/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerStokSayimHareketleriListeListeModelMesajlar } from './aaroKayitSonucAaroModullerStokSayimHareketleriListeListeModelMesajlar';
import type { AaroModullerStokSayimHareketleriListeListeModel } from './aaroModullerStokSayimHareketleriListeListeModel';

export interface AaroKayitSonucAaroModullerStokSayimHareketleriListeListeModel {
  Model?: AaroModullerStokSayimHareketleriListeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerStokSayimHareketleriListeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
