/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerSatinAlmaTalepListeListeModelMesajlar } from './aaroKayitSonucAaroModullerSatinAlmaTalepListeListeModelMesajlar.js';
import type { AaroModullerSatinAlmaTalepListeListeModel } from './aaroModullerSatinAlmaTalepListeListeModel.js';

export interface AaroKayitSonucAaroModullerSatinAlmaTalepListeListeModel {
  Model?: AaroModullerSatinAlmaTalepListeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerSatinAlmaTalepListeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
