/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerMuhasebeKayitSadeKayitModelMesajlar } from './aaroKayitSonucAaroModullerMuhasebeKayitSadeKayitModelMesajlar.js';
import type { AaroModullerMuhasebeKayitSadeKayitModel } from './aaroModullerMuhasebeKayitSadeKayitModel.js';

export interface AaroKayitSonucAaroModullerMuhasebeKayitSadeKayitModel {
  Model?: AaroModullerMuhasebeKayitSadeKayitModel;
  Mesajlar?: AaroKayitSonucAaroModullerMuhasebeKayitSadeKayitModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
