/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariIlgiliKayitSadeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariIlgiliKayitSadeListeModelMesajlar.js';
import type { AaroModullerCariIlgiliKayitSadeListeModel } from './aaroModullerCariIlgiliKayitSadeListeModel.js';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi.js';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariIlgiliKayitSadeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerCariIlgiliKayitSadeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariIlgiliKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
