/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroMVCControllersWebApiKalemModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroMVCControllersWebApiKalemModelMesajlar';
import type { AaroMVCControllersWebApiKalemModel } from './aaroMVCControllersWebApiKalemModel';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroMVCControllersWebApiKalemModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroMVCControllersWebApiKalemModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroMVCControllersWebApiKalemModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
