/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrAkisOperasyonKayitSadeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrAkisOperasyonKayitSadeListeModelMesajlar';
import type { AaroModullerUrAkisOperasyonKayitSadeListeModel } from './aaroModullerUrAkisOperasyonKayitSadeListeModel';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrAkisOperasyonKayitSadeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerUrAkisOperasyonKayitSadeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrAkisOperasyonKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
