/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerPaketKayitSadeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerPaketKayitSadeListeModelMesajlar';
import type { AaroModullerPaketKayitSadeListeModel } from './aaroModullerPaketKayitSadeListeModel';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerPaketKayitSadeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerPaketKayitSadeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerPaketKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
