/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerSubelerKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerSubelerKayitSadeListeModelMesajlar';
import type { AaroModullerSubelerKayitSadeListeModel } from './aaroModullerSubelerKayitSadeListeModel';

export interface AaroKayitSonucAaroModullerSubelerKayitSadeListeModel {
  Model?: AaroModullerSubelerKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerSubelerKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
