/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerCariRiskKayitSadeKayitModelMesajlar } from './aaroKayitSonucAaroModullerCariRiskKayitSadeKayitModelMesajlar';
import type { AaroModullerCariRiskKayitSadeKayitModel } from './aaroModullerCariRiskKayitSadeKayitModel';

export interface AaroKayitSonucAaroModullerCariRiskKayitSadeKayitModel {
  Model?: AaroModullerCariRiskKayitSadeKayitModel;
  Mesajlar?: AaroKayitSonucAaroModullerCariRiskKayitSadeKayitModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
