/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerAlisFaturasiHareketleriListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerAlisFaturasiHareketleriListeModelMesajlar';
import type { AaroModullerAlisFaturasiHareketleriListeModel } from './aaroModullerAlisFaturasiHareketleriListeModel';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerAlisFaturasiHareketleriListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerAlisFaturasiHareketleriListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerAlisFaturasiHareketleriListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
