/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerUrReceteKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerUrReceteKayitSadeListeModelMesajlar.js';
import type { AaroModullerUrReceteKayitSadeListeModel } from './aaroModullerUrReceteKayitSadeListeModel.js';

export interface AaroKayitSonucAaroModullerUrReceteKayitSadeListeModel {
  Model?: AaroModullerUrReceteKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerUrReceteKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
