/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerMasrafMerkeziKayitSadeKayitModelMesajlar } from './aaroKayitSonucAaroModullerMasrafMerkeziKayitSadeKayitModelMesajlar.js';
import type { AaroModullerMasrafMerkeziKayitSadeKayitModel } from './aaroModullerMasrafMerkeziKayitSadeKayitModel.js';

export interface AaroKayitSonucAaroModullerMasrafMerkeziKayitSadeKayitModel {
  Model?: AaroModullerMasrafMerkeziKayitSadeKayitModel;
  Mesajlar?: AaroKayitSonucAaroModullerMasrafMerkeziKayitSadeKayitModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
