/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerDegisiklikLoglariKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerDegisiklikLoglariKayitSadeListeModelMesajlar.js';
import type { AaroModullerDegisiklikLoglariKayitSadeListeModel } from './aaroModullerDegisiklikLoglariKayitSadeListeModel.js';

export interface AaroKayitSonucAaroModullerDegisiklikLoglariKayitSadeListeModel {
  Model?: AaroModullerDegisiklikLoglariKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerDegisiklikLoglariKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
