/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export interface AaroModullerVergiDairesiKayitSadeListeModel {
  EsnekAramaKisiti?: string;
  VDID?: number;
  VDKodu?: string;
  VDAdi?: string;
  VM?: string;
  IlID?: number;
  IlAdi?: string;
}
