/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerPerMesaiHareketDetayKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerPerMesaiHareketDetayKayitSadeListeModelMesajlar.js';
import type { AaroModullerPerMesaiHareketDetayKayitSadeListeModel } from './aaroModullerPerMesaiHareketDetayKayitSadeListeModel.js';

export interface AaroKayitSonucAaroModullerPerMesaiHareketDetayKayitSadeListeModel {
  Model?: AaroModullerPerMesaiHareketDetayKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerPerMesaiHareketDetayKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
