/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export interface AaroModullerUrAkisOperasyonHammaddeKayitSadeKayitModel {
  AkisOperasyonHammaddeID?: number;
  AkisOperasyonID?: number;
  ReceteOperasyonID?: number;
  HammaddeID?: number;
  Miktar?: number;
  Aciklama?: string;
  BirimMaliyetFiyati?: number;
  StokHareketID?: number;
}
