/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type AaroModullerAlisFaturasiListeListeModelOnayDurum = typeof AaroModullerAlisFaturasiListeListeModelOnayDurum[keyof typeof AaroModullerAlisFaturasiListeListeModelOnayDurum];


export const AaroModullerAlisFaturasiListeListeModelOnayDurum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_MINUS_1: -1,
} as const;
