/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucSystemCollectionsGenericIEnumerableAaroModullerUrReceteKayitSadeExcelModelDetayliMesajlar } from './aaroKayitSonucSystemCollectionsGenericIEnumerableAaroModullerUrReceteKayitSadeExcelModelDetayliMesajlar';
import type { AaroModullerUrReceteKayitSadeExcelModelDetayli } from './aaroModullerUrReceteKayitSadeExcelModelDetayli';

export interface AaroKayitSonucSystemCollectionsGenericIEnumerableAaroModullerUrReceteKayitSadeExcelModelDetayli {
  Model?: AaroModullerUrReceteKayitSadeExcelModelDetayli[];
  Mesajlar?: AaroKayitSonucSystemCollectionsGenericIEnumerableAaroModullerUrReceteKayitSadeExcelModelDetayliMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
