/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export interface AaroModullerCariBankaKayitSadeKayitModel {
  CariBankaID?: number;
  CariID?: number;
  BankaSubeID?: number;
  Adi?: string;
  Aciklama?: string;
  IbanNo?: string;
  Durum?: boolean;
  Oncelik?: boolean;
  DovizID?: number;
}
