/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerVerilenSiparisListeListeModelMesajlar } from './aaroKayitSonucAaroModullerVerilenSiparisListeListeModelMesajlar.js';
import type { AaroModullerVerilenSiparisListeListeModel } from './aaroModullerVerilenSiparisListeListeModel.js';

export interface AaroKayitSonucAaroModullerVerilenSiparisListeListeModel {
  Model?: AaroModullerVerilenSiparisListeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerVerilenSiparisListeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
