/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerUrAkisOperasyonKayitSadeKayitModelTipID } from './aaroModullerUrAkisOperasyonKayitSadeKayitModelTipID.js';
import type { AaroModullerUrAkisOperasyonKayitSadeMolaSaatleriViewModel } from './aaroModullerUrAkisOperasyonKayitSadeMolaSaatleriViewModel.js';
import type { AaroModullerUrAkisOperasyonKayitSadeStokBirimAD } from './aaroModullerUrAkisOperasyonKayitSadeStokBirimAD.js';
import type { AaroModullerUrAkisOperasyonKayitSadeUrAkisOperasyonHammaddeleri } from './aaroModullerUrAkisOperasyonKayitSadeUrAkisOperasyonHammaddeleri.js';
import type { AaroModullerUrAkisOperasyonKayitSadeUrAkisOperasyonMamulleri } from './aaroModullerUrAkisOperasyonKayitSadeUrAkisOperasyonMamulleri.js';
import type { AaroModullerUrAkisOperasyonKayitSadeUrAkisOperasyonPersonelleri } from './aaroModullerUrAkisOperasyonKayitSadeUrAkisOperasyonPersonelleri.js';

export interface AaroModullerUrAkisOperasyonKayitSadeKayitModel {
  HamListStokBirimAd?: AaroModullerUrAkisOperasyonKayitSadeStokBirimAD[];
  MamListStokBirimAd?: AaroModullerUrAkisOperasyonKayitSadeStokBirimAD[];
  AkisOperasyonID?: number;
  IsEmriID?: number;
  ReceteOperasyonID?: number;
  ReceteID?: number;
  OperasyonID?: number;
  MakineID?: number;
  DuraklamaNedenID?: number;
  HazirlikSure?: number;
  UretimSure?: number;
  IsciAdedi?: number;
  Aciklama?: string;
  DuraklamaNedeni?: string;
  TipID?: AaroModullerUrAkisOperasyonKayitSadeKayitModelTipID;
  Atlandi?: boolean;
  DuraklamaSure?: number;
  MolaSure?: number;
  Baslangic?: string;
  Bitis?: string;
  BaslangicSaat?: string;
  BitisSaat?: string;
  Durum?: boolean;
  OperasyonDetayID?: number;
  SorumluPersonelID?: number;
  KaliteKontrolBaslikID?: number;
  HammaddeListe?: AaroModullerUrAkisOperasyonKayitSadeUrAkisOperasyonHammaddeleri[];
  MamulListe?: AaroModullerUrAkisOperasyonKayitSadeUrAkisOperasyonMamulleri[];
  PersonelListe?: AaroModullerUrAkisOperasyonKayitSadeUrAkisOperasyonPersonelleri[];
  HamIstifNo?: string;
  MamIstifNo?: string;
  MolaSaatleri?: AaroModullerUrAkisOperasyonKayitSadeMolaSaatleriViewModel[];
}
