/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerKartlarUrBenzerlikKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerKartlarUrBenzerlikKayitSadeListeModelMesajlar.js';
import type { AaroModullerKartlarUrBenzerlikKayitSadeListeModel } from './aaroModullerKartlarUrBenzerlikKayitSadeListeModel.js';

export interface AaroKayitSonucAaroModullerKartlarUrBenzerlikKayitSadeListeModel {
  Model?: AaroModullerKartlarUrBenzerlikKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerKartlarUrBenzerlikKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
