/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerMasrafMerkeziKayitSadeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerMasrafMerkeziKayitSadeListeModelMesajlar.js';
import type { AaroModullerMasrafMerkeziKayitSadeListeModel } from './aaroModullerMasrafMerkeziKayitSadeListeModel.js';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi.js';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerMasrafMerkeziKayitSadeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerMasrafMerkeziKayitSadeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerMasrafMerkeziKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
