/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerSablonKayitSadeListeModelOnayDurum } from './aaroModullerSablonKayitSadeListeModelOnayDurum';
import type { AaroModullerSablonKayitSadeListeModelTabloID } from './aaroModullerSablonKayitSadeListeModelTabloID';

export interface AaroModullerSablonKayitSadeListeModel {
  OnayDurum?: AaroModullerSablonKayitSadeListeModelOnayDurum;
  OlsTar?: string;
  DgsTar?: string;
  OlsID?: number;
  OlsKodu?: string;
  OlsAdi?: string;
  DgsID?: number;
  DgsKodu?: string;
  DgsAdi?: string;
  EsnekAramaKisiti?: string;
  SablonID?: number;
  SablonKodu?: string;
  SablonAdi?: string;
  TabloID?: AaroModullerSablonKayitSadeListeModelTabloID;
  TabloAdi?: string;
  Aciklama?: string;
  Durum?: boolean;
}
