/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerKodlarKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerKodlarKayitSadeListeModelMesajlar.js';
import type { AaroModullerKodlarKayitSadeListeModel } from './aaroModullerKodlarKayitSadeListeModel.js';

export interface AaroKayitSonucAaroModullerKodlarKayitSadeListeModel {
  Model?: AaroModullerKodlarKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerKodlarKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
