/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerPerGirisCikisKayitSadeKayitModelMesajlar } from './aaroKayitSonucAaroModullerPerGirisCikisKayitSadeKayitModelMesajlar.js';
import type { AaroModullerPerGirisCikisKayitSadeKayitModel } from './aaroModullerPerGirisCikisKayitSadeKayitModel.js';

export interface AaroKayitSonucAaroModullerPerGirisCikisKayitSadeKayitModel {
  Model?: AaroModullerPerGirisCikisKayitSadeKayitModel;
  Mesajlar?: AaroKayitSonucAaroModullerPerGirisCikisKayitSadeKayitModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
