/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerAlisIrsaliyesiListeListeModelMesajlar } from './aaroKayitSonucAaroModullerAlisIrsaliyesiListeListeModelMesajlar.js';
import type { AaroModullerAlisIrsaliyesiListeListeModel } from './aaroModullerAlisIrsaliyesiListeListeModel.js';

export interface AaroKayitSonucAaroModullerAlisIrsaliyesiListeListeModel {
  Model?: AaroModullerAlisIrsaliyesiListeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerAlisIrsaliyesiListeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
