/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerSeriLotHareketleriKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerSeriLotHareketleriKayitSadeListeModelMesajlar';
import type { AaroModullerSeriLotHareketleriKayitSadeListeModel } from './aaroModullerSeriLotHareketleriKayitSadeListeModel';

export interface AaroKayitSonucAaroModullerSeriLotHareketleriKayitSadeListeModel {
  Model?: AaroModullerSeriLotHareketleriKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerSeriLotHareketleriKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
