/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

/**
 * Belgenin iş akışı üzerindeki onay durumu (Beklemede, Onaylandı, Reddedildi vb.).
 */
export type AaroMVCControllersWebApiBaslikModelOnayDurum = typeof AaroMVCControllersWebApiBaslikModelOnayDurum[keyof typeof AaroMVCControllersWebApiBaslikModelOnayDurum];


export const AaroMVCControllersWebApiBaslikModelOnayDurum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_MINUS_1: -1,
} as const;
