/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerUrOperasyonKayitSadeKayitModelMesajlar } from './aaroKayitSonucAaroModullerUrOperasyonKayitSadeKayitModelMesajlar.js';
import type { AaroModullerUrOperasyonKayitSadeKayitModel } from './aaroModullerUrOperasyonKayitSadeKayitModel.js';

export interface AaroKayitSonucAaroModullerUrOperasyonKayitSadeKayitModel {
  Model?: AaroModullerUrOperasyonKayitSadeKayitModel;
  Mesajlar?: AaroKayitSonucAaroModullerUrOperasyonKayitSadeKayitModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
