/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerBankaHareketleriListeListeModelMesajlar } from './aaroKayitSonucAaroModullerBankaHareketleriListeListeModelMesajlar.js';
import type { AaroModullerBankaHareketleriListeListeModel } from './aaroModullerBankaHareketleriListeListeModel.js';

export interface AaroKayitSonucAaroModullerBankaHareketleriListeListeModel {
  Model?: AaroModullerBankaHareketleriListeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerBankaHareketleriListeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
