/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export interface AaroModullerBelgeAdresKayitSadeBelgeBilgisi {
  BelgeAdresID?: number;
  BelgeAdresAdi?: string;
  BelgeAdresKodu?: string;
  Adres?: string;
  Uzanti?: string;
  /** Belgenin cachlenmesi icin kulanilabilcek degisiklik gecmisine ve belgenin detaylarina gore tutulan ozel kodu. Ayni belge icin belgede degisiklik yapildigindada guncellenir */
  BenzersizKodu?: string;
}
