/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerDepolarArasiTransferHareketleriListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerDepolarArasiTransferHareketleriListeModelMesajlar';
import type { AaroModullerDepolarArasiTransferHareketleriListeModel } from './aaroModullerDepolarArasiTransferHareketleriListeModel';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerDepolarArasiTransferHareketleriListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerDepolarArasiTransferHareketleriListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerDepolarArasiTransferHareketleriListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
