/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerAlinanSiparisListeListeModelMesajlar } from './aaroKayitSonucAaroModullerAlinanSiparisListeListeModelMesajlar.js';
import type { AaroModullerAlinanSiparisListeListeModel } from './aaroModullerAlinanSiparisListeListeModel.js';

export interface AaroKayitSonucAaroModullerAlinanSiparisListeListeModel {
  Model?: AaroModullerAlinanSiparisListeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerAlinanSiparisListeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
