/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerStokKayitSadeKayitModelFaturaKartTuru } from './aaroModullerStokKayitSadeKayitModelFaturaKartTuru';
import type { AaroModullerStokKayitSadeKayitModelTakipYontemi } from './aaroModullerStokKayitSadeKayitModelTakipYontemi';
import type { AaroModullerStokKayitSadeKayitModelTipID } from './aaroModullerStokKayitSadeKayitModelTipID';

/**
 * Stok kartı kayıt işlemleri için detay veri modeli.
Tüm stok bilgilerini içerir ve CRUD işlemlerinde kullanılır.
 */
export interface AaroModullerStokKayitSadeKayitModel {
  /** Stok kartının benzersiz kimlik numarası */
  StokID?: number;
  /** Stok kartının kodu (zorunlu, benzersiz) */
  StokKodu?: string;
  /** Stok kartının adı (zorunlu) */
  StokAdi?: string;
  /** Stok kartının kısa kodu (alternatif kod) */
  StokKisaKodu?: string;
  /** Stok kartının kısa adı (alternatif ad) */
  StokKisaAdi?: string;
  /** Eskiye uyumluluk icin tutuluyor. Kullanılmıyor */
  StokMuhasebeID?: number;
  /** Vergi ID'si - Stok kartının hangi vergilere tabi olduğunu tanımlar. KDV, Tevkifat, ÖTV ve diğer ek vergi alanları ve oranları alış ve satış işlemleri için Veri Tanımları ile ayarlanır */
  StokVergiID?: number;
  /** Ana birim ID'si (Adet, Kg, Lt vb. - zorunlu) */
  Brm1ID?: number;
  /** İkincil birim ID'si (koli, paket vb.) */
  Brm2ID?: number;
  /** Üçüncül birim ID'si (palet, sandık vb.) */
  Brm3ID?: number;
  /** Üretim birimi ID'si - Raporlarda üretim birimi cinsinden hızlı raporlama yapabilmek için kullanılır */
  UretimBrmID?: number;
  /** Rapor birimi ID'si -  Raporlarda bu birim cinsinden hızlı raporlama yapabilmek için kullanılır */
  RaporBrmID?: number;
  /** Ana birimden ikincil birime çevrim oranı - Örneğin : Birim1 degeri Adet olan  Stok kartı için Birim2 değeri Deste ise Çevirim 2 değeri 1/10 dan 0.1 olmalıdır */
  CevirimBrm2?: number;
  /** Ana birimden üçüncül birime çevrim oranı - Örneğin : Birim1 degeri Adet olan  Stok kartı için Birim3 değeri Kutu ise ve Kutuda 200Adet varsa  Çevirim 3 değeri 1/200 den 0.005 olmalıdır */
  CevirimBrm3?: number;
  /** Ürün kalınlığı (mm, cm vb.) */
  Kalinlik?: number;
  /** Ürün eni (mm, cm, m vb.) */
  En?: number;
  /** Ürün boyu (mm, cm, m vb.) */
  Boy?: number;
  /** Ürün yoğunluğu (kg/m³ vb.) */
  Yogunluk?: number;
  /** Ürün ağırlığı - kg cinsinden girilir. Faturalarda tonajı otomatik hesaplamada kullanılır */
  Agirlik?: number;
  /** Gümrük Tarife İstatistik Pozisyonu (dış ticaret için) */
  GTIP?: string;
  /** Dip satır kodu (dış ticaret için) */
  DIBSATIRKOD?: string;
  /** Hizmet kaydı mı? (true: hizmet, false: fiziksel ürün) Eksi bakiye ve miktar kontrolu için kullanılır. Hizmetlerde eksi bakiye ve miktar kontrolu yapılmaz */
  HizmetMi?: boolean;
  /** Standart ürün mü? Raporlamalarda ve sistem içinde standart ürünleri kategorilendirmek ve kolay erişim için kullanılır */
  StandartMi?: boolean;
  /** Demirbaş takibi zorunlu mu? Gelir ve Gider kartlarında karta işlenen hareketlerde demirbaş seçimini zorunlu yaparak giderin hangi demirbaş için yapıldığı takip edilir */
  ZorunluDemirbas?: boolean;
  /** Dekont takibi zorunlu mu? Gelir ve Gider kartlarında karta işlenen hareketlerde dekont seçimini zorunlu yaparak giderin hangi belge için yapıldığı takip edilir. Örneğin : sevk giderinin alış faturası ile ilişkilendirilmesi */
  ZorunluDekont?: boolean;
  /** Cari takibi zorunlu mu? Gelir ve Gider kartlarında karta işlenen hareketlerde cari seçimini zorunlu yaparak giderin hangi cari için yapıldığı takip edilir */
  ZorunluCari?: boolean;
  /** Masraf merkezi takibi zorunlu mu? Gelir ve Gider kartlarında karta işlenen hareketlerde masraf merkezi seçimini zorunlu yaparak giderin hangi masraf merkezi için yapıldığı takip edilir */
  ZorunluMasrafMerkezi?: boolean;
  /** Açıklamalar tablosu ID'si - Stok kartı için ek açıklamalar tutulur */
  AciklamalarID?: number;
  /** Stok kartı açıklaması */
  Aciklama?: string;
  /** Seviye */
  Seviye?: number;
  /** Fiyat etiketi bilgisi */
  FiyatEtiketi?: string;
  /** Bayi portalında görünsün mü? */
  BayiGozuksunMu?: boolean;
  /** Bayi portalında bayinin bu stok için görebileceği maks miktarı belirtir. Örneğin : 10 değeri girildiğinde ve depomuzda 5 adet olduğunda bayi 5 adet görür Fakat depomuzda 10 adetten fazla bulunduğunda bayi 10+ olarak görür. Kaç adet fazla olduğunu göremez. */
  BayiMaksMiktar?: number;
  /** Harici depodaki miktar (e-ticaret için) - Kendi depolarımız haricidende bu stoktan başka yerlerden hızlıca tedarik edilebiliyorsa buraya belirtilen miktar kadar depo miktarımız fazla gözükür */
  HariciDepoMiktar?: number;
  /** Kargo ücreti (e-ticaret için) */
  KargoUcreti?: number;
  /** Şube ID'si */
  SubeID?: number;
  /** Şirket ID'si */
  SirketID?: number;
  /** Aktif/Pasif durumu */
  Durum?: boolean;
  /** Stok tipi ID'si
              Vergi = 105000,
              Stok = 105001,
              GelirGider = 105002,
              DemirBas = 105003, */
  TipID?: AaroModullerStokKayitSadeKayitModelTipID;
  /** Muhasebeleşme ID'si - Muhasebeleşme sistemi ile bağlantı. Hangi Muhasebeleşme tanımı kullanılarak Muhasebe Hesap Planınında hangi hesaplara atılacağını belirler */
  EntegrasyonTanimID?: number;
  /** Kartları hiyerarşik olarak kategorilendirme kodlarıdır. Raporlama süreçlerini kolaylaştırır.
  1. Sınıflandırma kodu ID'si (örn: Ana Kategori) */
  Kod1ID?: number;
  /** 2. Sınıflandırma kodu ID'si (örn: Alt Kategori) */
  Kod2ID?: number;
  /** 3. Sınıflandırma kodu ID'si (örn: Marka) */
  Kod3ID?: number;
  /** 4. Sınıflandırma kodu ID'si (örn: Model) */
  Kod4ID?: number;
  /** 5. Sınıflandırma kodu ID'si (örn: Renk) */
  Kod5ID?: number;
  /** 6. Sınıflandırma kodu ID'si (örn: Beden) */
  Kod6ID?: number;
  /** Kartları farklı özelliklerine göre etiketlemek için kullanılır. Raporlama süreçlerini kolaylaştırır
  1. Etiket ID'si */
  Etiket1ID?: number;
  /** 2. Etiket ID'si */
  Etiket2ID?: number;
  /** 3. Etiket ID'si */
  Etiket3ID?: number;
  /** 4. Etiket ID'si */
  Etiket4ID?: number;
  /** 5. Etiket ID'si */
  Etiket5ID?: number;
  /** Yedek decimal alan 1 */
  YedekD1?: number;
  /** Yedek decimal alan 2 */
  YedekD2?: number;
  /** Yedek decimal alan 3 */
  YedekD3?: number;
  /** Yedek string alan 1 */
  YedekS1?: string;
  /** Yedek string alan 2 */
  YedekS2?: string;
  /** Yedek string alan 3 */
  YedekS3?: string;
  /** Şablon ID'si - Kart oluşturulurken ve düzenlenirken belirli bir formatta ve sınırlar dahilinde alanlarının ayarlanması istenildiğinde kullanılır. */
  SablonID?: number;
  /** Kart puanı - Kartın Program içinde kullanım sıklığını puanlar. Sistem otomatik ayarlar */
  KartPuan?: number;
  /** Stok takip yöntemi
  Normal = 0 Herhangi bir seri veya lot takibi yapılmaz
  Lot = 1 Lot numarası ile takip yapılır
  Seri = 2 Seri numarası ile takip yapılır */
  TakipYontemi?: AaroModullerStokKayitSadeKayitModelTakipYontemi;
  /** Takip yöntemi kod ön eki
  Otomatik Lot veya Seri numarası oluşturulmasında kullanılır */
  TakipYontemiKodOnEki?: string;
  /** Takip yönteminde üretim bire bir ilişki var mı?
  Çıkan ana mamül ile giren tüm yarımamul ve hammddelerin takip numaralarının bire bir eşleştirilmesi için kullanılır
  Bu şekilde çıkan her bir mamul serisi veya lotu için sipasifik olarak hangi hammdde serisi veya lotu kullanıldığı takip edilebilir.
  Seçilmez ise Aynı iş emrinden çıkan mamuller hangi hammadde lot veya serilerinden üretildiği genel olarak takip edilebilir. */
  TakipYontemiUretimBireBirIliski?: boolean;
  /** Raf takibi yapılsın mı?
  Bu stok kartı için detaylı raf takibi yapılmasını sağlar
  Depo kartında raf yönetimi aktif ise ve bu alan işaretli ise çalışır */
  RafTakibi?: boolean;
  /** Paket takibi yapılsın mı?
  Bu stok kartı için detaylı paket takibi yapılmasını sağlar
  Raf takip sistemi aktif ise ve bu alan işaretli ise çalışır */
  PaketTakibi?: boolean;
  /** Giriş kalite kontrol türü ID'si
  Alım işlemlerinde Stok kartı için hangi kalite kontrol esaslarına göre kalite kontrol yapılacağını belirler */
  GirisKaliteKontrolTurID?: number;
  /** Giriş kalite kontrol başlangıç tarihi
  Kalite kontrol zorunluluğunun hangi tarihten itibaren başlayacağını belirler */
  GirisKaliteKontrolBaslangic?: string;
  /** Reçete ID'si (üretim reçetesi için)
  Stok kartına ait ön tanımlı üretim reçetesini belirtir */
  ReceteID?: number;
  /** Reçete Adı (üretim reçetesi için)
  Stok kartına ait ön tanımlı üretim reçetesinin adını belirtir */
  ReceteAdi?: string;
  /** Reçete Kodu (üretim reçetesi için)
  Stok kartına ait ön tanımlı üretim reçetesinin kodunu belirtir */
  ReceteKodu?: string;
  /** WooCommerce ana ürün ID'si */
  WooParentID?: string;
  /** WooCommerce varyasyon ID'si */
  WooVariationID?: string;
  /** Ilaç ve tıbbi cihazlar için gererklidir kartın ilaç mı tıbbi cihaz mı olduğunu belitir */
  FaturaKartTuru?: AaroModullerStokKayitSadeKayitModelFaturaKartTuru;
}
