/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerSablonKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerSablonKayitSadeListeModelMesajlar';
import type { AaroModullerSablonKayitSadeListeModel } from './aaroModullerSablonKayitSadeListeModel';

export interface AaroKayitSonucAaroModullerSablonKayitSadeListeModel {
  Model?: AaroModullerSablonKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerSablonKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
