/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerKasaKayitSadeDetayliKayitModelAPITipID } from './aaroModullerKasaKayitSadeDetayliKayitModelAPITipID';
import type { AaroModullerKasaKayitSadeKasaEntegrasyonKayitModel } from './aaroModullerKasaKayitSadeKasaEntegrasyonKayitModel';

/**
 * Kasa kartı ve ilişkili entegrasyon tanımlarını (muhasebe hesapları vb.) içeren detaylı API veri modeli.
 */
export interface AaroModullerKasaKayitSadeDetayliKayitModelAPI {
  EntegrasyonTanimi?: AaroModullerKasaKayitSadeKasaEntegrasyonKayitModel;
  /** Kasa kartının benzersiz kimlik numarası */
  KasaID?: number;
  /** Kasa kodu (zorunlu, benzersiz) */
  KasaKodu?: string;
  /** Kasa adı (zorunlu) */
  KasaAdi?: string;
  /** Çalışma para birimi ID'si */
  DovizID?: number;
  /** Kasa seviyesi (hiyerarşik takip için) */
  Seviye?: number;
  /** Şube kimlik numarası */
  SubeID?: number;
  /** Şirket kimlik numarası */
  SirketID?: number;
  /** Aktif/Pasif durumu */
  Durum?: boolean;
  /** Kasa tipi ID'si */
  TipID?: AaroModullerKasaKayitSadeDetayliKayitModelAPITipID;
  /** Muhasebeleşme ID'si - Muhasebeleşme sistemi ile bağlantı */
  EntegrasyonTanimID?: number;
  /** 1. Sınıflandırma kodu ID'si */
  Kod1ID?: number;
  /** 2. Sınıflandırma kodu ID'si */
  Kod2ID?: number;
  /** 3. Sınıflandırma kodu ID'si */
  Kod3ID?: number;
  /** 4. Sınıflandırma kodu ID'si */
  Kod4ID?: number;
  /** 5. Sınıflandırma kodu ID'si */
  Kod5ID?: number;
  /** 6. Sınıflandırma kodu ID'si */
  Kod6ID?: number;
  /** 1. Etiket ID'si */
  Etiket1ID?: number;
  /** 2. Etiket ID'si */
  Etiket2ID?: number;
  /** 3. Etiket ID'si */
  Etiket3ID?: number;
  /** 4. Etiket ID'si */
  Etiket4ID?: number;
  /** 5. Etiket ID'si */
  Etiket5ID?: number;
  /** Yedek decimal alan 1 */
  YedekD1?: number;
  /** Yedek decimal alan 2 */
  YedekD2?: number;
  /** Yedek decimal alan 3 */
  YedekD3?: number;
  /** Yedek string alan 1 */
  YedekS1?: string;
  /** Yedek string alan 2 */
  YedekS2?: string;
  /** Yedek string alan 3 */
  YedekS3?: string;
  /** Şablon ID'si - Kartın belirli bir formatta ayarlanması için kullanılır */
  SablonID?: number;
}
