/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { _AaroModullerGorevlerKayitSadeGorevEkleAPIModelProgramID } from './_aaroModullerGorevlerKayitSadeGorevEkleAPIModelProgramID.js';
import type { _AaroModullerGorevlerKayitSadeGorevEkleAPIModelTabloID } from './_aaroModullerGorevlerKayitSadeGorevEkleAPIModelTabloID.js';
import type { AaroModellerEtiketler } from './aaroModellerEtiketler.js';
import type { AaroModellerGorevHareketleri } from './aaroModellerGorevHareketleri.js';
import type { AaroModellerGorevKullanicilari } from './aaroModellerGorevKullanicilari.js';
import type { AaroModellerKullanicilar } from './aaroModellerKullanicilar.js';
import type { AaroModullerGorevlerKayitSadeGorevEkleAPIModelBitisTuru } from './aaroModullerGorevlerKayitSadeGorevEkleAPIModelBitisTuru.js';
import type { AaroModullerGorevlerKayitSadeGorevEkleAPIModelOnayDurum } from './aaroModullerGorevlerKayitSadeGorevEkleAPIModelOnayDurum.js';
import type { AaroModullerGorevlerKayitSadeGorevEkleAPIModelTabloID } from './aaroModullerGorevlerKayitSadeGorevEkleAPIModelTabloID.js';
import type { AaroModullerGorevlerKayitSadeGorevEkleAPIModelTabloID2 } from './aaroModullerGorevlerKayitSadeGorevEkleAPIModelTabloID2.js';
import type { AaroModullerGorevlerKayitSadeGorevEkleAPIModelTamamlanmaTipi } from './aaroModullerGorevlerKayitSadeGorevEkleAPIModelTamamlanmaTipi.js';
import type { AaroModullerGorevlerKayitSadeGorevEkleAPIModelTekrarSekli } from './aaroModullerGorevlerKayitSadeGorevEkleAPIModelTekrarSekli.js';
import type { AaroModullerGorevlerKayitSadeGorevEkleAPIModelTipID } from './aaroModullerGorevlerKayitSadeGorevEkleAPIModelTipID.js';

export interface AaroModullerGorevlerKayitSadeGorevEkleAPIModel {
  GorevKullanicilari?: AaroModellerGorevKullanicilari[];
  GorevYoneticileri?: AaroModellerGorevKullanicilari[];
  readonly __TabloID?: _AaroModullerGorevlerKayitSadeGorevEkleAPIModelTabloID;
  readonly __ProgramID?: _AaroModullerGorevlerKayitSadeGorevEkleAPIModelProgramID;
  GorevID?: number;
  /**
     * @minLength 0
     * @maxLength 250
     */
  GorevAdi: string;
  /**
     * @minLength 0
     * @maxLength 1000
     */
  Aciklama?: string;
  TipID?: AaroModullerGorevlerKayitSadeGorevEkleAPIModelTipID;
  UstGorevID?: number;
  TekrarAnaGorevID?: number;
  TarihBit?: string;
  HatirlatmaGunSayisi?: number;
  TamamlanmaOrani?: number;
  Tamamlandi?: boolean;
  DegisiklikOlanaKadarGosterme?: boolean;
  EtiketID?: number;
  Oncelik?: number;
  TamamlanmaTipi?: AaroModullerGorevlerKayitSadeGorevEkleAPIModelTamamlanmaTipi;
  TabloID?: AaroModullerGorevlerKayitSadeGorevEkleAPIModelTabloID;
  TabloSatirID?: number;
  TabloID2?: AaroModullerGorevlerKayitSadeGorevEkleAPIModelTabloID2;
  TabloSatirID2?: number;
  TekrarSekli?: AaroModullerGorevlerKayitSadeGorevEkleAPIModelTekrarSekli;
  Periyot?: number;
  BitisTuru?: AaroModullerGorevlerKayitSadeGorevEkleAPIModelBitisTuru;
  HaftaninGunleri?: string;
  TekrarDeger1?: number;
  TekrarDeger2?: number;
  TekrarAdedi?: number;
  TekrarBitisTarih?: string;
  Durum?: boolean;
  OnayDurum?: AaroModullerGorevlerKayitSadeGorevEkleAPIModelOnayDurum;
  OlsID?: number;
  OlsTar?: string;
  DgsID?: number;
  DgsTar?: string;
  i_GorevKullanicilari?: AaroModellerGorevKullanicilari[];
  i_GorevHareketleri?: AaroModellerGorevHareketleri[];
  Etiket?: AaroModellerEtiketler;
  Ols?: AaroModellerKullanicilar;
  Dgs?: AaroModellerKullanicilar;
}
