/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroMVCControllersWebApiBayiControllerBayiSiparisModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroMVCControllersWebApiBayiControllerBayiSiparisModelMesajlar.js';
import type { AaroMVCControllersWebApiBayiControllerBayiSiparisModel } from './aaroMVCControllersWebApiBayiControllerBayiSiparisModel.js';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi.js';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroMVCControllersWebApiBayiControllerBayiSiparisModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroMVCControllersWebApiBayiControllerBayiSiparisModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroMVCControllersWebApiBayiControllerBayiSiparisModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
