/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisIrsaliyesiListeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisIrsaliyesiListeListeModelMesajlar';
import type { AaroModullerSatisIrsaliyesiListeListeModel } from './aaroModullerSatisIrsaliyesiListeListeModel';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisIrsaliyesiListeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerSatisIrsaliyesiListeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisIrsaliyesiListeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
