/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerAlisIadeIrsaliyesiListeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerAlisIadeIrsaliyesiListeListeModelMesajlar.js';
import type { AaroModullerAlisIadeIrsaliyesiListeListeModel } from './aaroModullerAlisIadeIrsaliyesiListeListeModel.js';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi.js';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerAlisIadeIrsaliyesiListeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerAlisIadeIrsaliyesiListeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerAlisIadeIrsaliyesiListeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
