/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerStokVergiKayitSadeKayitModelMesajlar } from './aaroKayitSonucAaroModullerStokVergiKayitSadeKayitModelMesajlar.js';
import type { AaroModullerStokVergiKayitSadeKayitModel } from './aaroModullerStokVergiKayitSadeKayitModel.js';

export interface AaroKayitSonucAaroModullerStokVergiKayitSadeKayitModel {
  Model?: AaroModullerStokVergiKayitSadeKayitModel;
  Mesajlar?: AaroKayitSonucAaroModullerStokVergiKayitSadeKayitModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
