/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerUrOperasyonKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerUrOperasyonKayitSadeListeModelMesajlar.js';
import type { AaroModullerUrOperasyonKayitSadeListeModel } from './aaroModullerUrOperasyonKayitSadeListeModel.js';

export interface AaroKayitSonucAaroModullerUrOperasyonKayitSadeListeModel {
  Model?: AaroModullerUrOperasyonKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerUrOperasyonKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
