/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerKullanicilarKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerKullanicilarKayitSadeListeModelMesajlar.js';
import type { AaroModullerKullanicilarKayitSadeListeModel } from './aaroModullerKullanicilarKayitSadeListeModel.js';

export interface AaroKayitSonucAaroModullerKullanicilarKayitSadeListeModel {
  Model?: AaroModullerKullanicilarKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerKullanicilarKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
