/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisFaturasiHareketleriListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisFaturasiHareketleriListeModelMesajlar';
import type { AaroModullerSatisFaturasiHareketleriListeModel } from './aaroModullerSatisFaturasiHareketleriListeModel';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisFaturasiHareketleriListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerSatisFaturasiHareketleriListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisFaturasiHareketleriListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
