/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrReceteOperasyonHammaddeKayitSadeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrReceteOperasyonHammaddeKayitSadeListeModelMesajlar.js';
import type { AaroModullerUrReceteOperasyonHammaddeKayitSadeListeModel } from './aaroModullerUrReceteOperasyonHammaddeKayitSadeListeModel.js';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi.js';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrReceteOperasyonHammaddeKayitSadeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerUrReceteOperasyonHammaddeKayitSadeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrReceteOperasyonHammaddeKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
