/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export interface AaroModullerKullaniciGruplarKayitSadeKayitModel {
  GrupID?: number;
  GrupKodu?: string;
  GrupAdi?: string;
  Etiket1ID?: number;
  Etiket2ID?: number;
  Etiket3ID?: number;
  Etiket4ID?: number;
  Etiket5ID?: number;
  Durum?: boolean;
}
