/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerOlcuBirimleriKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerOlcuBirimleriKayitSadeListeModelMesajlar';
import type { AaroModullerOlcuBirimleriKayitSadeListeModel } from './aaroModullerOlcuBirimleriKayitSadeListeModel';

export interface AaroKayitSonucAaroModullerOlcuBirimleriKayitSadeListeModel {
  Model?: AaroModullerOlcuBirimleriKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerOlcuBirimleriKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
