/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerBeklenenTahsilatlarVeOdemelerKayitSadeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerBeklenenTahsilatlarVeOdemelerKayitSadeListeModelMesajlar';
import type { AaroModullerBeklenenTahsilatlarVeOdemelerKayitSadeListeModel } from './aaroModullerBeklenenTahsilatlarVeOdemelerKayitSadeListeModel';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerBeklenenTahsilatlarVeOdemelerKayitSadeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerBeklenenTahsilatlarVeOdemelerKayitSadeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerBeklenenTahsilatlarVeOdemelerKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
