/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerCariKayitSadeKayitModelMesajlar } from './aaroKayitSonucAaroModullerCariKayitSadeKayitModelMesajlar';
import type { AaroModullerCariKayitSadeKayitModel } from './aaroModullerCariKayitSadeKayitModel';

export interface AaroKayitSonucAaroModullerCariKayitSadeKayitModel {
  Model?: AaroModullerCariKayitSadeKayitModel;
  Mesajlar?: AaroKayitSonucAaroModullerCariKayitSadeKayitModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
