/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerGorevKullanicilariKayitSadeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerGorevKullanicilariKayitSadeListeModelMesajlar.js';
import type { AaroModullerGorevKullanicilariKayitSadeListeModel } from './aaroModullerGorevKullanicilariKayitSadeListeModel.js';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi.js';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerGorevKullanicilariKayitSadeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerGorevKullanicilariKayitSadeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerGorevKullanicilariKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
