/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroMVCControllersWebApiBaslikModel } from './aaroMVCControllersWebApiBaslikModel.js';
import type { AaroMVCControllersWebApiKalemModel } from './aaroMVCControllersWebApiKalemModel.js';

export interface AaroMVCControllersWebApiBaslikKalemTekKalemCokModel {
  Baslik?: AaroMVCControllersWebApiBaslikModel;
  KalemTek?: AaroMVCControllersWebApiKalemModel;
  KalemCok?: AaroMVCControllersWebApiKalemModel;
}
