/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisIadeFaturasiListeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisIadeFaturasiListeListeModelMesajlar';
import type { AaroModullerSatisIadeFaturasiListeListeModel } from './aaroModullerSatisIadeFaturasiListeListeModel';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisIadeFaturasiListeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerSatisIadeFaturasiListeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisIadeFaturasiListeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
