/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerSablonKayitSadeKayitModelTabloID } from './aaroModullerSablonKayitSadeKayitModelTabloID.js';

export interface AaroModullerSablonKayitSadeKayitModel {
  SablonID?: number;
  SablonKodu?: string;
  SablonAdi?: string;
  TabloID?: AaroModullerSablonKayitSadeKayitModelTabloID;
  TabloAdi?: string;
  Aciklama?: string;
  Durum?: boolean;
}
