/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export interface AaroModullerKaliteKontrolDetayKayitSadeListeModel {
  KaliteKontrolTurDetayAdi?: string;
  KaliteKontrolTurKodu?: string;
  KaliteKontrolTurAdi?: string;
  OlcumAletiKodu?: string;
  OlcumAletiAdi?: string;
  OlsTar?: string;
  DgsTar?: string;
  OlsID?: number;
  OlsKodu?: string;
  OlsAdi?: string;
  DgsID?: number;
  DgsKodu?: string;
  DgsAdi?: string;
  KaliteKontrolDetayID?: number;
  KaliteKontrolTurDetayID?: number;
  KaliteKontrolTurID?: number;
  KaliteKontrolID?: number;
  SayisalSonuc?: number;
  TarihSonuc?: string;
  DogruYanlisSonuc?: boolean;
  MetinSonuc?: string;
  OlcumAletiID?: number;
}
