/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerPerOnayBaslikKayitSadeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerPerOnayBaslikKayitSadeListeModelMesajlar.js';
import type { AaroModullerPerOnayBaslikKayitSadeListeModel } from './aaroModullerPerOnayBaslikKayitSadeListeModel.js';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi.js';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerPerOnayBaslikKayitSadeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerPerOnayBaslikKayitSadeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerPerOnayBaslikKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
