/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariAdresKayitSadeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariAdresKayitSadeListeModelMesajlar';
import type { AaroModullerCariAdresKayitSadeListeModel } from './aaroModullerCariAdresKayitSadeListeModel';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariAdresKayitSadeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerCariAdresKayitSadeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariAdresKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
