/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerDisardanAktarimEkKodlarExcelModelTip2ID } from './aaroModullerDisardanAktarimEkKodlarExcelModelTip2ID';
import type { AaroModullerDisardanAktarimEkKodlarExcelModelTipID } from './aaroModullerDisardanAktarimEkKodlarExcelModelTipID';

export interface AaroModullerDisardanAktarimEkKodlarExcelModel {
  SirketID?: number;
  SubeID?: number;
  TipID?: AaroModullerDisardanAktarimEkKodlarExcelModelTipID;
  Tip2ID?: AaroModullerDisardanAktarimEkKodlarExcelModelTip2ID;
  Kod1ID?: number;
  Kod2ID?: number;
  Kod3ID?: number;
  Kod4ID?: number;
  Kod5ID?: number;
  Kod6ID?: number;
  Kod1?: string;
  Kod2?: string;
  Kod3?: string;
  Kod4?: string;
  Kod5?: string;
  Kod6?: string;
}
