/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerPaketKayitSadeKayitModel } from './aaroModullerPaketKayitSadeKayitModel.js';

export type AaroModullerPaketKayitSadeKayitModelBody = AaroModullerPaketKayitSadeKayitModel;
