/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrAkisOperasyonMamulKayitSadeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrAkisOperasyonMamulKayitSadeListeModelMesajlar';
import type { AaroModullerUrAkisOperasyonMamulKayitSadeListeModel } from './aaroModullerUrAkisOperasyonMamulKayitSadeListeModel';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrAkisOperasyonMamulKayitSadeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerUrAkisOperasyonMamulKayitSadeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrAkisOperasyonMamulKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
