/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export interface AaroModullerKaliteKontrolBaslikKayitSadeKayitModel {
  KaliteKontrolBaslikID?: number;
  SubeID?: number;
  SirketID?: number;
  Tarih?: string;
  Kapali?: boolean;
}
