/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokDepoMiktarKayitSadeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokDepoMiktarKayitSadeListeModelMesajlar';
import type { AaroModullerStokDepoMiktarKayitSadeListeModel } from './aaroModullerStokDepoMiktarKayitSadeListeModel';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokDepoMiktarKayitSadeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerStokDepoMiktarKayitSadeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokDepoMiktarKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
