/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerPersonelKayitSadeKayitModelMesajlar } from './aaroKayitSonucAaroModullerPersonelKayitSadeKayitModelMesajlar.js';
import type { AaroModullerPersonelKayitSadeKayitModel } from './aaroModullerPersonelKayitSadeKayitModel.js';

export interface AaroKayitSonucAaroModullerPersonelKayitSadeKayitModel {
  Model?: AaroModullerPersonelKayitSadeKayitModel;
  Mesajlar?: AaroKayitSonucAaroModullerPersonelKayitSadeKayitModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
