/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerSatisIadeFaturasiListeListeModelMesajlar } from './aaroKayitSonucAaroModullerSatisIadeFaturasiListeListeModelMesajlar.js';
import type { AaroModullerSatisIadeFaturasiListeListeModel } from './aaroModullerSatisIadeFaturasiListeListeModel.js';

export interface AaroKayitSonucAaroModullerSatisIadeFaturasiListeListeModel {
  Model?: AaroModullerSatisIadeFaturasiListeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerSatisIadeFaturasiListeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
