/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerEntegrasyonTanimKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerEntegrasyonTanimKayitSadeListeModelMesajlar';
import type { AaroModullerEntegrasyonTanimKayitSadeListeModel } from './aaroModullerEntegrasyonTanimKayitSadeListeModel';

export interface AaroKayitSonucAaroModullerEntegrasyonTanimKayitSadeListeModel {
  Model?: AaroModullerEntegrasyonTanimKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerEntegrasyonTanimKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
