/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerStokKayitSadeDetayliKayitModelAPIMesajlar } from './aaroKayitSonucAaroModullerStokKayitSadeDetayliKayitModelAPIMesajlar';
import type { AaroModullerStokKayitSadeDetayliKayitModelAPI } from './aaroModullerStokKayitSadeDetayliKayitModelAPI';

export interface AaroKayitSonucAaroModullerStokKayitSadeDetayliKayitModelAPI {
  Model?: AaroModullerStokKayitSadeDetayliKayitModelAPI;
  Mesajlar?: AaroKayitSonucAaroModullerStokKayitSadeDetayliKayitModelAPIMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
