/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerCariZiyaretKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerCariZiyaretKayitSadeListeModelMesajlar';
import type { AaroModullerCariZiyaretKayitSadeListeModel } from './aaroModullerCariZiyaretKayitSadeListeModel';

export interface AaroKayitSonucAaroModullerCariZiyaretKayitSadeListeModel {
  Model?: AaroModullerCariZiyaretKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerCariZiyaretKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
