/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrOperasyonMakineKayitSadeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrOperasyonMakineKayitSadeListeModelMesajlar.js';
import type { AaroModullerUrOperasyonMakineKayitSadeListeModel } from './aaroModullerUrOperasyonMakineKayitSadeListeModel.js';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi.js';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrOperasyonMakineKayitSadeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerUrOperasyonMakineKayitSadeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrOperasyonMakineKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
