/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerYetkilerKayitSadeKayitModelProgramID } from './aaroModullerYetkilerKayitSadeKayitModelProgramID';

export interface AaroModullerYetkilerKayitSadeKayitModel {
  StrID?: number;
  KullaniciID?: number;
  KullaniciGrupID?: number;
  ProgramID?: AaroModullerYetkilerKayitSadeKayitModelProgramID;
  Okuma?: boolean;
  Ekleme?: boolean;
  Silme?: boolean;
  Duzeltme?: boolean;
  Indirme?: boolean;
  SirketID?: number;
  SubeID?: number;
}
