/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerNotlarKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerNotlarKayitSadeListeModelMesajlar.js';
import type { AaroModullerNotlarKayitSadeListeModel } from './aaroModullerNotlarKayitSadeListeModel.js';

export interface AaroKayitSonucAaroModullerNotlarKayitSadeListeModel {
  Model?: AaroModullerNotlarKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerNotlarKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
