/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokKayitSadeMinModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokKayitSadeMinModelMesajlar';
import type { AaroModullerStokKayitSadeMinModel } from './aaroModullerStokKayitSadeMinModel';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokKayitSadeMinModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerStokKayitSadeMinModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokKayitSadeMinModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
