/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgiMesajlar } from './aaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgiMesajlar.js';
import type { AaroModullerOnayDurumBilgisiODBilgi } from './aaroModullerOnayDurumBilgisiODBilgi.js';

export interface AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi {
  Model?: AaroModullerOnayDurumBilgisiODBilgi[];
  Mesajlar?: AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgiMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
