/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerCekSenetKayitSadeListeModelDevirSonDurumID } from './aaroModullerCekSenetKayitSadeListeModelDevirSonDurumID.js';
import type { AaroModullerCekSenetKayitSadeListeModelOnayDurum } from './aaroModullerCekSenetKayitSadeListeModelOnayDurum.js';
import type { AaroModullerCekSenetKayitSadeListeModelSonDurumID } from './aaroModullerCekSenetKayitSadeListeModelSonDurumID.js';
import type { AaroModullerCekSenetKayitSadeListeModelTipID } from './aaroModullerCekSenetKayitSadeListeModelTipID.js';

export interface AaroModullerCekSenetKayitSadeListeModel {
  OnayDurum?: AaroModullerCekSenetKayitSadeListeModelOnayDurum;
  OlsTar?: string;
  DgsTar?: string;
  OlsID?: number;
  OlsKodu?: string;
  OlsAdi?: string;
  DgsID?: number;
  DgsKodu?: string;
  DgsAdi?: string;
  CariAdi?: string;
  CariKodu?: string;
  BankaHesapID?: number;
  BankaHesapAdi?: string;
  Tipi?: string;
  DovizKodu?: string;
  DovizSembol?: string;
  YeriCariAdi?: string;
  YeriBankaHesapAdi?: string;
  BA?: string;
  SonDurumAdi?: string;
  SirketAdi?: string;
  BankaAdi?: string;
  Bakiye?: number;
  CekSenetID?: number;
  SirketID?: number;
  SubeID?: number;
  TipID?: AaroModullerCekSenetKayitSadeListeModelTipID;
  CariID?: number;
  Tarih?: string;
  Vade?: string;
  Tutar?: number;
  DovizID?: number;
  TutarDvz?: number;
  YedekT?: number;
  YedekTD?: number;
  AsilMi?: boolean;
  AsilVergiNumarasi?: string;
  AsilAdi?: string;
  SeriNo?: string;
  BankaSubeID?: number;
  KesideIlID?: number;
  SonDurumID?: AaroModullerCekSenetKayitSadeListeModelSonDurumID;
  DevirSonDurumID?: AaroModullerCekSenetKayitSadeListeModelDevirSonDurumID;
  ProjeID?: number;
  PlasiyerID?: number;
  SozlesmeID?: number;
  MuhasebeBorcID?: number;
  MuhasebeAlacakID?: number;
  YeriCariID?: number;
  YeriBankaHesapID?: number;
  Aciklama?: string;
  SablonID?: number;
  EntegrasyonTanimID?: number;
  YedekD1?: number;
  YedekD2?: number;
  YedekD3?: number;
  YedekS1?: string;
  YedekS2?: string;
  YedekS3?: string;
}
