/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerStokBarkodKayitSadeKayitModelMesajlar } from './aaroKayitSonucAaroModullerStokBarkodKayitSadeKayitModelMesajlar.js';
import type { AaroModullerStokBarkodKayitSadeKayitModel } from './aaroModullerStokBarkodKayitSadeKayitModel.js';

export interface AaroKayitSonucAaroModullerStokBarkodKayitSadeKayitModel {
  Model?: AaroModullerStokBarkodKayitSadeKayitModel;
  Mesajlar?: AaroKayitSonucAaroModullerStokBarkodKayitSadeKayitModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
