/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerUrReceteKayitSadeKayitModelTipID } from './aaroModullerUrReceteKayitSadeKayitModelTipID';

export interface AaroModullerUrReceteKayitSadeKayitModel {
  ReceteID?: number;
  ReceteKodu?: string;
  ReceteAdi?: string;
  SubeID?: number;
  SirketID?: number;
  Durum?: boolean;
  TipID?: AaroModullerUrReceteKayitSadeKayitModelTipID;
  Aciklama?: string;
  IsEmriID?: number;
  IscilikMaliyetiSaat?: number;
  CalismaMaliyetiSaat?: number;
  DovizID?: number;
  KaynakReceteID?: number;
  Kod1ID?: number;
  Kod2ID?: number;
  Kod3ID?: number;
  Kod4ID?: number;
  Kod5ID?: number;
  Kod6ID?: number;
  Etiket1ID?: number;
  Etiket2ID?: number;
  Etiket3ID?: number;
  Etiket4ID?: number;
  Etiket5ID?: number;
  YedekD1?: number;
  YedekD2?: number;
  YedekD3?: number;
  YedekS1?: string;
  YedekS2?: string;
  YedekS3?: string;
  OperasyonID?: number;
  MakineID?: number;
  HazirlikSure?: number;
  UretimSure?: number;
  IsciAdedi?: number;
  HesapAciklamasi?: string;
  RecAciklama?: string;
  MamulID?: number;
  Miktar?: number;
  MamAciklama?: string;
  MamBirimBasiEkMaliyet?: number;
  HammaddeID?: number;
  HammaddeMiktar?: number;
  HammaddeFiyat?: number;
  HammaddeAciklama?: string;
  KopyalaID?: number;
  AltRecetelerKopyalansin?: boolean;
}
