/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerFiyatListesiSatirlarKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerFiyatListesiSatirlarKayitSadeListeModelMesajlar.js';
import type { AaroModullerFiyatListesiSatirlarKayitSadeListeModel } from './aaroModullerFiyatListesiSatirlarKayitSadeListeModel.js';

export interface AaroKayitSonucAaroModullerFiyatListesiSatirlarKayitSadeListeModel {
  Model?: AaroModullerFiyatListesiSatirlarKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerFiyatListesiSatirlarKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
