/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerBankaKayitSadeListeModelOnayDurum } from './aaroModullerBankaKayitSadeListeModelOnayDurum.js';

export interface AaroModullerBankaKayitSadeListeModel {
  OnayDurum?: AaroModullerBankaKayitSadeListeModelOnayDurum;
  OlsTar?: string;
  DgsTar?: string;
  OlsID?: number;
  OlsKodu?: string;
  OlsAdi?: string;
  DgsID?: number;
  DgsKodu?: string;
  DgsAdi?: string;
  BankaID?: number;
  BankaKodu?: string;
  BankaAdi?: string;
  Durum?: boolean;
}
