/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariHareketleriListeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariHareketleriListeListeModelMesajlar.js';
import type { AaroModullerCariHareketleriListeListeModel } from './aaroModullerCariHareketleriListeListeModel.js';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi.js';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariHareketleriListeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerCariHareketleriListeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariHareketleriListeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
