/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerDepoKayitSadeListeModelOnayDurum } from './aaroModullerDepoKayitSadeListeModelOnayDurum.js';
import type { AaroModullerDepoKayitSadeListeModelTipID } from './aaroModullerDepoKayitSadeListeModelTipID.js';

export interface AaroModullerDepoKayitSadeListeModel {
  SubeKodu?: string;
  SubeAdi?: string;
  SirketKodu?: string;
  SirketAdi?: string;
  TipAdi?: string;
  TipKodu?: string;
  CariKodu?: string;
  CariAdi?: string;
  OnayDurum?: AaroModullerDepoKayitSadeListeModelOnayDurum;
  OlsTar?: string;
  DgsTar?: string;
  OlsID?: number;
  OlsKodu?: string;
  OlsAdi?: string;
  DgsID?: number;
  DgsKodu?: string;
  DgsAdi?: string;
  Kod1Kodu?: string;
  Kod2Kodu?: string;
  Kod3Kodu?: string;
  Kod4Kodu?: string;
  Kod5Kodu?: string;
  Kod6Kodu?: string;
  Kod1Adi?: string;
  Kod2Adi?: string;
  Kod3Adi?: string;
  Kod4Adi?: string;
  Kod5Adi?: string;
  Kod6Adi?: string;
  Etiket1Adi?: string;
  Etiket2Adi?: string;
  Etiket3Adi?: string;
  Etiket4Adi?: string;
  Etiket5Adi?: string;
  SablonKodu?: string;
  SablonAdi?: string;
  ResimAdresi?: string;
  EsnekAramaKisiti?: string;
  DepoID?: number;
  DepoKodu?: string;
  DepoAdi?: string;
  CariID?: number;
  MaxHacim?: string;
  MaxAgirlik?: number;
  SubeID?: number;
  SirketID?: number;
  Durum?: boolean;
  TipID?: AaroModullerDepoKayitSadeListeModelTipID;
  Kod1ID?: number;
  Kod2ID?: number;
  Kod3ID?: number;
  Kod4ID?: number;
  Kod5ID?: number;
  Kod6ID?: number;
  Etiket1ID?: number;
  Etiket2ID?: number;
  Etiket3ID?: number;
  Etiket4ID?: number;
  Etiket5ID?: number;
  SablonID?: number;
  RafTakibi?: boolean;
  PaketTakibi?: boolean;
}
