/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export interface AaroModullerAciklamalarKayitSadeKayitModel {
  AciklamaID?: number;
  A1?: string;
  A2?: string;
  A3?: string;
  A4?: string;
  A5?: string;
  A6?: string;
  A7?: string;
  A8?: string;
  A9?: string;
  A10?: string;
  A11?: string;
}
