/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisiMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisiMesajlar';
import type { AaroModullerNotlarKayitSadeNotBilgisi } from './aaroModullerNotlarKayitSadeNotBilgisi';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';

export interface AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerNotlarKayitSadeNotBilgisi[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisiMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
