/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerKaliteKontrolleriKayitSadeKayitModelKaliteKontrolDurum } from './aaroModullerKaliteKontrolleriKayitSadeKayitModelKaliteKontrolDurum';

export interface AaroModullerKaliteKontrolleriKayitSadeKayitModel {
  KaliteKontrolID?: number;
  KaliteKontrolTurID?: number;
  KaliteKontrolBaslikID?: number;
  KartKodu?: string;
  SeriLotID?: number;
  TestMiktar?: number;
  KontrolMiktar?: number;
  SubeID?: number;
  SirketID?: number;
  Durum?: boolean;
  KaliteKontrolDurum?: AaroModullerKaliteKontrolleriKayitSadeKayitModelKaliteKontrolDurum;
  Aciklama?: string;
  AciklamaOtomatik?: string;
  Tarih?: string;
}
