/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerTakvimKayitSadeKayitModelTipID } from './aaroModullerTakvimKayitSadeKayitModelTipID';

export interface AaroModullerTakvimKayitSadeKayitModel {
  TakvimID?: number;
  TakvimKodu?: string;
  TakvimAdi?: string;
  SubeID?: number;
  SirketID?: number;
  TipID?: AaroModullerTakvimKayitSadeKayitModelTipID;
  Durum?: boolean;
}
