/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerKodlarKayitSadeKodlarTumSeviyelerModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerKodlarKayitSadeKodlarTumSeviyelerModelMesajlar';
import type { AaroModullerKodlarKayitSadeKodlarTumSeviyelerModel } from './aaroModullerKodlarKayitSadeKodlarTumSeviyelerModel';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerKodlarKayitSadeKodlarTumSeviyelerModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerKodlarKayitSadeKodlarTumSeviyelerModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerKodlarKayitSadeKodlarTumSeviyelerModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
