/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerParametrelerSirketSubeKayitSadeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerParametrelerSirketSubeKayitSadeListeModelMesajlar';
import type { AaroModullerParametrelerSirketSubeKayitSadeListeModel } from './aaroModullerParametrelerSirketSubeKayitSadeListeModel';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerParametrelerSirketSubeKayitSadeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerParametrelerSirketSubeKayitSadeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerParametrelerSirketSubeKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
