/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerAlisIadeFaturasiHareketleriListeModelMesajlar } from './aaroKayitSonucAaroModullerAlisIadeFaturasiHareketleriListeModelMesajlar.js';
import type { AaroModullerAlisIadeFaturasiHareketleriListeModel } from './aaroModullerAlisIadeFaturasiHareketleriListeModel.js';

export interface AaroKayitSonucAaroModullerAlisIadeFaturasiHareketleriListeModel {
  Model?: AaroModullerAlisIadeFaturasiHareketleriListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerAlisIadeFaturasiHareketleriListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
