/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerUrOperasyonMakineKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerUrOperasyonMakineKayitSadeListeModelMesajlar.js';
import type { AaroModullerUrOperasyonMakineKayitSadeListeModel } from './aaroModullerUrOperasyonMakineKayitSadeListeModel.js';

export interface AaroKayitSonucAaroModullerUrOperasyonMakineKayitSadeListeModel {
  Model?: AaroModullerUrOperasyonMakineKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerUrOperasyonMakineKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
