/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerMasrafMerkeziKayitSadeKayitModel } from './aaroModullerMasrafMerkeziKayitSadeKayitModel.js';

export type AaroModullerMasrafMerkeziKayitSadeKayitModelBody = AaroModullerMasrafMerkeziKayitSadeKayitModel;
