/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucAaroModullerHareketTurleriAltKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerHareketTurleriAltKayitSadeListeModelMesajlar.js';
import type { AaroModullerHareketTurleriAltKayitSadeListeModel } from './aaroModullerHareketTurleriAltKayitSadeListeModel.js';

export interface AaroKayitSonucAaroModullerHareketTurleriAltKayitSadeListeModel {
  Model?: AaroModullerHareketTurleriAltKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerHareketTurleriAltKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
