/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type AaroModullerDegisiklikLoglariKayitSadeKayitModelKayitTipi = typeof AaroModullerDegisiklikLoglariKayitSadeKayitModelKayitTipi[keyof typeof AaroModullerDegisiklikLoglariKayitSadeKayitModelKayitTipi];


export const AaroModullerDegisiklikLoglariKayitSadeKayitModelKayitTipi = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_6: 6,
  NUMBER_11: 11,
  NUMBER_12: 12,
  NUMBER_13: 13,
  NUMBER_14: 14,
  NUMBER_15: 15,
  NUMBER_16: 16,
  NUMBER_17: 17,
  NUMBER_18: 18,
  NUMBER_19: 19,
  NUMBER_20: 20,
  NUMBER_21: 21,
  NUMBER_22: 22,
  NUMBER_MINUS_2: -2,
  NUMBER_MINUS_1: -1,
} as const;
