/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerKodlarKayitSadeKayitModelTip2ID } from './aaroModullerKodlarKayitSadeKayitModelTip2ID.js';
import type { AaroModullerKodlarKayitSadeKayitModelTipID } from './aaroModullerKodlarKayitSadeKayitModelTipID.js';

export interface AaroModullerKodlarKayitSadeKayitModel {
  KodID?: number;
  Kod?: string;
  KodAdi?: string;
  Seviye?: number;
  SirketID?: number;
  SirketKodu?: string;
  SubeID?: number;
  SubeKodu?: string;
  TipID?: AaroModullerKodlarKayitSadeKayitModelTipID;
  TipKodu?: string;
  Tip2ID?: AaroModullerKodlarKayitSadeKayitModelTip2ID;
  Tip2Kodu?: string;
}
