/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerPerMesaiHareketDetayKayitSadeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerPerMesaiHareketDetayKayitSadeListeModelMesajlar.js';
import type { AaroModullerPerMesaiHareketDetayKayitSadeListeModel } from './aaroModullerPerMesaiHareketDetayKayitSadeListeModel.js';
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi.js';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerPerMesaiHareketDetayKayitSadeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerPerMesaiHareketDetayKayitSadeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerPerMesaiHareketDetayKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
