/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerPerPuantajKayitSadeListeModelOnayDurum } from './aaroModullerPerPuantajKayitSadeListeModelOnayDurum';
import type { AaroModullerPerPuantajKayitSadeListeModelTipID } from './aaroModullerPerPuantajKayitSadeListeModelTipID';

export interface AaroModullerPerPuantajKayitSadeListeModel {
  PersonelKodu?: string;
  PersonelAdiSoyadi?: string;
  PerSirketSicilAciklama?: string;
  OnayDurum?: AaroModullerPerPuantajKayitSadeListeModelOnayDurum;
  OlsTar?: string;
  DgsTar?: string;
  OlsID?: number;
  OlsKodu?: string;
  OlsAdi?: string;
  DgsID?: number;
  DgsKodu?: string;
  DgsAdi?: string;
  EsnekAramaKisiti?: string;
  PerPuantajID?: number;
  PersonelID?: number;
  PerSirketSicilID?: number;
  TipID?: AaroModullerPerPuantajKayitSadeListeModelTipID;
  Ay?: number;
  Yil?: number;
  BaslikID?: number;
  ToplamGun?: number;
  SSKGun?: number;
  MazeretIzni?: number;
  Rapor?: number;
  UcretsizIzin?: number;
  YillikIzin?: number;
  NormalGun?: number;
  HaftaTatili?: number;
  ResmiTatil?: number;
  EksikGun?: number;
  EksikGunNedenID?: number;
  EksikGunAciklama?: string;
  FazlaMesai1?: number;
  FazlaMesai2?: number;
  FazlaMesai3?: number;
  NormalSaat?: number;
  EksikSaat?: number;
  Durum?: boolean;
}
