/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type AciklamalarListeGetGetParams = {
'Kisit.esnekAramaKisiti'?: string;
'Kisit.aciklamaID'?: number;
'Kisit.a1'?: string;
'Kisit.a2'?: string;
'Kisit.a3'?: string;
'Kisit.a4'?: string;
'Kisit.a5'?: string;
'Kisit.a6'?: string;
'Kisit.a7'?: string;
'Kisit.a8'?: string;
'Kisit.a9'?: string;
'Kisit.a10'?: string;
'Kisit.a11'?: string;
/**
 * Listeleme işlemlerinde sıralama için kullanılacak kısıtı belirtir.
Örneğin, "Tarih", "Tarih:desc", "Tarih,Adi", "Tarih:desc,Adi" gibi bir değer alabilir.
 */
'SayfalandirmaBilgisi.siralamaKisiti'?: string;
/**
 * Geçerli sayfa numarasını (1'den başlar) alır veya ayarlar.
 */
'SayfalandirmaBilgisi.sayfa'?: number;
/**
 * Sayfa başına satır sayısını alır veya ayarlar. maxSayfaSatirSayisi değerini aşamaz.
 */
'SayfalandirmaBilgisi.sayfaSatirSayisi'?: number;
};
