/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type AlinanTeklifHareketleriListeGetGetKisitOnayDurum = typeof AlinanTeklifHareketleriListeGetGetKisitOnayDurum[keyof typeof AlinanTeklifHareketleriListeGetGetKisitOnayDurum];


export const AlinanTeklifHareketleriListeGetGetKisitOnayDurum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_MINUS_1: -1,
} as const;
