/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type AlisIrsaliyesiListeDetayliListeKisitEFaturaTurID = typeof AlisIrsaliyesiListeDetayliListeKisitEFaturaTurID[keyof typeof AlisIrsaliyesiListeDetayliListeKisitEFaturaTurID];


export const AlisIrsaliyesiListeDetayliListeKisitEFaturaTurID = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;
