/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type AlisFaturasiListeDetayliListeGetKisitEFaturaUygulamaYanitiDurumID = typeof AlisFaturasiListeDetayliListeGetKisitEFaturaUygulamaYanitiDurumID[keyof typeof AlisFaturasiListeDetayliListeGetKisitEFaturaUygulamaYanitiDurumID];


export const AlisFaturasiListeDetayliListeGetKisitEFaturaUygulamaYanitiDurumID = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;
