/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type AlisIadeFaturasiHareketleriGrupluListeGetParams = {
/**
 * Gruplama yapılacak alan adları (virgülle ayrılmış).
Örnek: "BelgeTuru,Durum" veya "Tarih_Yil,Tarih_Ay,SubeAdi"
Alan adları ilgili ListeModel sınıfındaki (TListe) property isimlerle eşleşmelidir.
Boş geçilemez - en az bir grup alanı zorunludur.
 */
Gruplar: string;
/**
 * Hesaplama yapılacak alanlar ve işlem tipleri (virgülle ayrılmış).
Format: "AlanAdi:IslemTipi,AlanAdi:IslemTipi"
Örnek: "Tutar:SUM,Miktar:AVG,KayıtID:COUNT"

Geçerli İşlem Tipleri:
- SUM: Toplam (sayısal alanlar için)
- AVG: Ortalama (sayısal alanlar için)
- MAX: En büyük değer
- MIN: En küçük değer
- COUNT: Kayıt sayısı

String alanlar için sadece MIN, MAX, COUNT desteklenir.
Boş geçilemez - en az bir değer alanı zorunludur.
 */
Degerler: string;
/**
 * Gruplama yapılmadan önce veri tabanında filtrelenecek ön koşulları temsil eder. ListeEsnek metodundaki string filtreleriyle / operatörle aynı yapıdadır.
 */
Kisit: string;
};
