/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { BankaSubeListeGetKisitOnayDurum } from './bankaSubeListeGetKisitOnayDurum';

export type BankaSubeListeGetParams = {
'Kisit.bankaAdi'?: string;
'Kisit.ilceAdi'?: string;
'Kisit.ilAdi'?: string;
'Kisit.ilID'?: number;
'Kisit.onayDurum'?: BankaSubeListeGetKisitOnayDurum;
'Kisit.olsTar'?: string;
'Kisit.dgsTar'?: string;
'Kisit.olsID'?: number;
'Kisit.olsKodu'?: string;
'Kisit.olsAdi'?: string;
'Kisit.dgsID'?: number;
'Kisit.dgsKodu'?: string;
'Kisit.dgsAdi'?: string;
'Kisit.esnekAramaKisiti'?: string;
'Kisit.bankaID'?: number;
'Kisit.bankaSubeID'?: number;
'Kisit.bankaSubeKodu'?: string;
'Kisit.bankaSubeAdi'?: string;
'Kisit.tel'?: string;
'Kisit.fax'?: string;
'Kisit.email'?: string;
'Kisit.adres'?: string;
'Kisit.ilceID'?: number;
'Kisit.durum'?: boolean;
/**
 * Listeleme işlemlerinde sıralama için kullanılacak kısıtı belirtir.
Örneğin, "Tarih", "Tarih:desc", "Tarih,Adi", "Tarih:desc,Adi" gibi bir değer alabilir.
 */
'SayfalandirmaBilgisi.siralamaKisiti'?: string;
/**
 * Geçerli sayfa numarasını (1'den başlar) alır veya ayarlar.
 */
'SayfalandirmaBilgisi.sayfa'?: number;
/**
 * Sayfa başına satır sayısını alır veya ayarlar. maxSayfaSatirSayisi değerini aşamaz.
 */
'SayfalandirmaBilgisi.sayfaSatirSayisi'?: number;
};
