/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { BayiSepetPostSayfaKayitTipi } from './bayiSepetPostSayfaKayitTipi.js';

export type BayiSepetPostParams = {
/**
 * İşlem yapılacak sepetin ID'si.
 */
DekontID: number;
/**
 * İşlem türü (Onayla veya Sil).
 */
SayfaKayitTipi: BayiSepetPostSayfaKayitTipi;
};
