/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type CariAdresReddetPostParams = {
/**
 * Reddedilecek kaydın ID'si.
 */
ID: number;
};
