/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { CariAdresListeGetKisitOnayDurum } from './cariAdresListeGetKisitOnayDurum';
import type { CariAdresListeGetKisitTipID } from './cariAdresListeGetKisitTipID';

export type CariAdresListeGetParams = {
'Kisit.cariAdi'?: string;
'Kisit.ilceAdi'?: string;
'Kisit.ilAdi'?: string;
'Kisit.ulkeAdi'?: string;
'Kisit.onayDurum'?: CariAdresListeGetKisitOnayDurum;
'Kisit.olsTar'?: string;
'Kisit.dgsTar'?: string;
'Kisit.olsID'?: number;
'Kisit.olsKodu'?: string;
'Kisit.olsAdi'?: string;
'Kisit.dgsID'?: number;
'Kisit.dgsKodu'?: string;
'Kisit.dgsAdi'?: string;
'Kisit.esnekAramaKisiti'?: string;
'Kisit.tipID'?: CariAdresListeGetKisitTipID;
'Kisit.vergiNo'?: string;
'Kisit.vergiDairesiAdi'?: string;
'Kisit.adresID'?: number;
'Kisit.cariID'?: number;
'Kisit.cariKodu'?: string;
'Kisit.adresAdi'?: string;
'Kisit.sokakAdi'?: string;
'Kisit.binaAdi'?: string;
'Kisit.binaNo'?: string;
'Kisit.kapiNo'?: string;
'Kisit.postaKodu'?: string;
'Kisit.durum'?: boolean;
'Kisit.ilceID'?: number;
'Kisit.tel'?: string;
'Kisit.tel2'?: string;
'Kisit.tel3'?: string;
'Kisit.fax'?: string;
'Kisit.email'?: string;
'Kisit.web'?: string;
'Kisit.enlem'?: number;
'Kisit.boylam'?: number;
'Kisit.oncelik'?: boolean;
/**
 * Listeleme işlemlerinde sıralama için kullanılacak kısıtı belirtir.
Örneğin, "Tarih", "Tarih:desc", "Tarih,Adi", "Tarih:desc,Adi" gibi bir değer alabilir.
 */
'SayfalandirmaBilgisi.siralamaKisiti'?: string;
/**
 * Geçerli sayfa numarasını (1'den başlar) alır veya ayarlar.
 */
'SayfalandirmaBilgisi.sayfa'?: number;
/**
 * Sayfa başına satır sayısını alır veya ayarlar. maxSayfaSatirSayisi değerini aşamaz.
 */
'SayfalandirmaBilgisi.sayfaSatirSayisi'?: number;
};
