/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type DekontZorunluDemirbasCariParams = {
/**
 * Kısıt ve zorunluluk kuralları kontrol edilecek stok/hizmet kartının sistem ID'si.
 */
StokID: number;
};
