/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { DekontKalemPostKayitTipi } from './dekontKalemPostKayitTipi.js';

export type DekontKalemPostParams = {
KayitTipi?: DekontKalemPostKayitTipi;
};
