/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { DekontBaslikKaydetPostKayitTipi } from './dekontBaslikKaydetPostKayitTipi.js';

export type DekontBaslikKaydetPostParams = {
/**
 * İşlemin türü (Ekleme mi, Düzeltme mi, Silme mi? - KayitTipi enum). Varsayılan: Duzelt.
 */
KayitTipi?: DekontBaslikKaydetPostKayitTipi;
};
