/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type DekontKalemVergiDetaylariGetirParams = {
/**
 * Vergi oranları sorgulanacak olan stok kartının sistem ID'si.
 */
StokID: number;
/**
 * Verginin hesaplanacağı, indirimler sonrası yerel para birimi (TL) cinsinden net matrah tutarı.
 */
Tutar: number;
/**
 * Verginin hesaplanacağı dövizli matrah tutarı.
 */
TutarDvz: number;
/**
 * İşlemde kullanılan para birimi ID'si.
 */
DovizID: number;
/**
 * İşlemin yönü (Borç/Alacak). 'A' (Alacak) ise Satış/Çıkış vergilerini, 'B' (Borç) ise Alış/Giriş vergilerini tetikler.
 */
BA: string;
};
