/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { EtiketlerListeGetGetKisitOnayDurum } from './etiketlerListeGetGetKisitOnayDurum.js';
import type { EtiketlerListeGetGetKisitTip2ID } from './etiketlerListeGetGetKisitTip2ID.js';
import type { EtiketlerListeGetGetKisitTipID } from './etiketlerListeGetGetKisitTipID.js';

export type EtiketlerListeGetGetParams = {
'Kisit.tip2Adi'?: string;
'Kisit.tip2Kodu'?: string;
'Kisit.tabloAdi'?: string;
'Kisit.subeKodu'?: string;
'Kisit.subeAdi'?: string;
'Kisit.sirketKodu'?: string;
'Kisit.sirketAdi'?: string;
'Kisit.olsTar'?: string;
'Kisit.dgsTar'?: string;
'Kisit.onayDurum'?: EtiketlerListeGetGetKisitOnayDurum;
'Kisit.olsID'?: number;
'Kisit.olsKodu'?: string;
'Kisit.olsAdi'?: string;
'Kisit.dgsID'?: number;
'Kisit.dgsKodu'?: string;
'Kisit.dgsAdi'?: string;
'Kisit.esnekAramaKisiti'?: string;
'Kisit.sirketID'?: number;
'Kisit.subeID'?: number;
'Kisit.tipID'?: EtiketlerListeGetGetKisitTipID;
'Kisit.tip2ID'?: EtiketlerListeGetGetKisitTip2ID;
'Kisit.etiketID'?: number;
'Kisit.etiketAdi'?: string;
'Kisit.aciklama'?: string;
'Kisit.renk'?: string;
'Kisit.seviye'?: number;
/**
 * Listeleme işlemlerinde sıralama için kullanılacak kısıtı belirtir.
Örneğin, "Tarih", "Tarih:desc", "Tarih,Adi", "Tarih:desc,Adi" gibi bir değer alabilir.
 */
'SayfalandirmaBilgisi.siralamaKisiti'?: string;
/**
 * Geçerli sayfa numarasını (1'den başlar) alır veya ayarlar.
 */
'SayfalandirmaBilgisi.sayfa'?: number;
/**
 * Sayfa başına satır sayısını alır veya ayarlar. maxSayfaSatirSayisi değerini aşamaz.
 */
'SayfalandirmaBilgisi.sayfaSatirSayisi'?: number;
};
