/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type FaturaListeListeGetGetKisitEFaturaUygulamaYanitiDurumID = typeof FaturaListeListeGetGetKisitEFaturaUygulamaYanitiDurumID[keyof typeof FaturaListeListeGetGetKisitEFaturaUygulamaYanitiDurumID];


export const FaturaListeListeGetGetKisitEFaturaUygulamaYanitiDurumID = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;
