/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type GelirGiderListeGetGetKisitTakipYontemi = typeof GelirGiderListeGetGetKisitTakipYontemi[keyof typeof GelirGiderListeGetGetKisitTakipYontemi];


export const GelirGiderListeGetGetKisitTakipYontemi = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
