/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type GorevlerListeGetKisitTamamlanmaTipi = typeof GorevlerListeGetKisitTamamlanmaTipi[keyof typeof GorevlerListeGetKisitTamamlanmaTipi];


export const GorevlerListeGetKisitTamamlanmaTipi = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
