/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type GorevlerListeGetGetKisitTekrarSekli = typeof GorevlerListeGetGetKisitTekrarSekli[keyof typeof GorevlerListeGetGetKisitTekrarSekli];


export const GorevlerListeGetGetKisitTekrarSekli = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
} as const;
