/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type KaliteKontrolleriListeGetGetKisitKaliteKontrolDurum = typeof KaliteKontrolleriListeGetGetKisitKaliteKontrolDurum[keyof typeof KaliteKontrolleriListeGetGetKisitKaliteKontrolDurum];


export const KaliteKontrolleriListeGetGetKisitKaliteKontrolDurum = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;
