/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { KullanicilarListeGetKisitOnayDurum } from './kullanicilarListeGetKisitOnayDurum';

export type KullanicilarListeGetParams = {
'Kisit.grupAdi'?: string;
'Kisit.grupKodu'?: string;
'Kisit.personelAdi'?: string;
'Kisit.personelKodu'?: string;
'Kisit.onayDurum'?: KullanicilarListeGetKisitOnayDurum;
'Kisit.olsTar'?: string;
'Kisit.dgsTar'?: string;
'Kisit.olsID'?: number;
'Kisit.olsKodu'?: string;
'Kisit.olsAdi'?: string;
'Kisit.dgsID'?: number;
'Kisit.dgsKodu'?: string;
'Kisit.dgsAdi'?: string;
'Kisit.etiket1Adi'?: string;
'Kisit.etiket2Adi'?: string;
'Kisit.etiket3Adi'?: string;
'Kisit.etiket4Adi'?: string;
'Kisit.etiket5Adi'?: string;
'Kisit.depoAdi'?: string;
'Kisit.depoKodu'?: string;
'Kisit.makineAdi'?: string;
'Kisit.makineKodu'?: string;
'Kisit.bayiCariAdi'?: string;
'Kisit.bayiCariKodu'?: string;
'Kisit.esnekAramaKisiti'?: string;
'Kisit.kulID'?: number;
'Kisit.kulKodu'?: string;
'Kisit.kulAdiSoyadi'?: string;
'Kisit.grupID'?: number;
'Kisit.personelID'?: number;
'Kisit.ePosta'?: string;
'Kisit.telefon'?: string;
'Kisit.durum'?: boolean;
'Kisit.etiket1ID'?: number;
'Kisit.etiket2ID'?: number;
'Kisit.etiket3ID'?: number;
'Kisit.etiket4ID'?: number;
'Kisit.etiket5ID'?: number;
'Kisit.gecmisTarihliCariKayitGunSayisi'?: number;
'Kisit.gelecekTarihliCariKayitGunSayisi'?: number;
'Kisit.gecmisTarihliMuhasebeKayitGunSayisi'?: number;
'Kisit.gelecekTarihliMuhasebeKayitGunSayisi'?: number;
'Kisit.siparisOlusturabilir'?: boolean;
'Kisit.bakiyeGorebilir'?: boolean;
'Kisit.hareketGorebilir'?: boolean;
'Kisit.anaSayfaIntroGorebilir'?: boolean;
'Kisit.cariKayitIntroGorebilir'?: boolean;
'Kisit.faturaKayitIntroGorebilir'?: boolean;
'Kisit.stokKayitIntroGorebilir'?: boolean;
'Kisit.gorulenSonGuncellemeTarihi'?: string;
'Kisit.oturumBaslangicSaatiPazartesi'?: string;
'Kisit.oturumBitisSaatiPazartesi'?: string;
'Kisit.oturumBaslangicSaatiSali'?: string;
'Kisit.oturumBitisSaatiSali'?: string;
'Kisit.oturumBaslangicSaatiCarsamba'?: string;
'Kisit.oturumBitisSaatiCarsamba'?: string;
'Kisit.oturumBaslangicSaatiPersembe'?: string;
'Kisit.oturumBitisSaatiPersembe'?: string;
'Kisit.oturumBaslangicSaatiCuma'?: string;
'Kisit.oturumBitisSaatiCuma'?: string;
'Kisit.oturumBaslangicSaatiCumartesi'?: string;
'Kisit.oturumBitisSaatiCumartesi'?: string;
'Kisit.oturumBaslangicSaatiPazar'?: string;
'Kisit.oturumBitisSaatiPazar'?: string;
'Kisit.depoID'?: number;
'Kisit.urMakineID'?: number;
'Kisit.bayiCariID'?: number;
/**
 * Listeleme işlemlerinde sıralama için kullanılacak kısıtı belirtir.
Örneğin, "Tarih", "Tarih:desc", "Tarih,Adi", "Tarih:desc,Adi" gibi bir değer alabilir.
 */
'SayfalandirmaBilgisi.siralamaKisiti'?: string;
/**
 * Geçerli sayfa numarasını (1'den başlar) alır veya ayarlar.
 */
'SayfalandirmaBilgisi.sayfa'?: number;
/**
 * Sayfa başına satır sayısını alır veya ayarlar. maxSayfaSatirSayisi değerini aşamaz.
 */
'SayfalandirmaBilgisi.sayfaSatirSayisi'?: number;
};
