/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { LinqFilteringFilterCriteria } from './linqFilteringFilterCriteria.js';
import type { LinqFilteringSortingInfo } from './linqFilteringSortingInfo.js';

export interface LinqFilteringAdvancedFilterRequest {
  Filters?: LinqFilteringFilterCriteria[];
  Sorting?: LinqFilteringSortingInfo[];
  Page?: number;
  PageSize?: number;
}
