/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { MuhasebeListeGetGetKisitOnayDurum } from './muhasebeListeGetGetKisitOnayDurum.js';

export type MuhasebeListeGetGetParams = {
'Kisit.anaHesapKodu'?: string;
'Kisit.subeKodu'?: string;
'Kisit.subeAdi'?: string;
'Kisit.sirketKodu'?: string;
'Kisit.sirketAdi'?: string;
'Kisit.tipAdi'?: string;
'Kisit.tipKodu'?: string;
'Kisit.onayDurum'?: MuhasebeListeGetGetKisitOnayDurum;
'Kisit.olsTar'?: string;
'Kisit.dgsTar'?: string;
'Kisit.olsID'?: number;
'Kisit.olsKodu'?: string;
'Kisit.olsAdi'?: string;
'Kisit.dgsID'?: number;
'Kisit.dgsKodu'?: string;
'Kisit.dgsAdi'?: string;
'Kisit.kod1Kodu'?: string;
'Kisit.kod2Kodu'?: string;
'Kisit.kod3Kodu'?: string;
'Kisit.kod4Kodu'?: string;
'Kisit.kod5Kodu'?: string;
'Kisit.kod6Kodu'?: string;
'Kisit.kod1Adi'?: string;
'Kisit.kod2Adi'?: string;
'Kisit.kod3Adi'?: string;
'Kisit.kod4Adi'?: string;
'Kisit.kod5Adi'?: string;
'Kisit.kod6Adi'?: string;
'Kisit.etiket1Adi'?: string;
'Kisit.etiket2Adi'?: string;
'Kisit.etiket3Adi'?: string;
'Kisit.etiket4Adi'?: string;
'Kisit.etiket5Adi'?: string;
'Kisit.sablonKodu'?: string;
'Kisit.sablonAdi'?: string;
'Kisit.esnekAramaKisiti'?: string;
'Kisit.muhasebeID'?: number;
'Kisit.hesapKodu'?: string;
'Kisit.hesapAdi'?: string;
'Kisit.hesapAdiY'?: string;
'Kisit.bA'?: string;
'Kisit.aGM'?: string;
'Kisit.kartPuan'?: number;
'Kisit.durum'?: boolean;
'Kisit.subeID'?: number;
'Kisit.sirketID'?: number;
'Kisit.kod1ID'?: number;
'Kisit.kod2ID'?: number;
'Kisit.kod3ID'?: number;
'Kisit.kod4ID'?: number;
'Kisit.kod5ID'?: number;
'Kisit.kod6ID'?: number;
'Kisit.etiket1ID'?: number;
'Kisit.etiket2ID'?: number;
'Kisit.etiket3ID'?: number;
'Kisit.etiket4ID'?: number;
'Kisit.etiket5ID'?: number;
'Kisit.sablonID'?: number;
/**
 * Listeleme işlemlerinde sıralama için kullanılacak kısıtı belirtir.
Örneğin, "Tarih", "Tarih:desc", "Tarih,Adi", "Tarih:desc,Adi" gibi bir değer alabilir.
 */
'SayfalandirmaBilgisi.siralamaKisiti'?: string;
/**
 * Geçerli sayfa numarasını (1'den başlar) alır veya ayarlar.
 */
'SayfalandirmaBilgisi.sayfa'?: number;
/**
 * Sayfa başına satır sayısını alır veya ayarlar. maxSayfaSatirSayisi değerini aşamaz.
 */
'SayfalandirmaBilgisi.sayfaSatirSayisi'?: number;
};
