/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { OlcuBirimleriListeGetKisitTipID } from './olcuBirimleriListeGetKisitTipID';

export type OlcuBirimleriListeGetParams = {
'Kisit.olcuBirimleriUBLKodu'?: string;
'Kisit.olcuBirimleriUBLAdi'?: string;
'Kisit.subeKodu'?: string;
'Kisit.subeAdi'?: string;
'Kisit.sirketKodu'?: string;
'Kisit.sirketAdi'?: string;
'Kisit.tipKodu'?: string;
'Kisit.tipAdi'?: string;
'Kisit.esnekAramaKisiti'?: string;
'Kisit.birimID'?: number;
'Kisit.birimKodu'?: string;
'Kisit.birimAdi'?: string;
'Kisit.olcuBirimleriUBLID'?: number;
'Kisit.birimOran'?: number;
'Kisit.tipID'?: OlcuBirimleriListeGetKisitTipID;
'Kisit.subeID'?: number;
'Kisit.sirketID'?: number;
/**
 * Listeleme işlemlerinde sıralama için kullanılacak kısıtı belirtir.
Örneğin, "Tarih", "Tarih:desc", "Tarih,Adi", "Tarih:desc,Adi" gibi bir değer alabilir.
 */
'SayfalandirmaBilgisi.siralamaKisiti'?: string;
/**
 * Geçerli sayfa numarasını (1'den başlar) alır veya ayarlar.
 */
'SayfalandirmaBilgisi.sayfa'?: number;
/**
 * Sayfa başına satır sayısını alır veya ayarlar. maxSayfaSatirSayisi değerini aşamaz.
 */
'SayfalandirmaBilgisi.sayfaSatirSayisi'?: number;
};
