/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { PerGirisCikisListeGetKisitOnayDurum } from './perGirisCikisListeGetKisitOnayDurum';

export type PerGirisCikisListeGetParams = {
'Kisit.onayDurum'?: PerGirisCikisListeGetKisitOnayDurum;
'Kisit.olsTar'?: string;
'Kisit.dgsTar'?: string;
'Kisit.olsID'?: number;
'Kisit.olsKodu'?: string;
'Kisit.olsAdi'?: string;
'Kisit.dgsID'?: number;
'Kisit.dgsKodu'?: string;
'Kisit.dgsAdi'?: string;
'Kisit.personelAdiSoyadi'?: string;
'Kisit.sicilAciklama'?: string;
'Kisit.cikisNedenSSKAciklama'?: string;
'Kisit.cikisNedenSSKKodu'?: number;
'Kisit.cikisNedenKodu'?: number;
'Kisit.personelKodu'?: string;
'Kisit.strID'?: number;
'Kisit.perSirketSicilID'?: number;
'Kisit.personelID'?: number;
'Kisit.girisTarihi'?: string;
'Kisit.cikisTarihi'?: string;
'Kisit.cikisNedenSSKID'?: number;
'Kisit.cikisNedenID'?: number;
'Kisit.aciklama'?: string;
'Kisit.ihbar'?: boolean;
'Kisit.kidem'?: boolean;
'Kisit.izinParasi'?: boolean;
'Kisit.kidemBasTarihi'?: string;
'Kisit.ozlukBasTarihi'?: string;
/**
 * Listeleme işlemlerinde sıralama için kullanılacak kısıtı belirtir.
Örneğin, "Tarih", "Tarih:desc", "Tarih,Adi", "Tarih:desc,Adi" gibi bir değer alabilir.
 */
'SayfalandirmaBilgisi.siralamaKisiti'?: string;
/**
 * Geçerli sayfa numarasını (1'den başlar) alır veya ayarlar.
 */
'SayfalandirmaBilgisi.sayfa'?: number;
/**
 * Sayfa başına satır sayısını alır veya ayarlar. maxSayfaSatirSayisi değerini aşamaz.
 */
'SayfalandirmaBilgisi.sayfaSatirSayisi'?: number;
};
