/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { PersonelListeGetKisitOnayDurum } from './personelListeGetKisitOnayDurum';

export type PersonelListeGetParams = {
'Kisit.cariKodu'?: string;
'Kisit.sgkTanimKodu'?: string;
'Kisit.sgkTanimAdi'?: string;
'Kisit.amirGrupKodu'?: string;
'Kisit.amirGrupAdi'?: string;
'Kisit.maasGrupKodu'?: string;
'Kisit.maasGrupAdi'?: string;
'Kisit.takvimKodu'?: string;
'Kisit.uyrukIlceAdi'?: string;
'Kisit.dogumIlceAdi'?: string;
'Kisit.nufusIlceAdi'?: string;
'Kisit.onayDurum'?: PersonelListeGetKisitOnayDurum;
'Kisit.olsTar'?: string;
'Kisit.dgsTar'?: string;
'Kisit.olsID'?: number;
'Kisit.olsKodu'?: string;
'Kisit.olsAdi'?: string;
'Kisit.dgsID'?: number;
'Kisit.dgsKodu'?: string;
'Kisit.dgsAdi'?: string;
'Kisit.kod1Kodu'?: string;
'Kisit.kod2Kodu'?: string;
'Kisit.kod3Kodu'?: string;
'Kisit.kod4Kodu'?: string;
'Kisit.kod5Kodu'?: string;
'Kisit.kod6Kodu'?: string;
'Kisit.kod1Adi'?: string;
'Kisit.kod2Adi'?: string;
'Kisit.kod3Adi'?: string;
'Kisit.kod4Adi'?: string;
'Kisit.kod5Adi'?: string;
'Kisit.kod6Adi'?: string;
'Kisit.etiket1Adi'?: string;
'Kisit.etiket2Adi'?: string;
'Kisit.etiket3Adi'?: string;
'Kisit.etiket4Adi'?: string;
'Kisit.etiket5Adi'?: string;
'Kisit.sablonKodu'?: string;
'Kisit.sablonAdi'?: string;
'Kisit.resimAdresi'?: string;
'Kisit.esnekAramaKisiti'?: string;
'Kisit.girisTarihiSon'?: string;
'Kisit.cikisTarihiSon'?: string;
'Kisit.personelID'?: number;
'Kisit.personelKodu'?: string;
'Kisit.personelAdiSoyadi'?: string;
'Kisit.cariID'?: number;
'Kisit.sgkTanimID'?: number;
'Kisit.amirGrupID'?: number;
'Kisit.maasGrupID'?: number;
'Kisit.takvimID'?: number;
'Kisit.tC'?: string;
'Kisit.durum'?: boolean;
'Kisit.hitap'?: string;
'Kisit.adi'?: string;
'Kisit.soyadi'?: string;
'Kisit.ilkSoyadi'?: string;
'Kisit.ozlukBasTar'?: string;
'Kisit.meslegi'?: string;
'Kisit.sSKNo'?: string;
'Kisit.sSKDurum'?: string;
'Kisit.emekliNo'?: string;
'Kisit.yaka'?: string;
'Kisit.cinsiyet'?: string;
'Kisit.medenihal'?: boolean;
'Kisit.esAdi'?: string;
'Kisit.esCalisiyorMu'?: boolean;
'Kisit.aGICocukAdedi'?: number;
'Kisit.cocukAdedi'?: number;
'Kisit.askrlikTip'?: string;
'Kisit.terhisTarihi'?: string;
'Kisit.muafNeden'?: string;
'Kisit.sakatDerece'?: number;
'Kisit.sakatKatagori'?: number;
'Kisit.sakatOran'?: number;
'Kisit.sakatAciklama'?: string;
'Kisit.eskiHukumlu'?: boolean;
'Kisit.hukumAciklama'?: string;
'Kisit.hukumKatagori'?: number;
'Kisit.terorleMucadele'?: boolean;
'Kisit.gocmen'?: boolean;
'Kisit.bitirdigiTahsili'?: string;
'Kisit.sigara'?: boolean;
'Kisit.seyahatEdebilir'?: boolean;
'Kisit.mesaiKalabilir'?: boolean;
'Kisit.resim'?: number;
'Kisit.uyrugu'?: string;
'Kisit.uyrukIlceID'?: number;
'Kisit.babaAdi'?: string;
'Kisit.anaAdi'?: string;
'Kisit.dogumTarihi'?: string;
'Kisit.dogumIlceID'?: number;
'Kisit.dini'?: string;
'Kisit.kanGrubu'?: string;
'Kisit.nufusIlceID'?: number;
'Kisit.nufusMahalle'?: string;
'Kisit.nufusKoyu'?: string;
'Kisit.ciltNo'?: string;
'Kisit.kutukNo'?: string;
'Kisit.sayfaNo'?: string;
'Kisit.verilisTarihi'?: string;
'Kisit.cuzdanSeriNo'?: string;
'Kisit.cuzdanKayitNo'?: string;
'Kisit.verildigiYer'?: string;
'Kisit.verilisNo'?: string;
'Kisit.pasaportNo'?: string;
'Kisit.pasaportYer'?: string;
'Kisit.pasaportIl'?: string;
'Kisit.pasaportTarih'?: string;
'Kisit.pasaportExp'?: string;
'Kisit.kod1ID'?: number;
'Kisit.kod2ID'?: number;
'Kisit.kod3ID'?: number;
'Kisit.kod4ID'?: number;
'Kisit.kod5ID'?: number;
'Kisit.kod6ID'?: number;
'Kisit.etiket1ID'?: number;
'Kisit.etiket2ID'?: number;
'Kisit.etiket3ID'?: number;
'Kisit.etiket4ID'?: number;
'Kisit.etiket5ID'?: number;
'Kisit.seviye'?: number;
'Kisit.ibanNo'?: string;
'Kisit.bireyselEmeklilik'?: boolean;
'Kisit.sablonID'?: number;
'Kisit.adres'?: string;
'Kisit.tel'?: string;
'Kisit.tel2'?: string;
'Kisit.tel3'?: string;
'Kisit.email'?: string;
'Kisit.cihazPersonelID'?: number;
/**
 * Listeleme işlemlerinde sıralama için kullanılacak kısıtı belirtir.
Örneğin, "Tarih", "Tarih:desc", "Tarih,Adi", "Tarih:desc,Adi" gibi bir değer alabilir.
 */
'SayfalandirmaBilgisi.siralamaKisiti'?: string;
/**
 * Geçerli sayfa numarasını (1'den başlar) alır veya ayarlar.
 */
'SayfalandirmaBilgisi.sayfa'?: number;
/**
 * Sayfa başına satır sayısını alır veya ayarlar. maxSayfaSatirSayisi değerini aşamaz.
 */
'SayfalandirmaBilgisi.sayfaSatirSayisi'?: number;
};
