/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type SatisFaturasiListeListeGetGetKisitEFaturaTurID = typeof SatisFaturasiListeListeGetGetKisitEFaturaTurID[keyof typeof SatisFaturasiListeListeGetGetKisitEFaturaTurID];


export const SatisFaturasiListeListeGetGetKisitEFaturaTurID = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;
