/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { SirketlerListeGetGetKisitEFaturaEntegrator } from './sirketlerListeGetGetKisitEFaturaEntegrator.js';
import type { SirketlerListeGetGetKisitEPostaSSL } from './sirketlerListeGetGetKisitEPostaSSL.js';

export type SirketlerListeGetGetParams = {
'Kisit.vergiDairesiKodu'?: string;
'Kisit.vergiDairesiAdi'?: string;
'Kisit.cariKodu'?: string;
'Kisit.cariAdi'?: string;
'Kisit.ilceKodu'?: string;
'Kisit.ilceAdi'?: string;
'Kisit.esnekAramaKisiti'?: string;
'Kisit.sirketID'?: number;
'Kisit.sirketKodu'?: string;
'Kisit.sirketAdi'?: string;
'Kisit.sirketUzunAdi'?: string;
'Kisit.vergiDairesiID'?: number;
'Kisit.vergiNo'?: string;
'Kisit.sicilNo'?: string;
'Kisit.mersisNo'?: string;
'Kisit.cariID'?: number;
'Kisit.sokakAdi'?: string;
'Kisit.binaAdi'?: string;
'Kisit.binaNo'?: string;
'Kisit.kapiNo'?: string;
'Kisit.postaKodu'?: string;
'Kisit.ilceID'?: number;
'Kisit.tel'?: string;
'Kisit.tel2'?: string;
'Kisit.tel3'?: string;
'Kisit.fax'?: string;
'Kisit.email'?: string;
'Kisit.web'?: string;
'Kisit.eFaturaAktif'?: boolean;
'Kisit.eArsivAktif'?: boolean;
'Kisit.eIrsaliyeAktif'?: boolean;
'Kisit.eFaturaEntegrator'?: SirketlerListeGetGetKisitEFaturaEntegrator;
'Kisit.eFaturaTCVKNo'?: string;
'Kisit.eFaturaSifre'?: string;
'Kisit.eFaturaKullaniciAdi'?: string;
'Kisit.eFaturaGbEtiketi'?: string;
'Kisit.eFaturaPkEtiketi'?: string;
'Kisit.eIrsaliyeGbEtiketi'?: string;
'Kisit.eIrsaliyePkEtiketi'?: string;
'Kisit.eFaturaTestMi'?: boolean;
'Kisit.eFaturaSonSorguTarihi'?: string;
'Kisit.eIrsaliyeSonSorguTarihi'?: string;
'Kisit.ePosta'?: string;
'Kisit.ePostaSifre'?: string;
'Kisit.ePostaHost'?: string;
'Kisit.ePostaPort'?: string;
'Kisit.ePostaSSL'?: SirketlerListeGetGetKisitEPostaSSL;
'Kisit.otomatikKirilimliHesapPlani'?: boolean;
/**
 * Listeleme işlemlerinde sıralama için kullanılacak kısıtı belirtir.
Örneğin, "Tarih", "Tarih:desc", "Tarih,Adi", "Tarih:desc,Adi" gibi bir değer alabilir.
 */
'SayfalandirmaBilgisi.siralamaKisiti'?: string;
/**
 * Geçerli sayfa numarasını (1'den başlar) alır veya ayarlar.
 */
'SayfalandirmaBilgisi.sayfa'?: number;
/**
 * Sayfa başına satır sayısını alır veya ayarlar. maxSayfaSatirSayisi değerini aşamaz.
 */
'SayfalandirmaBilgisi.sayfaSatirSayisi'?: number;
};
