/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { StokNotlarGetKisitTabloID } from './stokNotlarGetKisitTabloID.js';
import type { StokNotlarGetKisitTipID } from './stokNotlarGetKisitTipID.js';

export type StokNotlarGetParams = {
'Kisit.subeKodu'?: string;
'Kisit.subeAdi'?: string;
'Kisit.sirketKodu'?: string;
'Kisit.sirketAdi'?: string;
'Kisit.tipAdi'?: string;
'Kisit.tipKodu'?: string;
'Kisit.tabloAdi'?: string;
'Kisit.olsKodu'?: string;
'Kisit.olsAdi'?: string;
'Kisit.esnekAramaKisiti'?: string;
'Kisit.notID'?: number;
'Kisit.tabloSatirID'?: number;
'Kisit.notu'?: string;
'Kisit.subeID'?: number;
'Kisit.sirketID'?: number;
'Kisit.tipID'?: StokNotlarGetKisitTipID;
'Kisit.tabloID'?: StokNotlarGetKisitTabloID;
'Kisit.olsTar'?: string;
'Kisit.olsID'?: number;
/**
 * Listeleme işlemlerinde sıralama için kullanılacak kısıtı belirtir.
Örneğin, "Tarih", "Tarih:desc", "Tarih,Adi", "Tarih:desc,Adi" gibi bir değer alabilir.
 */
'SayfalandirmaBilgisi.siralamaKisiti'?: string;
/**
 * Geçerli sayfa numarasını (1'den başlar) alır veya ayarlar.
 */
'SayfalandirmaBilgisi.sayfa'?: number;
/**
 * Sayfa başına satır sayısını alır veya ayarlar. maxSayfaSatirSayisi değerini aşamaz.
 */
'SayfalandirmaBilgisi.sayfaSatirSayisi'?: number;
};
