/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type StokListeGetGetKisitFaturaKartTuru = typeof StokListeGetGetKisitFaturaKartTuru[keyof typeof StokListeGetGetKisitFaturaKartTuru];


export const StokListeGetGetKisitFaturaKartTuru = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
