/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type UrIsEmriDetayliListeGetKisitUretimDurumu = typeof UrIsEmriDetayliListeGetKisitUretimDurumu[keyof typeof UrIsEmriDetayliListeGetKisitUretimDurumu];


export const UrIsEmriDetayliListeGetKisitUretimDurumu = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
} as const;
