/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { UrOperasyonMakineListeGetGetKisitOnayDurum } from './urOperasyonMakineListeGetGetKisitOnayDurum.js';

export type UrOperasyonMakineListeGetGetParams = {
'Kisit.olsTar'?: string;
'Kisit.dgsTar'?: string;
'Kisit.olsID'?: number;
'Kisit.olsKodu'?: string;
'Kisit.olsAdi'?: string;
'Kisit.dgsID'?: number;
'Kisit.dgsKodu'?: string;
'Kisit.dgsAdi'?: string;
'Kisit.onayDurum'?: UrOperasyonMakineListeGetGetKisitOnayDurum;
'Kisit.operasyonAdi'?: string;
'Kisit.makineAdi'?: string;
'Kisit.operasyonMakineID'?: number;
'Kisit.operasyonID'?: number;
'Kisit.makineID'?: number;
'Kisit.oncelik'?: number;
/**
 * Listeleme işlemlerinde sıralama için kullanılacak kısıtı belirtir.
Örneğin, "Tarih", "Tarih:desc", "Tarih,Adi", "Tarih:desc,Adi" gibi bir değer alabilir.
 */
'SayfalandirmaBilgisi.siralamaKisiti'?: string;
/**
 * Geçerli sayfa numarasını (1'den başlar) alır veya ayarlar.
 */
'SayfalandirmaBilgisi.sayfa'?: number;
/**
 * Sayfa başına satır sayısını alır veya ayarlar. maxSayfaSatirSayisi değerini aşamaz.
 */
'SayfalandirmaBilgisi.sayfaSatirSayisi'?: number;
};
