/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type VerilenSiparisListeListeGetGetKisitOnayDurum = typeof VerilenSiparisListeListeGetGetKisitOnayDurum[keyof typeof VerilenSiparisListeListeGetGetKisitOnayDurum];


export const VerilenSiparisListeListeGetGetKisitOnayDurum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_MINUS_1: -1,
} as const;
