/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { YevmiyeFisHareketleriDetayliListeKisitCariHareketTabloID } from './yevmiyeFisHareketleriDetayliListeKisitCariHareketTabloID';
import type { YevmiyeFisHareketleriDetayliListeKisitCariKartTabloID } from './yevmiyeFisHareketleriDetayliListeKisitCariKartTabloID';
import type { YevmiyeFisHareketleriDetayliListeKisitDekontTipID } from './yevmiyeFisHareketleriDetayliListeKisitDekontTipID';
import type { YevmiyeFisHareketleriDetayliListeKisitOnayDurum } from './yevmiyeFisHareketleriDetayliListeKisitOnayDurum';
import type { YevmiyeFisHareketleriDetayliListeKisitTipID } from './yevmiyeFisHareketleriDetayliListeKisitTipID';

export type YevmiyeFisHareketleriDetayliListeParams = {
'Kisit.subeKodu'?: string;
'Kisit.subeAdi'?: string;
'Kisit.sirketKodu'?: string;
'Kisit.sirketAdi'?: string;
'Kisit.tipAdi'?: string;
'Kisit.tipKodu'?: string;
'Kisit.onayDurum'?: YevmiyeFisHareketleriDetayliListeKisitOnayDurum;
'Kisit.olsTar'?: string;
'Kisit.dgsTar'?: string;
'Kisit.olsID'?: number;
'Kisit.olsKodu'?: string;
'Kisit.olsAdi'?: string;
'Kisit.dgsID'?: number;
'Kisit.dgsKodu'?: string;
'Kisit.dgsAdi'?: string;
'Kisit.hesapKodu'?: string;
'Kisit.hesapAdi'?: string;
'Kisit.aGM'?: string;
'Kisit.hesabiHataliOlanYevmiyeFisHareketi'?: boolean;
'Kisit.borc'?: number;
'Kisit.alacak'?: number;
'Kisit.bakiye'?: number;
'Kisit.bakiyeMiktar'?: number;
'Kisit.fisNo'?: string;
'Kisit.belgeNo'?: string;
'Kisit.dovizKodu'?: string;
'Kisit.entegrasyonDurumu'?: number;
'Kisit.tamamlanmaDurumu'?: boolean;
'Kisit.dekontTipID'?: YevmiyeFisHareketleriDetayliListeKisitDekontTipID;
'Kisit.entegrasyonKodu'?: string;
'Kisit.entegrasyonAdi'?: string;
'Kisit.entegrasyonTipKodu'?: string;
'Kisit.esnekAramaKisiti'?: string;
'Kisit.dekontTarih'?: string;
'Kisit.eDefterAdi'?: string;
'Kisit.hareketID'?: number;
'Kisit.yevmiyeFisID'?: number;
'Kisit.sirketID'?: number;
'Kisit.subeID'?: number;
'Kisit.muhasebeID'?: number;
'Kisit.tipID'?: YevmiyeFisHareketleriDetayliListeKisitTipID;
'Kisit.tarih'?: string;
'Kisit.ay'?: number;
'Kisit.yil'?: number;
'Kisit.bA'?: string;
'Kisit.miktar'?: number;
'Kisit.tutar'?: number;
'Kisit.tutarDvz'?: number;
'Kisit.dovizID'?: number;
'Kisit.oran'?: number;
'Kisit.dekontFaturaID'?: number;
'Kisit.cariHareketTabloID'?: YevmiyeFisHareketleriDetayliListeKisitCariHareketTabloID;
'Kisit.cariHareketID'?: number;
'Kisit.cariKartTabloID'?: YevmiyeFisHareketleriDetayliListeKisitCariKartTabloID;
'Kisit.cariKartID'?: number;
'Kisit.entegrasyonTanimID'?: number;
'Kisit.projeID'?: number;
'Kisit.aciklama1'?: string;
'Kisit.aciklama2'?: string;
'Kisit.bABSTutar'?: number;
'Kisit.durum'?: boolean;
/**
 * Listeleme işlemlerinde sıralama için kullanılacak kısıtı belirtir.
Örneğin, "Tarih", "Tarih:desc", "Tarih,Adi", "Tarih:desc,Adi" gibi bir değer alabilir.
 */
'SayfalandirmaBilgisi.siralamaKisiti'?: string;
/**
 * Geçerli sayfa numarasını (1'den başlar) alır veya ayarlar.
 */
'SayfalandirmaBilgisi.sayfa'?: number;
/**
 * Sayfa başına satır sayısını alır veya ayarlar. maxSayfaSatirSayisi değerini aşamaz.
 */
'SayfalandirmaBilgisi.sayfaSatirSayisi'?: number;
};
