/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type {
  AaroKayitSonuc,
  AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel,
  AaroKayitSonucAaroModullerGorevlerKayitSadeKayitModel,
  AaroKayitSonucAaroModullerGorevlerKayitSadeListeModel,
  AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel,
  AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerGorevlerKayitSadeListeModel,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi,
  AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi,
  AaroModullerGorevlerKayitSadeGorevEkleAPIModel,
  AaroModullerGorevlerKayitSadeKayitModelBody,
  AaroModullerNotlarKayitSadeKayitModelBody,
  GorevlerBelgeEklePostParams,
  GorevlerBelgeEklePostPathParameters,
  GorevlerBelgeSilDeleteParams,
  GorevlerBelgeSilDeletePathParameters,
  GorevlerBelgelerGetParams,
  GorevlerBelgelerGetPathParameters,
  GorevlerDegisiklikGecmisiGetParams,
  GorevlerDegisiklikGecmisiGetPathParameters,
  GorevlerDeleteDeletePathParameters,
  GorevlerGetGetPathParameters,
  GorevlerGrupluListeGet200Four,
  GorevlerGrupluListeGet200One,
  GorevlerGrupluListeGet200Three,
  GorevlerGrupluListeGet200Two,
  GorevlerGrupluListeGetParams,
  GorevlerListeEsnekGet200Four,
  GorevlerListeEsnekGet200One,
  GorevlerListeEsnekGet200Three,
  GorevlerListeEsnekGet200Two,
  GorevlerListeEsnekGetParams,
  GorevlerListeGetGetParams,
  GorevlerNotEklePostPathParameters,
  GorevlerNotSilDeletePathParameters,
  GorevlerNotlarGetParams,
  GorevlerNotlarGetPathParameters,
  GorevlerOnayDurumuGetPathParameters,
  GorevlerOnaylaPostParams,
  GorevlerPutPutPathParameters,
  GorevlerReddetPostParams,
  LinqFilteringAdvancedFilterRequestBody
} from '../../models';

import { customInstance } from '../../axios';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;




  export const getGorevler = () => {
/**
 * @summary Yeni bir görev oluşturur veya mevcut bir görevi hızlıca kaydeder/günceller.
Alternatif İsimler: SaveTask, CreateTask, AddNewAssignment
Kullanım: Yeni iş emri oluşturma, hızlı görev atama işlemleri
İş Kuralları: Görev başlığı zorunludur. Atanan personel belirtilmezse işlem yapan kullanıcıya atanabilir.
 */
const Gorevler_GorevKaydetPost = (
    aaroModullerGorevlerKayitSadeGorevEkleAPIModel: NonReadonly<AaroModullerGorevlerKayitSadeGorevEkleAPIModel>,
 ) => {
      return customInstance<AaroKayitSonuc>(
      {url: `/api/Gorevler/GorevKaydet`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerGorevlerKayitSadeGorevEkleAPIModel
    },
      );
    }
  /**
 * @summary Belirtilen ID'ye sahip kaydı getirir. Kart detay bilgilerini döndürür.
INTENT: kaydı getir, detayı göster, bilgileri al, ID ile sorgula, kartı görüntüle
KULLANIM: Kart görüntüleme, düzenleme öncesi mevcut bilgileri alma.
 */
const Gorevler_GetGet = (
    { id }: GorevlerGetGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerGorevlerKayitSadeListeModel>(
      {url: `/api/Gorevler/${id}`, method: 'GET'
    },
      );
    }
  const Gorevler_PutPut = (
    { id }: GorevlerPutPutPathParameters,
    aaroModullerGorevlerKayitSadeKayitModelBody: AaroModullerGorevlerKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerGorevlerKayitSadeListeModel>(
      {url: `/api/Gorevler/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerGorevlerKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı siler veya pasifleştirir.
INTENT: sil, kaldır, pasifleştir, devre dışı bırak, kapat
KULLANIM: Artık kullanılmayan kayıtları sistemden kaldırma veya pasifleştirme.
IS_KURALLARI: Hareketi veya bağlı kaydı bulunan kartlar tamamen silinemez; yalnızca pasifleştirilebilir.
 */
const Gorevler_DeleteDelete = (
    { id }: GorevlerDeleteDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerGorevlerKayitSadeListeModel>(
      {url: `/api/Gorevler/${id}`, method: 'DELETE'
    },
      );
    }
  const Gorevler_ListeGetGet = (
    params?: GorevlerListeGetGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerGorevlerKayitSadeListeModel>(
      {url: `/api/Gorevler`, method: 'GET',
        params
    },
      );
    }
  const Gorevler_PostPost = (
    aaroModullerGorevlerKayitSadeKayitModelBody: AaroModullerGorevlerKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerGorevlerKayitSadeListeModel>(
      {url: `/api/Gorevler`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerGorevlerKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı onaylar. Onay akışındaki kaydı bir sonraki aşamaya taşır.
INTENT: onayla, kabul et, akışı ilerlet, onay ver
IS_KURALLARI: Kayıt onay akışında olmalı ve onaylanabilir durumda olmalı.
 */
const Gorevler_OnaylaPost = (
    params?: GorevlerOnaylaPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerGorevlerKayitSadeKayitModel>(
      {url: `/api/Gorevler/Onayla`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydı reddeder. Onay akışındaki kaydı geri gönderir.
INTENT: reddet, geri gönder, onaylama, iade et
IS_KURALLARI: Kayıt onay akışında ve reddedilebilir durumda olmalı.
 */
const Gorevler_ReddetPost = (
    params?: GorevlerReddetPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerGorevlerKayitSadeKayitModel>(
      {url: `/api/Gorevler/Reddet`, method: 'POST',
        params
    },
      );
    }
  /**
 * FILTRE_FORMATI: {Alan}:{Operator}:{Deger}:{Mantik}
Operatörler:
  eq  — Eşit           örn: Durum:eq:True
  ct  — İçerir         örn: Ad:ct:Market
  sw  — İle başlar     örn: Kod:sw:A
  gt  — Büyüktür       örn: Bakiye:gt:5000
  in  — Listede        örn: GrupID:in:1|5|8   (değerler | ile ayrılır)
  lk  — Like (%)       örn: Adres:lk:İstanbul
Birden fazla filtre virgülle birleştirilir:
  örn: Sehir:eq:Istanbul:and,Bakiye:gt:5000:and,GrupID:in:1|5|8
            
SIRALAMA_FORMATI: {Alan}:{Yon}
  örn: Ad:asc,Bakiye:desc    (Varsayılan: Kod alanı artan)
            
SUTUN_SECIMI: Sadece ihtiyaç duyulan alanlar belirtilir; performansı artırır.
  örn: ID,Kod,Ad,Bakiye
 * @summary Dinamik ve esnek sorgulama altyapısı ile kayıt listesini getirir.
Kolon seçimi, karmaşık filtreler ve sıralama üzerinde tam kontrol sağlar.
INTENT: esnek sorgula, dinamik filtrele, özel alanları getir, karmaşık filtre uygula
KULLANIM: İnsan geliştirici ve harici entegrasyonlar için tasarlanmıştır.
          MCP ve AI çağrıları için POST /Liste tercih edilmelidir.
MCP_NOT: Bu endpoint MCP/AI çağrıları için önerilmez. 
         Tip güvensiz string filtreler hata üretme riski taşır.
         Karmaşık filtreler için POST /Liste kullanılır.
 */
const Gorevler_ListeEsnekGet = (
    params?: GorevlerListeEsnekGetParams,
 ) => {
      return customInstance<GorevlerListeEsnekGet200One | GorevlerListeEsnekGet200Two | GorevlerListeEsnekGet200Three | GorevlerListeEsnekGet200Four>(
      {url: `/api/Gorevler/Liste`, method: 'GET',
        params
    },
      );
    }
  const Gorevler_ListePostPost = (
    linqFilteringAdvancedFilterRequestBody: LinqFilteringAdvancedFilterRequestBody,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerGorevlerKayitSadeListeModel>(
      {url: `/api/Gorevler/Liste`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: linqFilteringAdvancedFilterRequestBody
    },
      );
    }
  /**
 * @summary Kayıtları belirtilen alanlara göre gruplayarak özet liste döndürür.
INTENT: grupla, özet al, gruplara göre say, gruplama raporu
KULLANIM: Gruplama bazlı raporlama ve istatistik sorgularında kullanılır.
YETKI: Hareket özeti admini gerektirir.
 */
const Gorevler_GrupluListeGet = (
    params?: GorevlerGrupluListeGetParams,
 ) => {
      return customInstance<GorevlerGrupluListeGet200One | GorevlerGrupluListeGet200Two | GorevlerGrupluListeGet200Three | GorevlerGrupluListeGet200Four>(
      {url: `/api/Gorevler/GrupluListe`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydın onay durumunu ve onay geçmişini getirir.
INTENT: onay durumu nedir, onaylandı mı, hangi aşamada, onay sorgula
KULLANIM: Onay akışı takibi, kaydın hangi adımda olduğunu öğrenme.
 */
const Gorevler_OnayDurumuGet = (
    { id }: GorevlerOnayDurumuGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi>(
      {url: `/api/Gorevler/${id}/OnayDurumu`, method: 'GET'
    },
      );
    }
  /**
 * @summary Belirtilen kaydın değişiklik geçmişini getirir. Kim, ne zaman, ne değiştirdi bilgisi.
INTENT: değişiklik geçmişi, kim değiştirdi, ne zaman değişti, log, audit, tarihçe
KULLANIM: Kayıt üzerinde yapılan tüm değişikliklerin izlenmesi ve denetimi.
 */
const Gorevler_DegisiklikGecmisiGet = (
    { id }: GorevlerDegisiklikGecmisiGetPathParameters,
    params?: GorevlerDegisiklikGecmisiGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi>(
      {url: `/api/Gorevler/${id}/DegisiklikGecmisi`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait belge listesini getirir.
INTENT: belgeleri getir, dosyaları listele, ekleri göster, dokümanlar
KULLANIM: Kayda eklenmiş sözleşme, fatura, resim gibi belgelerin listelenmesi.
 */
const Gorevler_BelgelerGet = (
    { id }: GorevlerBelgelerGetPathParameters,
    params?: GorevlerBelgelerGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi>(
      {url: `/api/Gorevler/${id}/Belgeler`, method: 'GET',
        params
    },
      );
    }
  const Gorevler_BelgeEklePost = (
    { id }: GorevlerBelgeEklePostPathParameters,
    params?: GorevlerBelgeEklePostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/Gorevler/${id}/BelgeEkle`, method: 'POST',
        params
    },
      );
    }
  const Gorevler_BelgeSilDelete = (
    { id, belgeID }: GorevlerBelgeSilDeletePathParameters,
    params?: GorevlerBelgeSilDeleteParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/Gorevler/${id}/BelgeSil/${belgeID}`, method: 'DELETE',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait notları getirir.
INTENT: notları getir, açıklamaları göster, yorumları listele, notlar neler
KULLANIM: Kayda eklenen serbest metin notların, hatırlatmaların veya açıklamaların listelenmesi.
 */
const Gorevler_NotlarGet = (
    { id }: GorevlerNotlarGetPathParameters,
    params?: GorevlerNotlarGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi>(
      {url: `/api/Gorevler/${id}/Notlar`, method: 'GET',
        params
    },
      );
    }
  const Gorevler_NotEklePost = (
    { id }: GorevlerNotEklePostPathParameters,
    aaroModullerNotlarKayitSadeKayitModelBody: AaroModullerNotlarKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/Gorevler/${id}/NotEkle`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerNotlarKayitSadeKayitModelBody
    },
      );
    }
  const Gorevler_NotSilDelete = (
    { id, notID }: GorevlerNotSilDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/Gorevler/${id}/NotSil/${notID}`, method: 'DELETE'
    },
      );
    }
  return {Gorevler_GorevKaydetPost,Gorevler_GetGet,Gorevler_PutPut,Gorevler_DeleteDelete,Gorevler_ListeGetGet,Gorevler_PostPost,Gorevler_OnaylaPost,Gorevler_ReddetPost,Gorevler_ListeEsnekGet,Gorevler_ListePostPost,Gorevler_GrupluListeGet,Gorevler_OnayDurumuGet,Gorevler_DegisiklikGecmisiGet,Gorevler_BelgelerGet,Gorevler_BelgeEklePost,Gorevler_BelgeSilDelete,Gorevler_NotlarGet,Gorevler_NotEklePost,Gorevler_NotSilDelete}};
export type GorevlerGorevKaydetPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGorevler>['Gorevler_GorevKaydetPost']>>>
export type GorevlerGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGorevler>['Gorevler_GetGet']>>>
export type GorevlerPutPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGorevler>['Gorevler_PutPut']>>>
export type GorevlerDeleteDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGorevler>['Gorevler_DeleteDelete']>>>
export type GorevlerListeGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGorevler>['Gorevler_ListeGetGet']>>>
export type GorevlerPostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGorevler>['Gorevler_PostPost']>>>
export type GorevlerOnaylaPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGorevler>['Gorevler_OnaylaPost']>>>
export type GorevlerReddetPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGorevler>['Gorevler_ReddetPost']>>>
export type GorevlerListeEsnekGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGorevler>['Gorevler_ListeEsnekGet']>>>
export type GorevlerListePostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGorevler>['Gorevler_ListePostPost']>>>
export type GorevlerGrupluListeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGorevler>['Gorevler_GrupluListeGet']>>>
export type GorevlerOnayDurumuGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGorevler>['Gorevler_OnayDurumuGet']>>>
export type GorevlerDegisiklikGecmisiGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGorevler>['Gorevler_DegisiklikGecmisiGet']>>>
export type GorevlerBelgelerGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGorevler>['Gorevler_BelgelerGet']>>>
export type GorevlerBelgeEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGorevler>['Gorevler_BelgeEklePost']>>>
export type GorevlerBelgeSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGorevler>['Gorevler_BelgeSilDelete']>>>
export type GorevlerNotlarGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGorevler>['Gorevler_NotlarGet']>>>
export type GorevlerNotEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGorevler>['Gorevler_NotEklePost']>>>
export type GorevlerNotSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGorevler>['Gorevler_NotSilDelete']>>>
