/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type {
  AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel,
  AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel,
  AaroKayitSonucAaroModullerUrAkisOperasyonMamulKayitSadeKayitModel,
  AaroKayitSonucAaroModullerUrAkisOperasyonMamulKayitSadeListeModel,
  AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrAkisOperasyonMamulKayitSadeListeModel,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi,
  AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi,
  AaroModullerNotlarKayitSadeKayitModelBody,
  AaroModullerUrAkisOperasyonMamulKayitSadeKayitModelBody,
  LinqFilteringAdvancedFilterRequestBody,
  UrAkisOperasyonMamulBelgeEklePostParams,
  UrAkisOperasyonMamulBelgeEklePostPathParameters,
  UrAkisOperasyonMamulBelgeSilDeleteParams,
  UrAkisOperasyonMamulBelgeSilDeletePathParameters,
  UrAkisOperasyonMamulBelgelerGetParams,
  UrAkisOperasyonMamulBelgelerGetPathParameters,
  UrAkisOperasyonMamulDegisiklikGecmisiGetParams,
  UrAkisOperasyonMamulDegisiklikGecmisiGetPathParameters,
  UrAkisOperasyonMamulDeleteDeletePathParameters,
  UrAkisOperasyonMamulDetayliListeGetParams,
  UrAkisOperasyonMamulGetGetPathParameters,
  UrAkisOperasyonMamulGrupluListeGet200Four,
  UrAkisOperasyonMamulGrupluListeGet200One,
  UrAkisOperasyonMamulGrupluListeGet200Three,
  UrAkisOperasyonMamulGrupluListeGet200Two,
  UrAkisOperasyonMamulGrupluListeGetParams,
  UrAkisOperasyonMamulListeEsnekGet200Four,
  UrAkisOperasyonMamulListeEsnekGet200One,
  UrAkisOperasyonMamulListeEsnekGet200Three,
  UrAkisOperasyonMamulListeEsnekGet200Two,
  UrAkisOperasyonMamulListeEsnekGetParams,
  UrAkisOperasyonMamulNotEklePostPathParameters,
  UrAkisOperasyonMamulNotSilDeletePathParameters,
  UrAkisOperasyonMamulNotlarGetParams,
  UrAkisOperasyonMamulNotlarGetPathParameters,
  UrAkisOperasyonMamulOnayDurumuGetPathParameters,
  UrAkisOperasyonMamulOnaylaPostParams,
  UrAkisOperasyonMamulPutPutPathParameters,
  UrAkisOperasyonMamulReddetPostParams
} from '../../models';

import { customInstance } from '../../axios';



  export const getUrAkisOperasyonMamul = () => {
const UrAkisOperasyonMamul_GetGet = (
    { id }: UrAkisOperasyonMamulGetGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerUrAkisOperasyonMamulKayitSadeListeModel>(
      {url: `/api/UrAkisOperasyonMamul/${id}`, method: 'GET'
    },
      );
    }
  const UrAkisOperasyonMamul_PutPut = (
    { id }: UrAkisOperasyonMamulPutPutPathParameters,
    aaroModullerUrAkisOperasyonMamulKayitSadeKayitModelBody: AaroModullerUrAkisOperasyonMamulKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerUrAkisOperasyonMamulKayitSadeListeModel>(
      {url: `/api/UrAkisOperasyonMamul/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerUrAkisOperasyonMamulKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı siler veya pasifleştirir.
INTENT: sil, kaldır, pasifleştir, devre dışı bırak, kapat
KULLANIM: Artık kullanılmayan kayıtları sistemden kaldırma veya pasifleştirme.
IS_KURALLARI: Hareketi veya bağlı kaydı bulunan kartlar tamamen silinemez; yalnızca pasifleştirilebilir.
 */
const UrAkisOperasyonMamul_DeleteDelete = (
    { id }: UrAkisOperasyonMamulDeleteDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerUrAkisOperasyonMamulKayitSadeListeModel>(
      {url: `/api/UrAkisOperasyonMamul/${id}`, method: 'DELETE'
    },
      );
    }
  const UrAkisOperasyonMamul_DetayliListeGet = (
    params?: UrAkisOperasyonMamulDetayliListeGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrAkisOperasyonMamulKayitSadeListeModel>(
      {url: `/api/UrAkisOperasyonMamul`, method: 'GET',
        params
    },
      );
    }
  const UrAkisOperasyonMamul_PostPost = (
    aaroModullerUrAkisOperasyonMamulKayitSadeKayitModelBody: AaroModullerUrAkisOperasyonMamulKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerUrAkisOperasyonMamulKayitSadeListeModel>(
      {url: `/api/UrAkisOperasyonMamul`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerUrAkisOperasyonMamulKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı onaylar. Onay akışındaki kaydı bir sonraki aşamaya taşır.
INTENT: onayla, kabul et, akışı ilerlet, onay ver
IS_KURALLARI: Kayıt onay akışında olmalı ve onaylanabilir durumda olmalı.
 */
const UrAkisOperasyonMamul_OnaylaPost = (
    params?: UrAkisOperasyonMamulOnaylaPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerUrAkisOperasyonMamulKayitSadeKayitModel>(
      {url: `/api/UrAkisOperasyonMamul/Onayla`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydı reddeder. Onay akışındaki kaydı geri gönderir.
INTENT: reddet, geri gönder, onaylama, iade et
IS_KURALLARI: Kayıt onay akışında ve reddedilebilir durumda olmalı.
 */
const UrAkisOperasyonMamul_ReddetPost = (
    params?: UrAkisOperasyonMamulReddetPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerUrAkisOperasyonMamulKayitSadeKayitModel>(
      {url: `/api/UrAkisOperasyonMamul/Reddet`, method: 'POST',
        params
    },
      );
    }
  /**
 * FILTRE_FORMATI: {Alan}:{Operator}:{Deger}:{Mantik}
Operatörler:
  eq  — Eşit           örn: Durum:eq:True
  ct  — İçerir         örn: Ad:ct:Market
  sw  — İle başlar     örn: Kod:sw:A
  gt  — Büyüktür       örn: Bakiye:gt:5000
  in  — Listede        örn: GrupID:in:1|5|8   (değerler | ile ayrılır)
  lk  — Like (%)       örn: Adres:lk:İstanbul
Birden fazla filtre virgülle birleştirilir:
  örn: Sehir:eq:Istanbul:and,Bakiye:gt:5000:and,GrupID:in:1|5|8
            
SIRALAMA_FORMATI: {Alan}:{Yon}
  örn: Ad:asc,Bakiye:desc    (Varsayılan: Kod alanı artan)
            
SUTUN_SECIMI: Sadece ihtiyaç duyulan alanlar belirtilir; performansı artırır.
  örn: ID,Kod,Ad,Bakiye
 * @summary Dinamik ve esnek sorgulama altyapısı ile kayıt listesini getirir.
Kolon seçimi, karmaşık filtreler ve sıralama üzerinde tam kontrol sağlar.
INTENT: esnek sorgula, dinamik filtrele, özel alanları getir, karmaşık filtre uygula
KULLANIM: İnsan geliştirici ve harici entegrasyonlar için tasarlanmıştır.
          MCP ve AI çağrıları için POST /Liste tercih edilmelidir.
MCP_NOT: Bu endpoint MCP/AI çağrıları için önerilmez. 
         Tip güvensiz string filtreler hata üretme riski taşır.
         Karmaşık filtreler için POST /Liste kullanılır.
 */
const UrAkisOperasyonMamul_ListeEsnekGet = (
    params?: UrAkisOperasyonMamulListeEsnekGetParams,
 ) => {
      return customInstance<UrAkisOperasyonMamulListeEsnekGet200One | UrAkisOperasyonMamulListeEsnekGet200Two | UrAkisOperasyonMamulListeEsnekGet200Three | UrAkisOperasyonMamulListeEsnekGet200Four>(
      {url: `/api/UrAkisOperasyonMamul/Liste`, method: 'GET',
        params
    },
      );
    }
  const UrAkisOperasyonMamul_ListePostPost = (
    linqFilteringAdvancedFilterRequestBody: LinqFilteringAdvancedFilterRequestBody,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrAkisOperasyonMamulKayitSadeListeModel>(
      {url: `/api/UrAkisOperasyonMamul/Liste`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: linqFilteringAdvancedFilterRequestBody
    },
      );
    }
  /**
 * @summary Kayıtları belirtilen alanlara göre gruplayarak özet liste döndürür.
INTENT: grupla, özet al, gruplara göre say, gruplama raporu
KULLANIM: Gruplama bazlı raporlama ve istatistik sorgularında kullanılır.
YETKI: Hareket özeti admini gerektirir.
 */
const UrAkisOperasyonMamul_GrupluListeGet = (
    params?: UrAkisOperasyonMamulGrupluListeGetParams,
 ) => {
      return customInstance<UrAkisOperasyonMamulGrupluListeGet200One | UrAkisOperasyonMamulGrupluListeGet200Two | UrAkisOperasyonMamulGrupluListeGet200Three | UrAkisOperasyonMamulGrupluListeGet200Four>(
      {url: `/api/UrAkisOperasyonMamul/GrupluListe`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydın onay durumunu ve onay geçmişini getirir.
INTENT: onay durumu nedir, onaylandı mı, hangi aşamada, onay sorgula
KULLANIM: Onay akışı takibi, kaydın hangi adımda olduğunu öğrenme.
 */
const UrAkisOperasyonMamul_OnayDurumuGet = (
    { id }: UrAkisOperasyonMamulOnayDurumuGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi>(
      {url: `/api/UrAkisOperasyonMamul/${id}/OnayDurumu`, method: 'GET'
    },
      );
    }
  /**
 * @summary Belirtilen kaydın değişiklik geçmişini getirir. Kim, ne zaman, ne değiştirdi bilgisi.
INTENT: değişiklik geçmişi, kim değiştirdi, ne zaman değişti, log, audit, tarihçe
KULLANIM: Kayıt üzerinde yapılan tüm değişikliklerin izlenmesi ve denetimi.
 */
const UrAkisOperasyonMamul_DegisiklikGecmisiGet = (
    { id }: UrAkisOperasyonMamulDegisiklikGecmisiGetPathParameters,
    params?: UrAkisOperasyonMamulDegisiklikGecmisiGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi>(
      {url: `/api/UrAkisOperasyonMamul/${id}/DegisiklikGecmisi`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait belge listesini getirir.
INTENT: belgeleri getir, dosyaları listele, ekleri göster, dokümanlar
KULLANIM: Kayda eklenmiş sözleşme, fatura, resim gibi belgelerin listelenmesi.
 */
const UrAkisOperasyonMamul_BelgelerGet = (
    { id }: UrAkisOperasyonMamulBelgelerGetPathParameters,
    params?: UrAkisOperasyonMamulBelgelerGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi>(
      {url: `/api/UrAkisOperasyonMamul/${id}/Belgeler`, method: 'GET',
        params
    },
      );
    }
  const UrAkisOperasyonMamul_BelgeEklePost = (
    { id }: UrAkisOperasyonMamulBelgeEklePostPathParameters,
    params?: UrAkisOperasyonMamulBelgeEklePostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/UrAkisOperasyonMamul/${id}/BelgeEkle`, method: 'POST',
        params
    },
      );
    }
  const UrAkisOperasyonMamul_BelgeSilDelete = (
    { id, belgeID }: UrAkisOperasyonMamulBelgeSilDeletePathParameters,
    params?: UrAkisOperasyonMamulBelgeSilDeleteParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/UrAkisOperasyonMamul/${id}/BelgeSil/${belgeID}`, method: 'DELETE',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait notları getirir.
INTENT: notları getir, açıklamaları göster, yorumları listele, notlar neler
KULLANIM: Kayda eklenen serbest metin notların, hatırlatmaların veya açıklamaların listelenmesi.
 */
const UrAkisOperasyonMamul_NotlarGet = (
    { id }: UrAkisOperasyonMamulNotlarGetPathParameters,
    params?: UrAkisOperasyonMamulNotlarGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi>(
      {url: `/api/UrAkisOperasyonMamul/${id}/Notlar`, method: 'GET',
        params
    },
      );
    }
  const UrAkisOperasyonMamul_NotEklePost = (
    { id }: UrAkisOperasyonMamulNotEklePostPathParameters,
    aaroModullerNotlarKayitSadeKayitModelBody: AaroModullerNotlarKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/UrAkisOperasyonMamul/${id}/NotEkle`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerNotlarKayitSadeKayitModelBody
    },
      );
    }
  const UrAkisOperasyonMamul_NotSilDelete = (
    { id, notID }: UrAkisOperasyonMamulNotSilDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/UrAkisOperasyonMamul/${id}/NotSil/${notID}`, method: 'DELETE'
    },
      );
    }
  return {UrAkisOperasyonMamul_GetGet,UrAkisOperasyonMamul_PutPut,UrAkisOperasyonMamul_DeleteDelete,UrAkisOperasyonMamul_DetayliListeGet,UrAkisOperasyonMamul_PostPost,UrAkisOperasyonMamul_OnaylaPost,UrAkisOperasyonMamul_ReddetPost,UrAkisOperasyonMamul_ListeEsnekGet,UrAkisOperasyonMamul_ListePostPost,UrAkisOperasyonMamul_GrupluListeGet,UrAkisOperasyonMamul_OnayDurumuGet,UrAkisOperasyonMamul_DegisiklikGecmisiGet,UrAkisOperasyonMamul_BelgelerGet,UrAkisOperasyonMamul_BelgeEklePost,UrAkisOperasyonMamul_BelgeSilDelete,UrAkisOperasyonMamul_NotlarGet,UrAkisOperasyonMamul_NotEklePost,UrAkisOperasyonMamul_NotSilDelete}};
export type UrAkisOperasyonMamulGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrAkisOperasyonMamul>['UrAkisOperasyonMamul_GetGet']>>>
export type UrAkisOperasyonMamulPutPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrAkisOperasyonMamul>['UrAkisOperasyonMamul_PutPut']>>>
export type UrAkisOperasyonMamulDeleteDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrAkisOperasyonMamul>['UrAkisOperasyonMamul_DeleteDelete']>>>
export type UrAkisOperasyonMamulDetayliListeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrAkisOperasyonMamul>['UrAkisOperasyonMamul_DetayliListeGet']>>>
export type UrAkisOperasyonMamulPostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrAkisOperasyonMamul>['UrAkisOperasyonMamul_PostPost']>>>
export type UrAkisOperasyonMamulOnaylaPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrAkisOperasyonMamul>['UrAkisOperasyonMamul_OnaylaPost']>>>
export type UrAkisOperasyonMamulReddetPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrAkisOperasyonMamul>['UrAkisOperasyonMamul_ReddetPost']>>>
export type UrAkisOperasyonMamulListeEsnekGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrAkisOperasyonMamul>['UrAkisOperasyonMamul_ListeEsnekGet']>>>
export type UrAkisOperasyonMamulListePostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrAkisOperasyonMamul>['UrAkisOperasyonMamul_ListePostPost']>>>
export type UrAkisOperasyonMamulGrupluListeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrAkisOperasyonMamul>['UrAkisOperasyonMamul_GrupluListeGet']>>>
export type UrAkisOperasyonMamulOnayDurumuGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrAkisOperasyonMamul>['UrAkisOperasyonMamul_OnayDurumuGet']>>>
export type UrAkisOperasyonMamulDegisiklikGecmisiGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrAkisOperasyonMamul>['UrAkisOperasyonMamul_DegisiklikGecmisiGet']>>>
export type UrAkisOperasyonMamulBelgelerGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrAkisOperasyonMamul>['UrAkisOperasyonMamul_BelgelerGet']>>>
export type UrAkisOperasyonMamulBelgeEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrAkisOperasyonMamul>['UrAkisOperasyonMamul_BelgeEklePost']>>>
export type UrAkisOperasyonMamulBelgeSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrAkisOperasyonMamul>['UrAkisOperasyonMamul_BelgeSilDelete']>>>
export type UrAkisOperasyonMamulNotlarGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrAkisOperasyonMamul>['UrAkisOperasyonMamul_NotlarGet']>>>
export type UrAkisOperasyonMamulNotEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrAkisOperasyonMamul>['UrAkisOperasyonMamul_NotEklePost']>>>
export type UrAkisOperasyonMamulNotSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrAkisOperasyonMamul>['UrAkisOperasyonMamul_NotSilDelete']>>>
