/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type {
  AaroKayitSonucSystemString,
  EkGorevlerBelgeNoGetParams,
  EkGorevlerKartKoduGetParams
} from '../../models';

import { customInstance } from '../../axios';



  export const getEkGorevler = () => {
/**
 * @summary Belirlenen işlem tipi ve seriye göre sistemdeki bir sonraki boş belge numarasını getirir.
Alternatif İsimler: GetNextDocumentNumber, OtomatikEvrakNo, GetSequenceNumber
Kullanım: Yeni bir fatura veya sipariş oluşturulurken, kullanıcıya otomatik bir numara önermek için kullanılır.
 */
const EkGorevler_BelgeNoGet = (
    params?: EkGorevlerBelgeNoGetParams,
 ) => {
      return customInstance<AaroKayitSonucSystemString>(
      {url: `/api/EkGorevler/BelgeNo`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirli bir tablo ve kolon için hiyerarşik veya serili sıradaki kart kodunu üretir.
Alternatif İsimler: GetNextCardCode, KartKodUretici, GenerateRecordCode
Kullanım: Yeni bir stok kartı veya müşteri (cari) kaydı açılırken, "STK0001" gibi otomatik kodlar üretmek için kullanılır.
 */
const EkGorevler_KartKoduGet = (
    params?: EkGorevlerKartKoduGetParams,
 ) => {
      return customInstance<AaroKayitSonucSystemString>(
      {url: `/api/EkGorevler/KartKodu`, method: 'GET',
        params
    },
      );
    }
  return {EkGorevler_BelgeNoGet,EkGorevler_KartKoduGet}};
export type EkGorevlerBelgeNoGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEkGorevler>['EkGorevler_BelgeNoGet']>>>
export type EkGorevlerKartKoduGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEkGorevler>['EkGorevler_KartKoduGet']>>>
