/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type {
  AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel,
  AaroKayitSonucAaroModullerCariIlgiliKayitSadeKayitModel,
  AaroKayitSonucAaroModullerCariIlgiliKayitSadeListeModel,
  AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel,
  AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariIlgiliKayitSadeListeModel,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi,
  AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi,
  AaroModullerCariIlgiliKayitSadeKayitModelBody,
  AaroModullerNotlarKayitSadeKayitModelBody,
  CariIlgiliBelgeEklePostParams,
  CariIlgiliBelgeEklePostPathParameters,
  CariIlgiliBelgeSilDeleteParams,
  CariIlgiliBelgeSilDeletePathParameters,
  CariIlgiliBelgelerGetParams,
  CariIlgiliBelgelerGetPathParameters,
  CariIlgiliDegisiklikGecmisiGetParams,
  CariIlgiliDegisiklikGecmisiGetPathParameters,
  CariIlgiliDeleteDeletePathParameters,
  CariIlgiliGetGetPathParameters,
  CariIlgiliGrupluListeGet200Four,
  CariIlgiliGrupluListeGet200One,
  CariIlgiliGrupluListeGet200Three,
  CariIlgiliGrupluListeGet200Two,
  CariIlgiliGrupluListeGetParams,
  CariIlgiliListeEsnekGet200Four,
  CariIlgiliListeEsnekGet200One,
  CariIlgiliListeEsnekGet200Three,
  CariIlgiliListeEsnekGet200Two,
  CariIlgiliListeEsnekGetParams,
  CariIlgiliListeGetGetParams,
  CariIlgiliNotEklePostPathParameters,
  CariIlgiliNotSilDeletePathParameters,
  CariIlgiliNotlarGetParams,
  CariIlgiliNotlarGetPathParameters,
  CariIlgiliOnayDurumuGetPathParameters,
  CariIlgiliOnaylaPostParams,
  CariIlgiliPutPutPathParameters,
  CariIlgiliReddetPostParams,
  LinqFilteringAdvancedFilterRequestBody
} from '../../models';

import { customInstance } from '../../axios';



  export const getCariIlgili = () => {
/**
 * @summary Belirtilen ID'ye sahip kaydı getirir. Kart detay bilgilerini döndürür.
INTENT: kaydı getir, detayı göster, bilgileri al, ID ile sorgula, kartı görüntüle
KULLANIM: Kart görüntüleme, düzenleme öncesi mevcut bilgileri alma.
 */
const CariIlgili_GetGet = (
    { id }: CariIlgiliGetGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerCariIlgiliKayitSadeListeModel>(
      {url: `/api/CariIlgili/${id}`, method: 'GET'
    },
      );
    }
  const CariIlgili_PutPut = (
    { id }: CariIlgiliPutPutPathParameters,
    aaroModullerCariIlgiliKayitSadeKayitModelBody: AaroModullerCariIlgiliKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerCariIlgiliKayitSadeListeModel>(
      {url: `/api/CariIlgili/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerCariIlgiliKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı siler veya pasifleştirir.
INTENT: sil, kaldır, pasifleştir, devre dışı bırak, kapat
KULLANIM: Artık kullanılmayan kayıtları sistemden kaldırma veya pasifleştirme.
IS_KURALLARI: Hareketi veya bağlı kaydı bulunan kartlar tamamen silinemez; yalnızca pasifleştirilebilir.
 */
const CariIlgili_DeleteDelete = (
    { id }: CariIlgiliDeleteDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerCariIlgiliKayitSadeListeModel>(
      {url: `/api/CariIlgili/${id}`, method: 'DELETE'
    },
      );
    }
  const CariIlgili_ListeGetGet = (
    params?: CariIlgiliListeGetGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariIlgiliKayitSadeListeModel>(
      {url: `/api/CariIlgili`, method: 'GET',
        params
    },
      );
    }
  const CariIlgili_PostPost = (
    aaroModullerCariIlgiliKayitSadeKayitModelBody: AaroModullerCariIlgiliKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerCariIlgiliKayitSadeListeModel>(
      {url: `/api/CariIlgili`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerCariIlgiliKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı onaylar. Onay akışındaki kaydı bir sonraki aşamaya taşır.
INTENT: onayla, kabul et, akışı ilerlet, onay ver
IS_KURALLARI: Kayıt onay akışında olmalı ve onaylanabilir durumda olmalı.
 */
const CariIlgili_OnaylaPost = (
    params?: CariIlgiliOnaylaPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerCariIlgiliKayitSadeKayitModel>(
      {url: `/api/CariIlgili/Onayla`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydı reddeder. Onay akışındaki kaydı geri gönderir.
INTENT: reddet, geri gönder, onaylama, iade et
IS_KURALLARI: Kayıt onay akışında ve reddedilebilir durumda olmalı.
 */
const CariIlgili_ReddetPost = (
    params?: CariIlgiliReddetPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerCariIlgiliKayitSadeKayitModel>(
      {url: `/api/CariIlgili/Reddet`, method: 'POST',
        params
    },
      );
    }
  /**
 * FILTRE_FORMATI: {Alan}:{Operator}:{Deger}:{Mantik}
Operatörler:
  eq  — Eşit           örn: Durum:eq:True
  ct  — İçerir         örn: Ad:ct:Market
  sw  — İle başlar     örn: Kod:sw:A
  gt  — Büyüktür       örn: Bakiye:gt:5000
  in  — Listede        örn: GrupID:in:1|5|8   (değerler | ile ayrılır)
  lk  — Like (%)       örn: Adres:lk:İstanbul
Birden fazla filtre virgülle birleştirilir:
  örn: Sehir:eq:Istanbul:and,Bakiye:gt:5000:and,GrupID:in:1|5|8
            
SIRALAMA_FORMATI: {Alan}:{Yon}
  örn: Ad:asc,Bakiye:desc    (Varsayılan: Kod alanı artan)
            
SUTUN_SECIMI: Sadece ihtiyaç duyulan alanlar belirtilir; performansı artırır.
  örn: ID,Kod,Ad,Bakiye
 * @summary Dinamik ve esnek sorgulama altyapısı ile kayıt listesini getirir.
Kolon seçimi, karmaşık filtreler ve sıralama üzerinde tam kontrol sağlar.
INTENT: esnek sorgula, dinamik filtrele, özel alanları getir, karmaşık filtre uygula
KULLANIM: İnsan geliştirici ve harici entegrasyonlar için tasarlanmıştır.
          MCP ve AI çağrıları için POST /Liste tercih edilmelidir.
MCP_NOT: Bu endpoint MCP/AI çağrıları için önerilmez. 
         Tip güvensiz string filtreler hata üretme riski taşır.
         Karmaşık filtreler için POST /Liste kullanılır.
 */
const CariIlgili_ListeEsnekGet = (
    params?: CariIlgiliListeEsnekGetParams,
 ) => {
      return customInstance<CariIlgiliListeEsnekGet200One | CariIlgiliListeEsnekGet200Two | CariIlgiliListeEsnekGet200Three | CariIlgiliListeEsnekGet200Four>(
      {url: `/api/CariIlgili/Liste`, method: 'GET',
        params
    },
      );
    }
  const CariIlgili_ListePostPost = (
    linqFilteringAdvancedFilterRequestBody: LinqFilteringAdvancedFilterRequestBody,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariIlgiliKayitSadeListeModel>(
      {url: `/api/CariIlgili/Liste`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: linqFilteringAdvancedFilterRequestBody
    },
      );
    }
  /**
 * @summary Kayıtları belirtilen alanlara göre gruplayarak özet liste döndürür.
INTENT: grupla, özet al, gruplara göre say, gruplama raporu
KULLANIM: Gruplama bazlı raporlama ve istatistik sorgularında kullanılır.
YETKI: Hareket özeti admini gerektirir.
 */
const CariIlgili_GrupluListeGet = (
    params?: CariIlgiliGrupluListeGetParams,
 ) => {
      return customInstance<CariIlgiliGrupluListeGet200One | CariIlgiliGrupluListeGet200Two | CariIlgiliGrupluListeGet200Three | CariIlgiliGrupluListeGet200Four>(
      {url: `/api/CariIlgili/GrupluListe`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydın onay durumunu ve onay geçmişini getirir.
INTENT: onay durumu nedir, onaylandı mı, hangi aşamada, onay sorgula
KULLANIM: Onay akışı takibi, kaydın hangi adımda olduğunu öğrenme.
 */
const CariIlgili_OnayDurumuGet = (
    { id }: CariIlgiliOnayDurumuGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi>(
      {url: `/api/CariIlgili/${id}/OnayDurumu`, method: 'GET'
    },
      );
    }
  /**
 * @summary Belirtilen kaydın değişiklik geçmişini getirir. Kim, ne zaman, ne değiştirdi bilgisi.
INTENT: değişiklik geçmişi, kim değiştirdi, ne zaman değişti, log, audit, tarihçe
KULLANIM: Kayıt üzerinde yapılan tüm değişikliklerin izlenmesi ve denetimi.
 */
const CariIlgili_DegisiklikGecmisiGet = (
    { id }: CariIlgiliDegisiklikGecmisiGetPathParameters,
    params?: CariIlgiliDegisiklikGecmisiGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi>(
      {url: `/api/CariIlgili/${id}/DegisiklikGecmisi`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait belge listesini getirir.
INTENT: belgeleri getir, dosyaları listele, ekleri göster, dokümanlar
KULLANIM: Kayda eklenmiş sözleşme, fatura, resim gibi belgelerin listelenmesi.
 */
const CariIlgili_BelgelerGet = (
    { id }: CariIlgiliBelgelerGetPathParameters,
    params?: CariIlgiliBelgelerGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi>(
      {url: `/api/CariIlgili/${id}/Belgeler`, method: 'GET',
        params
    },
      );
    }
  const CariIlgili_BelgeEklePost = (
    { id }: CariIlgiliBelgeEklePostPathParameters,
    params?: CariIlgiliBelgeEklePostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/CariIlgili/${id}/BelgeEkle`, method: 'POST',
        params
    },
      );
    }
  const CariIlgili_BelgeSilDelete = (
    { id, belgeID }: CariIlgiliBelgeSilDeletePathParameters,
    params?: CariIlgiliBelgeSilDeleteParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/CariIlgili/${id}/BelgeSil/${belgeID}`, method: 'DELETE',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait notları getirir.
INTENT: notları getir, açıklamaları göster, yorumları listele, notlar neler
KULLANIM: Kayda eklenen serbest metin notların, hatırlatmaların veya açıklamaların listelenmesi.
 */
const CariIlgili_NotlarGet = (
    { id }: CariIlgiliNotlarGetPathParameters,
    params?: CariIlgiliNotlarGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi>(
      {url: `/api/CariIlgili/${id}/Notlar`, method: 'GET',
        params
    },
      );
    }
  const CariIlgili_NotEklePost = (
    { id }: CariIlgiliNotEklePostPathParameters,
    aaroModullerNotlarKayitSadeKayitModelBody: AaroModullerNotlarKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/CariIlgili/${id}/NotEkle`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerNotlarKayitSadeKayitModelBody
    },
      );
    }
  const CariIlgili_NotSilDelete = (
    { id, notID }: CariIlgiliNotSilDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/CariIlgili/${id}/NotSil/${notID}`, method: 'DELETE'
    },
      );
    }
  return {CariIlgili_GetGet,CariIlgili_PutPut,CariIlgili_DeleteDelete,CariIlgili_ListeGetGet,CariIlgili_PostPost,CariIlgili_OnaylaPost,CariIlgili_ReddetPost,CariIlgili_ListeEsnekGet,CariIlgili_ListePostPost,CariIlgili_GrupluListeGet,CariIlgili_OnayDurumuGet,CariIlgili_DegisiklikGecmisiGet,CariIlgili_BelgelerGet,CariIlgili_BelgeEklePost,CariIlgili_BelgeSilDelete,CariIlgili_NotlarGet,CariIlgili_NotEklePost,CariIlgili_NotSilDelete}};
export type CariIlgiliGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariIlgili>['CariIlgili_GetGet']>>>
export type CariIlgiliPutPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariIlgili>['CariIlgili_PutPut']>>>
export type CariIlgiliDeleteDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariIlgili>['CariIlgili_DeleteDelete']>>>
export type CariIlgiliListeGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariIlgili>['CariIlgili_ListeGetGet']>>>
export type CariIlgiliPostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariIlgili>['CariIlgili_PostPost']>>>
export type CariIlgiliOnaylaPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariIlgili>['CariIlgili_OnaylaPost']>>>
export type CariIlgiliReddetPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariIlgili>['CariIlgili_ReddetPost']>>>
export type CariIlgiliListeEsnekGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariIlgili>['CariIlgili_ListeEsnekGet']>>>
export type CariIlgiliListePostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariIlgili>['CariIlgili_ListePostPost']>>>
export type CariIlgiliGrupluListeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariIlgili>['CariIlgili_GrupluListeGet']>>>
export type CariIlgiliOnayDurumuGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariIlgili>['CariIlgili_OnayDurumuGet']>>>
export type CariIlgiliDegisiklikGecmisiGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariIlgili>['CariIlgili_DegisiklikGecmisiGet']>>>
export type CariIlgiliBelgelerGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariIlgili>['CariIlgili_BelgelerGet']>>>
export type CariIlgiliBelgeEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariIlgili>['CariIlgili_BelgeEklePost']>>>
export type CariIlgiliBelgeSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariIlgili>['CariIlgili_BelgeSilDelete']>>>
export type CariIlgiliNotlarGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariIlgili>['CariIlgili_NotlarGet']>>>
export type CariIlgiliNotEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariIlgili>['CariIlgili_NotEklePost']>>>
export type CariIlgiliNotSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariIlgili>['CariIlgili_NotSilDelete']>>>
