/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type {
  AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel,
  AaroKayitSonucAaroModullerCariBankaKayitSadeKayitModel,
  AaroKayitSonucAaroModullerCariBankaKayitSadeListeModel,
  AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel,
  AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariBankaKayitSadeListeModel,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi,
  AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi,
  AaroModullerCariBankaKayitSadeKayitModelBody,
  AaroModullerNotlarKayitSadeKayitModelBody,
  CariBankaBelgeEklePostParams,
  CariBankaBelgeEklePostPathParameters,
  CariBankaBelgeSilDeleteParams,
  CariBankaBelgeSilDeletePathParameters,
  CariBankaBelgelerGetParams,
  CariBankaBelgelerGetPathParameters,
  CariBankaDegisiklikGecmisiGetParams,
  CariBankaDegisiklikGecmisiGetPathParameters,
  CariBankaDeleteDeletePathParameters,
  CariBankaGetGetPathParameters,
  CariBankaGrupluListeGet200Four,
  CariBankaGrupluListeGet200One,
  CariBankaGrupluListeGet200Three,
  CariBankaGrupluListeGet200Two,
  CariBankaGrupluListeGetParams,
  CariBankaListeEsnekGet200Four,
  CariBankaListeEsnekGet200One,
  CariBankaListeEsnekGet200Three,
  CariBankaListeEsnekGet200Two,
  CariBankaListeEsnekGetParams,
  CariBankaListeGetGetParams,
  CariBankaNotEklePostPathParameters,
  CariBankaNotSilDeletePathParameters,
  CariBankaNotlarGetParams,
  CariBankaNotlarGetPathParameters,
  CariBankaOnayDurumuGetPathParameters,
  CariBankaOnaylaPostParams,
  CariBankaPutPutPathParameters,
  CariBankaReddetPostParams,
  LinqFilteringAdvancedFilterRequestBody
} from '../../models';

import { customInstance } from '../../axios';



  export const getCariBanka = () => {
/**
 * @summary Belirtilen ID'ye sahip kaydı getirir. Kart detay bilgilerini döndürür.
INTENT: kaydı getir, detayı göster, bilgileri al, ID ile sorgula, kartı görüntüle
KULLANIM: Kart görüntüleme, düzenleme öncesi mevcut bilgileri alma.
 */
const CariBanka_GetGet = (
    { id }: CariBankaGetGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerCariBankaKayitSadeListeModel>(
      {url: `/api/CariBanka/${id}`, method: 'GET'
    },
      );
    }
  const CariBanka_PutPut = (
    { id }: CariBankaPutPutPathParameters,
    aaroModullerCariBankaKayitSadeKayitModelBody: AaroModullerCariBankaKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerCariBankaKayitSadeListeModel>(
      {url: `/api/CariBanka/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerCariBankaKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı siler veya pasifleştirir.
INTENT: sil, kaldır, pasifleştir, devre dışı bırak, kapat
KULLANIM: Artık kullanılmayan kayıtları sistemden kaldırma veya pasifleştirme.
IS_KURALLARI: Hareketi veya bağlı kaydı bulunan kartlar tamamen silinemez; yalnızca pasifleştirilebilir.
 */
const CariBanka_DeleteDelete = (
    { id }: CariBankaDeleteDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerCariBankaKayitSadeListeModel>(
      {url: `/api/CariBanka/${id}`, method: 'DELETE'
    },
      );
    }
  const CariBanka_ListeGetGet = (
    params?: CariBankaListeGetGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariBankaKayitSadeListeModel>(
      {url: `/api/CariBanka`, method: 'GET',
        params
    },
      );
    }
  const CariBanka_PostPost = (
    aaroModullerCariBankaKayitSadeKayitModelBody: AaroModullerCariBankaKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerCariBankaKayitSadeListeModel>(
      {url: `/api/CariBanka`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerCariBankaKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı onaylar. Onay akışındaki kaydı bir sonraki aşamaya taşır.
INTENT: onayla, kabul et, akışı ilerlet, onay ver
IS_KURALLARI: Kayıt onay akışında olmalı ve onaylanabilir durumda olmalı.
 */
const CariBanka_OnaylaPost = (
    params?: CariBankaOnaylaPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerCariBankaKayitSadeKayitModel>(
      {url: `/api/CariBanka/Onayla`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydı reddeder. Onay akışındaki kaydı geri gönderir.
INTENT: reddet, geri gönder, onaylama, iade et
IS_KURALLARI: Kayıt onay akışında ve reddedilebilir durumda olmalı.
 */
const CariBanka_ReddetPost = (
    params?: CariBankaReddetPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerCariBankaKayitSadeKayitModel>(
      {url: `/api/CariBanka/Reddet`, method: 'POST',
        params
    },
      );
    }
  /**
 * FILTRE_FORMATI: {Alan}:{Operator}:{Deger}:{Mantik}
Operatörler:
  eq  — Eşit           örn: Durum:eq:True
  ct  — İçerir         örn: Ad:ct:Market
  sw  — İle başlar     örn: Kod:sw:A
  gt  — Büyüktür       örn: Bakiye:gt:5000
  in  — Listede        örn: GrupID:in:1|5|8   (değerler | ile ayrılır)
  lk  — Like (%)       örn: Adres:lk:İstanbul
Birden fazla filtre virgülle birleştirilir:
  örn: Sehir:eq:Istanbul:and,Bakiye:gt:5000:and,GrupID:in:1|5|8
            
SIRALAMA_FORMATI: {Alan}:{Yon}
  örn: Ad:asc,Bakiye:desc    (Varsayılan: Kod alanı artan)
            
SUTUN_SECIMI: Sadece ihtiyaç duyulan alanlar belirtilir; performansı artırır.
  örn: ID,Kod,Ad,Bakiye
 * @summary Dinamik ve esnek sorgulama altyapısı ile kayıt listesini getirir.
Kolon seçimi, karmaşık filtreler ve sıralama üzerinde tam kontrol sağlar.
INTENT: esnek sorgula, dinamik filtrele, özel alanları getir, karmaşık filtre uygula
KULLANIM: İnsan geliştirici ve harici entegrasyonlar için tasarlanmıştır.
          MCP ve AI çağrıları için POST /Liste tercih edilmelidir.
MCP_NOT: Bu endpoint MCP/AI çağrıları için önerilmez. 
         Tip güvensiz string filtreler hata üretme riski taşır.
         Karmaşık filtreler için POST /Liste kullanılır.
 */
const CariBanka_ListeEsnekGet = (
    params?: CariBankaListeEsnekGetParams,
 ) => {
      return customInstance<CariBankaListeEsnekGet200One | CariBankaListeEsnekGet200Two | CariBankaListeEsnekGet200Three | CariBankaListeEsnekGet200Four>(
      {url: `/api/CariBanka/Liste`, method: 'GET',
        params
    },
      );
    }
  const CariBanka_ListePostPost = (
    linqFilteringAdvancedFilterRequestBody: LinqFilteringAdvancedFilterRequestBody,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariBankaKayitSadeListeModel>(
      {url: `/api/CariBanka/Liste`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: linqFilteringAdvancedFilterRequestBody
    },
      );
    }
  /**
 * @summary Kayıtları belirtilen alanlara göre gruplayarak özet liste döndürür.
INTENT: grupla, özet al, gruplara göre say, gruplama raporu
KULLANIM: Gruplama bazlı raporlama ve istatistik sorgularında kullanılır.
YETKI: Hareket özeti admini gerektirir.
 */
const CariBanka_GrupluListeGet = (
    params?: CariBankaGrupluListeGetParams,
 ) => {
      return customInstance<CariBankaGrupluListeGet200One | CariBankaGrupluListeGet200Two | CariBankaGrupluListeGet200Three | CariBankaGrupluListeGet200Four>(
      {url: `/api/CariBanka/GrupluListe`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydın onay durumunu ve onay geçmişini getirir.
INTENT: onay durumu nedir, onaylandı mı, hangi aşamada, onay sorgula
KULLANIM: Onay akışı takibi, kaydın hangi adımda olduğunu öğrenme.
 */
const CariBanka_OnayDurumuGet = (
    { id }: CariBankaOnayDurumuGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi>(
      {url: `/api/CariBanka/${id}/OnayDurumu`, method: 'GET'
    },
      );
    }
  /**
 * @summary Belirtilen kaydın değişiklik geçmişini getirir. Kim, ne zaman, ne değiştirdi bilgisi.
INTENT: değişiklik geçmişi, kim değiştirdi, ne zaman değişti, log, audit, tarihçe
KULLANIM: Kayıt üzerinde yapılan tüm değişikliklerin izlenmesi ve denetimi.
 */
const CariBanka_DegisiklikGecmisiGet = (
    { id }: CariBankaDegisiklikGecmisiGetPathParameters,
    params?: CariBankaDegisiklikGecmisiGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi>(
      {url: `/api/CariBanka/${id}/DegisiklikGecmisi`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait belge listesini getirir.
INTENT: belgeleri getir, dosyaları listele, ekleri göster, dokümanlar
KULLANIM: Kayda eklenmiş sözleşme, fatura, resim gibi belgelerin listelenmesi.
 */
const CariBanka_BelgelerGet = (
    { id }: CariBankaBelgelerGetPathParameters,
    params?: CariBankaBelgelerGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi>(
      {url: `/api/CariBanka/${id}/Belgeler`, method: 'GET',
        params
    },
      );
    }
  const CariBanka_BelgeEklePost = (
    { id }: CariBankaBelgeEklePostPathParameters,
    params?: CariBankaBelgeEklePostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/CariBanka/${id}/BelgeEkle`, method: 'POST',
        params
    },
      );
    }
  const CariBanka_BelgeSilDelete = (
    { id, belgeID }: CariBankaBelgeSilDeletePathParameters,
    params?: CariBankaBelgeSilDeleteParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/CariBanka/${id}/BelgeSil/${belgeID}`, method: 'DELETE',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait notları getirir.
INTENT: notları getir, açıklamaları göster, yorumları listele, notlar neler
KULLANIM: Kayda eklenen serbest metin notların, hatırlatmaların veya açıklamaların listelenmesi.
 */
const CariBanka_NotlarGet = (
    { id }: CariBankaNotlarGetPathParameters,
    params?: CariBankaNotlarGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi>(
      {url: `/api/CariBanka/${id}/Notlar`, method: 'GET',
        params
    },
      );
    }
  const CariBanka_NotEklePost = (
    { id }: CariBankaNotEklePostPathParameters,
    aaroModullerNotlarKayitSadeKayitModelBody: AaroModullerNotlarKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/CariBanka/${id}/NotEkle`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerNotlarKayitSadeKayitModelBody
    },
      );
    }
  const CariBanka_NotSilDelete = (
    { id, notID }: CariBankaNotSilDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/CariBanka/${id}/NotSil/${notID}`, method: 'DELETE'
    },
      );
    }
  return {CariBanka_GetGet,CariBanka_PutPut,CariBanka_DeleteDelete,CariBanka_ListeGetGet,CariBanka_PostPost,CariBanka_OnaylaPost,CariBanka_ReddetPost,CariBanka_ListeEsnekGet,CariBanka_ListePostPost,CariBanka_GrupluListeGet,CariBanka_OnayDurumuGet,CariBanka_DegisiklikGecmisiGet,CariBanka_BelgelerGet,CariBanka_BelgeEklePost,CariBanka_BelgeSilDelete,CariBanka_NotlarGet,CariBanka_NotEklePost,CariBanka_NotSilDelete}};
export type CariBankaGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariBanka>['CariBanka_GetGet']>>>
export type CariBankaPutPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariBanka>['CariBanka_PutPut']>>>
export type CariBankaDeleteDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariBanka>['CariBanka_DeleteDelete']>>>
export type CariBankaListeGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariBanka>['CariBanka_ListeGetGet']>>>
export type CariBankaPostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariBanka>['CariBanka_PostPost']>>>
export type CariBankaOnaylaPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariBanka>['CariBanka_OnaylaPost']>>>
export type CariBankaReddetPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariBanka>['CariBanka_ReddetPost']>>>
export type CariBankaListeEsnekGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariBanka>['CariBanka_ListeEsnekGet']>>>
export type CariBankaListePostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariBanka>['CariBanka_ListePostPost']>>>
export type CariBankaGrupluListeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariBanka>['CariBanka_GrupluListeGet']>>>
export type CariBankaOnayDurumuGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariBanka>['CariBanka_OnayDurumuGet']>>>
export type CariBankaDegisiklikGecmisiGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariBanka>['CariBanka_DegisiklikGecmisiGet']>>>
export type CariBankaBelgelerGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariBanka>['CariBanka_BelgelerGet']>>>
export type CariBankaBelgeEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariBanka>['CariBanka_BelgeEklePost']>>>
export type CariBankaBelgeSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariBanka>['CariBanka_BelgeSilDelete']>>>
export type CariBankaNotlarGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariBanka>['CariBanka_NotlarGet']>>>
export type CariBankaNotEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariBanka>['CariBanka_NotEklePost']>>>
export type CariBankaNotSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariBanka>['CariBanka_NotSilDelete']>>>
