/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type {
  AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel,
  AaroKayitSonucAaroModullerKullanicilarKayitSadeKayitModel,
  AaroKayitSonucAaroModullerKullanicilarKayitSadeListeModel,
  AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel,
  AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerKullanicilarKayitSadeListeModel,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi,
  AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi,
  AaroModullerKullanicilarKayitSadeKayitModelBody,
  AaroModullerNotlarKayitSadeKayitModelBody,
  KullanicilarBelgeEklePostParams,
  KullanicilarBelgeEklePostPathParameters,
  KullanicilarBelgeSilDeleteParams,
  KullanicilarBelgeSilDeletePathParameters,
  KullanicilarBelgelerGetParams,
  KullanicilarBelgelerGetPathParameters,
  KullanicilarDegisiklikGecmisiGetParams,
  KullanicilarDegisiklikGecmisiGetPathParameters,
  KullanicilarDeleteDeletePathParameters,
  KullanicilarGetGetPathParameters,
  KullanicilarGrupluListeGet200Four,
  KullanicilarGrupluListeGet200One,
  KullanicilarGrupluListeGet200Three,
  KullanicilarGrupluListeGet200Two,
  KullanicilarGrupluListeGetParams,
  KullanicilarListeEsnekGet200Four,
  KullanicilarListeEsnekGet200One,
  KullanicilarListeEsnekGet200Three,
  KullanicilarListeEsnekGet200Two,
  KullanicilarListeEsnekGetParams,
  KullanicilarListeGetGetParams,
  KullanicilarNotEklePostPathParameters,
  KullanicilarNotSilDeletePathParameters,
  KullanicilarNotlarGetParams,
  KullanicilarNotlarGetPathParameters,
  KullanicilarOnayDurumuGetPathParameters,
  KullanicilarOnaylaPostParams,
  KullanicilarPutPutPathParameters,
  KullanicilarReddetPostParams,
  LinqFilteringAdvancedFilterRequestBody
} from '../../models';

import { customInstance } from '../../axios';



  export const getKullanicilar = () => {
/**
 * @summary Belirtilen ID'ye sahip kaydı getirir. Kart detay bilgilerini döndürür.
INTENT: kaydı getir, detayı göster, bilgileri al, ID ile sorgula, kartı görüntüle
KULLANIM: Kart görüntüleme, düzenleme öncesi mevcut bilgileri alma.
 */
const Kullanicilar_GetGet = (
    { id }: KullanicilarGetGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerKullanicilarKayitSadeListeModel>(
      {url: `/api/Kullanicilar/${id}`, method: 'GET'
    },
      );
    }
  const Kullanicilar_PutPut = (
    { id }: KullanicilarPutPutPathParameters,
    aaroModullerKullanicilarKayitSadeKayitModelBody: AaroModullerKullanicilarKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerKullanicilarKayitSadeListeModel>(
      {url: `/api/Kullanicilar/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerKullanicilarKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı siler veya pasifleştirir.
INTENT: sil, kaldır, pasifleştir, devre dışı bırak, kapat
KULLANIM: Artık kullanılmayan kayıtları sistemden kaldırma veya pasifleştirme.
IS_KURALLARI: Hareketi veya bağlı kaydı bulunan kartlar tamamen silinemez; yalnızca pasifleştirilebilir.
 */
const Kullanicilar_DeleteDelete = (
    { id }: KullanicilarDeleteDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerKullanicilarKayitSadeListeModel>(
      {url: `/api/Kullanicilar/${id}`, method: 'DELETE'
    },
      );
    }
  const Kullanicilar_ListeGetGet = (
    params?: KullanicilarListeGetGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerKullanicilarKayitSadeListeModel>(
      {url: `/api/Kullanicilar`, method: 'GET',
        params
    },
      );
    }
  const Kullanicilar_PostPost = (
    aaroModullerKullanicilarKayitSadeKayitModelBody: AaroModullerKullanicilarKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerKullanicilarKayitSadeListeModel>(
      {url: `/api/Kullanicilar`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerKullanicilarKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı onaylar. Onay akışındaki kaydı bir sonraki aşamaya taşır.
INTENT: onayla, kabul et, akışı ilerlet, onay ver
IS_KURALLARI: Kayıt onay akışında olmalı ve onaylanabilir durumda olmalı.
 */
const Kullanicilar_OnaylaPost = (
    params?: KullanicilarOnaylaPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerKullanicilarKayitSadeKayitModel>(
      {url: `/api/Kullanicilar/Onayla`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydı reddeder. Onay akışındaki kaydı geri gönderir.
INTENT: reddet, geri gönder, onaylama, iade et
IS_KURALLARI: Kayıt onay akışında ve reddedilebilir durumda olmalı.
 */
const Kullanicilar_ReddetPost = (
    params?: KullanicilarReddetPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerKullanicilarKayitSadeKayitModel>(
      {url: `/api/Kullanicilar/Reddet`, method: 'POST',
        params
    },
      );
    }
  /**
 * FILTRE_FORMATI: {Alan}:{Operator}:{Deger}:{Mantik}
Operatörler:
  eq  — Eşit           örn: Durum:eq:True
  ct  — İçerir         örn: Ad:ct:Market
  sw  — İle başlar     örn: Kod:sw:A
  gt  — Büyüktür       örn: Bakiye:gt:5000
  in  — Listede        örn: GrupID:in:1|5|8   (değerler | ile ayrılır)
  lk  — Like (%)       örn: Adres:lk:İstanbul
Birden fazla filtre virgülle birleştirilir:
  örn: Sehir:eq:Istanbul:and,Bakiye:gt:5000:and,GrupID:in:1|5|8
            
SIRALAMA_FORMATI: {Alan}:{Yon}
  örn: Ad:asc,Bakiye:desc    (Varsayılan: Kod alanı artan)
            
SUTUN_SECIMI: Sadece ihtiyaç duyulan alanlar belirtilir; performansı artırır.
  örn: ID,Kod,Ad,Bakiye
 * @summary Dinamik ve esnek sorgulama altyapısı ile kayıt listesini getirir.
Kolon seçimi, karmaşık filtreler ve sıralama üzerinde tam kontrol sağlar.
INTENT: esnek sorgula, dinamik filtrele, özel alanları getir, karmaşık filtre uygula
KULLANIM: İnsan geliştirici ve harici entegrasyonlar için tasarlanmıştır.
          MCP ve AI çağrıları için POST /Liste tercih edilmelidir.
MCP_NOT: Bu endpoint MCP/AI çağrıları için önerilmez. 
         Tip güvensiz string filtreler hata üretme riski taşır.
         Karmaşık filtreler için POST /Liste kullanılır.
 */
const Kullanicilar_ListeEsnekGet = (
    params?: KullanicilarListeEsnekGetParams,
 ) => {
      return customInstance<KullanicilarListeEsnekGet200One | KullanicilarListeEsnekGet200Two | KullanicilarListeEsnekGet200Three | KullanicilarListeEsnekGet200Four>(
      {url: `/api/Kullanicilar/Liste`, method: 'GET',
        params
    },
      );
    }
  const Kullanicilar_ListePostPost = (
    linqFilteringAdvancedFilterRequestBody: LinqFilteringAdvancedFilterRequestBody,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerKullanicilarKayitSadeListeModel>(
      {url: `/api/Kullanicilar/Liste`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: linqFilteringAdvancedFilterRequestBody
    },
      );
    }
  /**
 * @summary Kayıtları belirtilen alanlara göre gruplayarak özet liste döndürür.
INTENT: grupla, özet al, gruplara göre say, gruplama raporu
KULLANIM: Gruplama bazlı raporlama ve istatistik sorgularında kullanılır.
YETKI: Hareket özeti admini gerektirir.
 */
const Kullanicilar_GrupluListeGet = (
    params?: KullanicilarGrupluListeGetParams,
 ) => {
      return customInstance<KullanicilarGrupluListeGet200One | KullanicilarGrupluListeGet200Two | KullanicilarGrupluListeGet200Three | KullanicilarGrupluListeGet200Four>(
      {url: `/api/Kullanicilar/GrupluListe`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydın onay durumunu ve onay geçmişini getirir.
INTENT: onay durumu nedir, onaylandı mı, hangi aşamada, onay sorgula
KULLANIM: Onay akışı takibi, kaydın hangi adımda olduğunu öğrenme.
 */
const Kullanicilar_OnayDurumuGet = (
    { id }: KullanicilarOnayDurumuGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi>(
      {url: `/api/Kullanicilar/${id}/OnayDurumu`, method: 'GET'
    },
      );
    }
  /**
 * @summary Belirtilen kaydın değişiklik geçmişini getirir. Kim, ne zaman, ne değiştirdi bilgisi.
INTENT: değişiklik geçmişi, kim değiştirdi, ne zaman değişti, log, audit, tarihçe
KULLANIM: Kayıt üzerinde yapılan tüm değişikliklerin izlenmesi ve denetimi.
 */
const Kullanicilar_DegisiklikGecmisiGet = (
    { id }: KullanicilarDegisiklikGecmisiGetPathParameters,
    params?: KullanicilarDegisiklikGecmisiGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi>(
      {url: `/api/Kullanicilar/${id}/DegisiklikGecmisi`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait belge listesini getirir.
INTENT: belgeleri getir, dosyaları listele, ekleri göster, dokümanlar
KULLANIM: Kayda eklenmiş sözleşme, fatura, resim gibi belgelerin listelenmesi.
 */
const Kullanicilar_BelgelerGet = (
    { id }: KullanicilarBelgelerGetPathParameters,
    params?: KullanicilarBelgelerGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi>(
      {url: `/api/Kullanicilar/${id}/Belgeler`, method: 'GET',
        params
    },
      );
    }
  const Kullanicilar_BelgeEklePost = (
    { id }: KullanicilarBelgeEklePostPathParameters,
    params?: KullanicilarBelgeEklePostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/Kullanicilar/${id}/BelgeEkle`, method: 'POST',
        params
    },
      );
    }
  const Kullanicilar_BelgeSilDelete = (
    { id, belgeID }: KullanicilarBelgeSilDeletePathParameters,
    params?: KullanicilarBelgeSilDeleteParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/Kullanicilar/${id}/BelgeSil/${belgeID}`, method: 'DELETE',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait notları getirir.
INTENT: notları getir, açıklamaları göster, yorumları listele, notlar neler
KULLANIM: Kayda eklenen serbest metin notların, hatırlatmaların veya açıklamaların listelenmesi.
 */
const Kullanicilar_NotlarGet = (
    { id }: KullanicilarNotlarGetPathParameters,
    params?: KullanicilarNotlarGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi>(
      {url: `/api/Kullanicilar/${id}/Notlar`, method: 'GET',
        params
    },
      );
    }
  const Kullanicilar_NotEklePost = (
    { id }: KullanicilarNotEklePostPathParameters,
    aaroModullerNotlarKayitSadeKayitModelBody: AaroModullerNotlarKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/Kullanicilar/${id}/NotEkle`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerNotlarKayitSadeKayitModelBody
    },
      );
    }
  const Kullanicilar_NotSilDelete = (
    { id, notID }: KullanicilarNotSilDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/Kullanicilar/${id}/NotSil/${notID}`, method: 'DELETE'
    },
      );
    }
  return {Kullanicilar_GetGet,Kullanicilar_PutPut,Kullanicilar_DeleteDelete,Kullanicilar_ListeGetGet,Kullanicilar_PostPost,Kullanicilar_OnaylaPost,Kullanicilar_ReddetPost,Kullanicilar_ListeEsnekGet,Kullanicilar_ListePostPost,Kullanicilar_GrupluListeGet,Kullanicilar_OnayDurumuGet,Kullanicilar_DegisiklikGecmisiGet,Kullanicilar_BelgelerGet,Kullanicilar_BelgeEklePost,Kullanicilar_BelgeSilDelete,Kullanicilar_NotlarGet,Kullanicilar_NotEklePost,Kullanicilar_NotSilDelete}};
export type KullanicilarGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKullanicilar>['Kullanicilar_GetGet']>>>
export type KullanicilarPutPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKullanicilar>['Kullanicilar_PutPut']>>>
export type KullanicilarDeleteDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKullanicilar>['Kullanicilar_DeleteDelete']>>>
export type KullanicilarListeGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKullanicilar>['Kullanicilar_ListeGetGet']>>>
export type KullanicilarPostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKullanicilar>['Kullanicilar_PostPost']>>>
export type KullanicilarOnaylaPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKullanicilar>['Kullanicilar_OnaylaPost']>>>
export type KullanicilarReddetPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKullanicilar>['Kullanicilar_ReddetPost']>>>
export type KullanicilarListeEsnekGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKullanicilar>['Kullanicilar_ListeEsnekGet']>>>
export type KullanicilarListePostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKullanicilar>['Kullanicilar_ListePostPost']>>>
export type KullanicilarGrupluListeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKullanicilar>['Kullanicilar_GrupluListeGet']>>>
export type KullanicilarOnayDurumuGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKullanicilar>['Kullanicilar_OnayDurumuGet']>>>
export type KullanicilarDegisiklikGecmisiGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKullanicilar>['Kullanicilar_DegisiklikGecmisiGet']>>>
export type KullanicilarBelgelerGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKullanicilar>['Kullanicilar_BelgelerGet']>>>
export type KullanicilarBelgeEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKullanicilar>['Kullanicilar_BelgeEklePost']>>>
export type KullanicilarBelgeSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKullanicilar>['Kullanicilar_BelgeSilDelete']>>>
export type KullanicilarNotlarGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKullanicilar>['Kullanicilar_NotlarGet']>>>
export type KullanicilarNotEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKullanicilar>['Kullanicilar_NotEklePost']>>>
export type KullanicilarNotSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getKullanicilar>['Kullanicilar_NotSilDelete']>>>
