/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type {
  AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel,
  AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel,
  AaroKayitSonucAaroModullerStokSayimKayitSadeKayitModel,
  AaroKayitSonucAaroModullerStokSayimKayitSadeListeModel,
  AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokSayimKayitSadeListeModel,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi,
  AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi,
  AaroModullerNotlarKayitSadeKayitModelBody,
  AaroModullerStokSayimKayitSadeKayitModelBody,
  LinqFilteringAdvancedFilterRequestBody,
  StokSayimBelgeEklePostParams,
  StokSayimBelgeEklePostPathParameters,
  StokSayimBelgeSilDeleteParams,
  StokSayimBelgeSilDeletePathParameters,
  StokSayimBelgelerGetParams,
  StokSayimBelgelerGetPathParameters,
  StokSayimDegisiklikGecmisiGetParams,
  StokSayimDegisiklikGecmisiGetPathParameters,
  StokSayimDeleteDeletePathParameters,
  StokSayimGetGetPathParameters,
  StokSayimGrupluListeGet200Four,
  StokSayimGrupluListeGet200One,
  StokSayimGrupluListeGet200Three,
  StokSayimGrupluListeGet200Two,
  StokSayimGrupluListeGetParams,
  StokSayimListeEsnekGet200Four,
  StokSayimListeEsnekGet200One,
  StokSayimListeEsnekGet200Three,
  StokSayimListeEsnekGet200Two,
  StokSayimListeEsnekGetParams,
  StokSayimListeGetGetParams,
  StokSayimNotEklePostPathParameters,
  StokSayimNotSilDeletePathParameters,
  StokSayimNotlarGetParams,
  StokSayimNotlarGetPathParameters,
  StokSayimOnayDurumuGetPathParameters,
  StokSayimOnaylaPostParams,
  StokSayimPutPutPathParameters,
  StokSayimReddetPostParams
} from '../../models';

import { customInstance } from '../../axios';



  export const getStokSayim = () => {
/**
 * @summary Belirtilen ID'ye sahip kaydı getirir. Kart detay bilgilerini döndürür.
INTENT: kaydı getir, detayı göster, bilgileri al, ID ile sorgula, kartı görüntüle
KULLANIM: Kart görüntüleme, düzenleme öncesi mevcut bilgileri alma.
 */
const StokSayim_GetGet = (
    { id }: StokSayimGetGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokSayimKayitSadeListeModel>(
      {url: `/api/StokSayim/${id}`, method: 'GET'
    },
      );
    }
  const StokSayim_PutPut = (
    { id }: StokSayimPutPutPathParameters,
    aaroModullerStokSayimKayitSadeKayitModelBody: AaroModullerStokSayimKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokSayimKayitSadeListeModel>(
      {url: `/api/StokSayim/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerStokSayimKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı siler veya pasifleştirir.
INTENT: sil, kaldır, pasifleştir, devre dışı bırak, kapat
KULLANIM: Artık kullanılmayan kayıtları sistemden kaldırma veya pasifleştirme.
IS_KURALLARI: Hareketi veya bağlı kaydı bulunan kartlar tamamen silinemez; yalnızca pasifleştirilebilir.
 */
const StokSayim_DeleteDelete = (
    { id }: StokSayimDeleteDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokSayimKayitSadeListeModel>(
      {url: `/api/StokSayim/${id}`, method: 'DELETE'
    },
      );
    }
  const StokSayim_ListeGetGet = (
    params?: StokSayimListeGetGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokSayimKayitSadeListeModel>(
      {url: `/api/StokSayim`, method: 'GET',
        params
    },
      );
    }
  const StokSayim_PostPost = (
    aaroModullerStokSayimKayitSadeKayitModelBody: AaroModullerStokSayimKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokSayimKayitSadeListeModel>(
      {url: `/api/StokSayim`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerStokSayimKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı onaylar. Onay akışındaki kaydı bir sonraki aşamaya taşır.
INTENT: onayla, kabul et, akışı ilerlet, onay ver
IS_KURALLARI: Kayıt onay akışında olmalı ve onaylanabilir durumda olmalı.
 */
const StokSayim_OnaylaPost = (
    params?: StokSayimOnaylaPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokSayimKayitSadeKayitModel>(
      {url: `/api/StokSayim/Onayla`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydı reddeder. Onay akışındaki kaydı geri gönderir.
INTENT: reddet, geri gönder, onaylama, iade et
IS_KURALLARI: Kayıt onay akışında ve reddedilebilir durumda olmalı.
 */
const StokSayim_ReddetPost = (
    params?: StokSayimReddetPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokSayimKayitSadeKayitModel>(
      {url: `/api/StokSayim/Reddet`, method: 'POST',
        params
    },
      );
    }
  /**
 * FILTRE_FORMATI: {Alan}:{Operator}:{Deger}:{Mantik}
Operatörler:
  eq  — Eşit           örn: Durum:eq:True
  ct  — İçerir         örn: Ad:ct:Market
  sw  — İle başlar     örn: Kod:sw:A
  gt  — Büyüktür       örn: Bakiye:gt:5000
  in  — Listede        örn: GrupID:in:1|5|8   (değerler | ile ayrılır)
  lk  — Like (%)       örn: Adres:lk:İstanbul
Birden fazla filtre virgülle birleştirilir:
  örn: Sehir:eq:Istanbul:and,Bakiye:gt:5000:and,GrupID:in:1|5|8
            
SIRALAMA_FORMATI: {Alan}:{Yon}
  örn: Ad:asc,Bakiye:desc    (Varsayılan: Kod alanı artan)
            
SUTUN_SECIMI: Sadece ihtiyaç duyulan alanlar belirtilir; performansı artırır.
  örn: ID,Kod,Ad,Bakiye
 * @summary Dinamik ve esnek sorgulama altyapısı ile kayıt listesini getirir.
Kolon seçimi, karmaşık filtreler ve sıralama üzerinde tam kontrol sağlar.
INTENT: esnek sorgula, dinamik filtrele, özel alanları getir, karmaşık filtre uygula
KULLANIM: İnsan geliştirici ve harici entegrasyonlar için tasarlanmıştır.
          MCP ve AI çağrıları için POST /Liste tercih edilmelidir.
MCP_NOT: Bu endpoint MCP/AI çağrıları için önerilmez. 
         Tip güvensiz string filtreler hata üretme riski taşır.
         Karmaşık filtreler için POST /Liste kullanılır.
 */
const StokSayim_ListeEsnekGet = (
    params?: StokSayimListeEsnekGetParams,
 ) => {
      return customInstance<StokSayimListeEsnekGet200One | StokSayimListeEsnekGet200Two | StokSayimListeEsnekGet200Three | StokSayimListeEsnekGet200Four>(
      {url: `/api/StokSayim/Liste`, method: 'GET',
        params
    },
      );
    }
  const StokSayim_ListePostPost = (
    linqFilteringAdvancedFilterRequestBody: LinqFilteringAdvancedFilterRequestBody,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokSayimKayitSadeListeModel>(
      {url: `/api/StokSayim/Liste`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: linqFilteringAdvancedFilterRequestBody
    },
      );
    }
  /**
 * @summary Kayıtları belirtilen alanlara göre gruplayarak özet liste döndürür.
INTENT: grupla, özet al, gruplara göre say, gruplama raporu
KULLANIM: Gruplama bazlı raporlama ve istatistik sorgularında kullanılır.
YETKI: Hareket özeti admini gerektirir.
 */
const StokSayim_GrupluListeGet = (
    params?: StokSayimGrupluListeGetParams,
 ) => {
      return customInstance<StokSayimGrupluListeGet200One | StokSayimGrupluListeGet200Two | StokSayimGrupluListeGet200Three | StokSayimGrupluListeGet200Four>(
      {url: `/api/StokSayim/GrupluListe`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydın onay durumunu ve onay geçmişini getirir.
INTENT: onay durumu nedir, onaylandı mı, hangi aşamada, onay sorgula
KULLANIM: Onay akışı takibi, kaydın hangi adımda olduğunu öğrenme.
 */
const StokSayim_OnayDurumuGet = (
    { id }: StokSayimOnayDurumuGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi>(
      {url: `/api/StokSayim/${id}/OnayDurumu`, method: 'GET'
    },
      );
    }
  /**
 * @summary Belirtilen kaydın değişiklik geçmişini getirir. Kim, ne zaman, ne değiştirdi bilgisi.
INTENT: değişiklik geçmişi, kim değiştirdi, ne zaman değişti, log, audit, tarihçe
KULLANIM: Kayıt üzerinde yapılan tüm değişikliklerin izlenmesi ve denetimi.
 */
const StokSayim_DegisiklikGecmisiGet = (
    { id }: StokSayimDegisiklikGecmisiGetPathParameters,
    params?: StokSayimDegisiklikGecmisiGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi>(
      {url: `/api/StokSayim/${id}/DegisiklikGecmisi`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait belge listesini getirir.
INTENT: belgeleri getir, dosyaları listele, ekleri göster, dokümanlar
KULLANIM: Kayda eklenmiş sözleşme, fatura, resim gibi belgelerin listelenmesi.
 */
const StokSayim_BelgelerGet = (
    { id }: StokSayimBelgelerGetPathParameters,
    params?: StokSayimBelgelerGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi>(
      {url: `/api/StokSayim/${id}/Belgeler`, method: 'GET',
        params
    },
      );
    }
  const StokSayim_BelgeEklePost = (
    { id }: StokSayimBelgeEklePostPathParameters,
    params?: StokSayimBelgeEklePostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/StokSayim/${id}/BelgeEkle`, method: 'POST',
        params
    },
      );
    }
  const StokSayim_BelgeSilDelete = (
    { id, belgeID }: StokSayimBelgeSilDeletePathParameters,
    params?: StokSayimBelgeSilDeleteParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/StokSayim/${id}/BelgeSil/${belgeID}`, method: 'DELETE',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait notları getirir.
INTENT: notları getir, açıklamaları göster, yorumları listele, notlar neler
KULLANIM: Kayda eklenen serbest metin notların, hatırlatmaların veya açıklamaların listelenmesi.
 */
const StokSayim_NotlarGet = (
    { id }: StokSayimNotlarGetPathParameters,
    params?: StokSayimNotlarGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi>(
      {url: `/api/StokSayim/${id}/Notlar`, method: 'GET',
        params
    },
      );
    }
  const StokSayim_NotEklePost = (
    { id }: StokSayimNotEklePostPathParameters,
    aaroModullerNotlarKayitSadeKayitModelBody: AaroModullerNotlarKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/StokSayim/${id}/NotEkle`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerNotlarKayitSadeKayitModelBody
    },
      );
    }
  const StokSayim_NotSilDelete = (
    { id, notID }: StokSayimNotSilDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/StokSayim/${id}/NotSil/${notID}`, method: 'DELETE'
    },
      );
    }
  return {StokSayim_GetGet,StokSayim_PutPut,StokSayim_DeleteDelete,StokSayim_ListeGetGet,StokSayim_PostPost,StokSayim_OnaylaPost,StokSayim_ReddetPost,StokSayim_ListeEsnekGet,StokSayim_ListePostPost,StokSayim_GrupluListeGet,StokSayim_OnayDurumuGet,StokSayim_DegisiklikGecmisiGet,StokSayim_BelgelerGet,StokSayim_BelgeEklePost,StokSayim_BelgeSilDelete,StokSayim_NotlarGet,StokSayim_NotEklePost,StokSayim_NotSilDelete}};
export type StokSayimGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStokSayim>['StokSayim_GetGet']>>>
export type StokSayimPutPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStokSayim>['StokSayim_PutPut']>>>
export type StokSayimDeleteDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStokSayim>['StokSayim_DeleteDelete']>>>
export type StokSayimListeGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStokSayim>['StokSayim_ListeGetGet']>>>
export type StokSayimPostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStokSayim>['StokSayim_PostPost']>>>
export type StokSayimOnaylaPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStokSayim>['StokSayim_OnaylaPost']>>>
export type StokSayimReddetPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStokSayim>['StokSayim_ReddetPost']>>>
export type StokSayimListeEsnekGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStokSayim>['StokSayim_ListeEsnekGet']>>>
export type StokSayimListePostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStokSayim>['StokSayim_ListePostPost']>>>
export type StokSayimGrupluListeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStokSayim>['StokSayim_GrupluListeGet']>>>
export type StokSayimOnayDurumuGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStokSayim>['StokSayim_OnayDurumuGet']>>>
export type StokSayimDegisiklikGecmisiGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStokSayim>['StokSayim_DegisiklikGecmisiGet']>>>
export type StokSayimBelgelerGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStokSayim>['StokSayim_BelgelerGet']>>>
export type StokSayimBelgeEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStokSayim>['StokSayim_BelgeEklePost']>>>
export type StokSayimBelgeSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStokSayim>['StokSayim_BelgeSilDelete']>>>
export type StokSayimNotlarGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStokSayim>['StokSayim_NotlarGet']>>>
export type StokSayimNotEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStokSayim>['StokSayim_NotEklePost']>>>
export type StokSayimNotSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStokSayim>['StokSayim_NotSilDelete']>>>
