/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type {
  AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisIadeFaturasiListeListeModel,
  SatisIadeFaturasiListeDetayliListeGetParams
} from '../../models';

import { customInstance } from '../../axios';



  export const getSatisIadeFaturasiListe = () => {
/**
 * @summary Filtrelenmiş satış iade faturası listesini getirir. Fatura bazında finansal özet ve yasal statü bilgileri sunar.
Alternatif İsimler: SalesReturnMasterList, CreditNoteQuery, SatisIadeFisSorgulama, GetSalesReturns
Kullanım: İade süreçlerinin genel takibi, müşteriye sağlanan iade kredilerinin analizi ve muhasebe kayıtlarının kontrolü.
MCP Kullanımı: Kullanıcının "Bu hafta ne kadarlık satış iadesi aldık?", "X müşterisine ait iade faturaları neler?", "İade faturalarının toplam tutarı" gibi fiş bazlı soruları için ana kaynaktır.
 */
const SatisIadeFaturasiListe_DetayliListeGet = (
    params?: SatisIadeFaturasiListeDetayliListeGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisIadeFaturasiListeListeModel>(
      {url: `/api/SatisIadeFaturasiListe`, method: 'GET',
        params
    },
      );
    }
  return {SatisIadeFaturasiListe_DetayliListeGet}};
export type SatisIadeFaturasiListeDetayliListeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSatisIadeFaturasiListe>['SatisIadeFaturasiListe_DetayliListeGet']>>>
