/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type {
  AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel,
  AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel,
  AaroKayitSonucAaroModullerNotlarKayitSadeListeModel,
  AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerNotlarKayitSadeListeModel,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi,
  AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi,
  AaroModullerNotlarKayitSadeKayitModelBody,
  LinqFilteringAdvancedFilterRequestBody,
  NotlarBelgeEklePostParams,
  NotlarBelgeEklePostPathParameters,
  NotlarBelgeSilDeleteParams,
  NotlarBelgeSilDeletePathParameters,
  NotlarBelgelerGetParams,
  NotlarBelgelerGetPathParameters,
  NotlarDegisiklikGecmisiGetParams,
  NotlarDegisiklikGecmisiGetPathParameters,
  NotlarDeleteDeletePathParameters,
  NotlarGetGetPathParameters,
  NotlarGrupluListeGet200Four,
  NotlarGrupluListeGet200One,
  NotlarGrupluListeGet200Three,
  NotlarGrupluListeGet200Two,
  NotlarGrupluListeGetParams,
  NotlarListeEsnekGet200Four,
  NotlarListeEsnekGet200One,
  NotlarListeEsnekGet200Three,
  NotlarListeEsnekGet200Two,
  NotlarListeEsnekGetParams,
  NotlarListeGetGetParams,
  NotlarNotEklePostPathParameters,
  NotlarNotSilDeletePathParameters,
  NotlarNotlarGetParams,
  NotlarNotlarGetPathParameters,
  NotlarOnayDurumuGetPathParameters,
  NotlarOnaylaPostParams,
  NotlarPutPutPathParameters,
  NotlarReddetPostParams
} from '../../models';

import { customInstance } from '../../axios';



  export const getNotlar = () => {
/**
 * @summary Belirtilen ID'ye sahip kaydı getirir. Kart detay bilgilerini döndürür.
INTENT: kaydı getir, detayı göster, bilgileri al, ID ile sorgula, kartı görüntüle
KULLANIM: Kart görüntüleme, düzenleme öncesi mevcut bilgileri alma.
 */
const Notlar_GetGet = (
    { id }: NotlarGetGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeListeModel>(
      {url: `/api/Notlar/${id}`, method: 'GET'
    },
      );
    }
  const Notlar_PutPut = (
    { id }: NotlarPutPutPathParameters,
    aaroModullerNotlarKayitSadeKayitModelBody: AaroModullerNotlarKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeListeModel>(
      {url: `/api/Notlar/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerNotlarKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı siler veya pasifleştirir.
INTENT: sil, kaldır, pasifleştir, devre dışı bırak, kapat
KULLANIM: Artık kullanılmayan kayıtları sistemden kaldırma veya pasifleştirme.
IS_KURALLARI: Hareketi veya bağlı kaydı bulunan kartlar tamamen silinemez; yalnızca pasifleştirilebilir.
 */
const Notlar_DeleteDelete = (
    { id }: NotlarDeleteDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeListeModel>(
      {url: `/api/Notlar/${id}`, method: 'DELETE'
    },
      );
    }
  const Notlar_ListeGetGet = (
    params?: NotlarListeGetGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerNotlarKayitSadeListeModel>(
      {url: `/api/Notlar`, method: 'GET',
        params
    },
      );
    }
  const Notlar_PostPost = (
    aaroModullerNotlarKayitSadeKayitModelBody: AaroModullerNotlarKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeListeModel>(
      {url: `/api/Notlar`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerNotlarKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı onaylar. Onay akışındaki kaydı bir sonraki aşamaya taşır.
INTENT: onayla, kabul et, akışı ilerlet, onay ver
IS_KURALLARI: Kayıt onay akışında olmalı ve onaylanabilir durumda olmalı.
 */
const Notlar_OnaylaPost = (
    params?: NotlarOnaylaPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/Notlar/Onayla`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydı reddeder. Onay akışındaki kaydı geri gönderir.
INTENT: reddet, geri gönder, onaylama, iade et
IS_KURALLARI: Kayıt onay akışında ve reddedilebilir durumda olmalı.
 */
const Notlar_ReddetPost = (
    params?: NotlarReddetPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/Notlar/Reddet`, method: 'POST',
        params
    },
      );
    }
  /**
 * FILTRE_FORMATI: {Alan}:{Operator}:{Deger}:{Mantik}
Operatörler:
  eq  — Eşit           örn: Durum:eq:True
  ct  — İçerir         örn: Ad:ct:Market
  sw  — İle başlar     örn: Kod:sw:A
  gt  — Büyüktür       örn: Bakiye:gt:5000
  in  — Listede        örn: GrupID:in:1|5|8   (değerler | ile ayrılır)
  lk  — Like (%)       örn: Adres:lk:İstanbul
Birden fazla filtre virgülle birleştirilir:
  örn: Sehir:eq:Istanbul:and,Bakiye:gt:5000:and,GrupID:in:1|5|8
            
SIRALAMA_FORMATI: {Alan}:{Yon}
  örn: Ad:asc,Bakiye:desc    (Varsayılan: Kod alanı artan)
            
SUTUN_SECIMI: Sadece ihtiyaç duyulan alanlar belirtilir; performansı artırır.
  örn: ID,Kod,Ad,Bakiye
 * @summary Dinamik ve esnek sorgulama altyapısı ile kayıt listesini getirir.
Kolon seçimi, karmaşık filtreler ve sıralama üzerinde tam kontrol sağlar.
INTENT: esnek sorgula, dinamik filtrele, özel alanları getir, karmaşık filtre uygula
KULLANIM: İnsan geliştirici ve harici entegrasyonlar için tasarlanmıştır.
          MCP ve AI çağrıları için POST /Liste tercih edilmelidir.
MCP_NOT: Bu endpoint MCP/AI çağrıları için önerilmez. 
         Tip güvensiz string filtreler hata üretme riski taşır.
         Karmaşık filtreler için POST /Liste kullanılır.
 */
const Notlar_ListeEsnekGet = (
    params?: NotlarListeEsnekGetParams,
 ) => {
      return customInstance<NotlarListeEsnekGet200One | NotlarListeEsnekGet200Two | NotlarListeEsnekGet200Three | NotlarListeEsnekGet200Four>(
      {url: `/api/Notlar/Liste`, method: 'GET',
        params
    },
      );
    }
  const Notlar_ListePostPost = (
    linqFilteringAdvancedFilterRequestBody: LinqFilteringAdvancedFilterRequestBody,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerNotlarKayitSadeListeModel>(
      {url: `/api/Notlar/Liste`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: linqFilteringAdvancedFilterRequestBody
    },
      );
    }
  /**
 * @summary Kayıtları belirtilen alanlara göre gruplayarak özet liste döndürür.
INTENT: grupla, özet al, gruplara göre say, gruplama raporu
KULLANIM: Gruplama bazlı raporlama ve istatistik sorgularında kullanılır.
YETKI: Hareket özeti admini gerektirir.
 */
const Notlar_GrupluListeGet = (
    params?: NotlarGrupluListeGetParams,
 ) => {
      return customInstance<NotlarGrupluListeGet200One | NotlarGrupluListeGet200Two | NotlarGrupluListeGet200Three | NotlarGrupluListeGet200Four>(
      {url: `/api/Notlar/GrupluListe`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydın onay durumunu ve onay geçmişini getirir.
INTENT: onay durumu nedir, onaylandı mı, hangi aşamada, onay sorgula
KULLANIM: Onay akışı takibi, kaydın hangi adımda olduğunu öğrenme.
 */
const Notlar_OnayDurumuGet = (
    { id }: NotlarOnayDurumuGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi>(
      {url: `/api/Notlar/${id}/OnayDurumu`, method: 'GET'
    },
      );
    }
  /**
 * @summary Belirtilen kaydın değişiklik geçmişini getirir. Kim, ne zaman, ne değiştirdi bilgisi.
INTENT: değişiklik geçmişi, kim değiştirdi, ne zaman değişti, log, audit, tarihçe
KULLANIM: Kayıt üzerinde yapılan tüm değişikliklerin izlenmesi ve denetimi.
 */
const Notlar_DegisiklikGecmisiGet = (
    { id }: NotlarDegisiklikGecmisiGetPathParameters,
    params?: NotlarDegisiklikGecmisiGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi>(
      {url: `/api/Notlar/${id}/DegisiklikGecmisi`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait belge listesini getirir.
INTENT: belgeleri getir, dosyaları listele, ekleri göster, dokümanlar
KULLANIM: Kayda eklenmiş sözleşme, fatura, resim gibi belgelerin listelenmesi.
 */
const Notlar_BelgelerGet = (
    { id }: NotlarBelgelerGetPathParameters,
    params?: NotlarBelgelerGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi>(
      {url: `/api/Notlar/${id}/Belgeler`, method: 'GET',
        params
    },
      );
    }
  const Notlar_BelgeEklePost = (
    { id }: NotlarBelgeEklePostPathParameters,
    params?: NotlarBelgeEklePostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/Notlar/${id}/BelgeEkle`, method: 'POST',
        params
    },
      );
    }
  const Notlar_BelgeSilDelete = (
    { id, belgeID }: NotlarBelgeSilDeletePathParameters,
    params?: NotlarBelgeSilDeleteParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/Notlar/${id}/BelgeSil/${belgeID}`, method: 'DELETE',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait notları getirir.
INTENT: notları getir, açıklamaları göster, yorumları listele, notlar neler
KULLANIM: Kayda eklenen serbest metin notların, hatırlatmaların veya açıklamaların listelenmesi.
 */
const Notlar_NotlarGet = (
    { id }: NotlarNotlarGetPathParameters,
    params?: NotlarNotlarGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi>(
      {url: `/api/Notlar/${id}/Notlar`, method: 'GET',
        params
    },
      );
    }
  const Notlar_NotEklePost = (
    { id }: NotlarNotEklePostPathParameters,
    aaroModullerNotlarKayitSadeKayitModelBody: AaroModullerNotlarKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/Notlar/${id}/NotEkle`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerNotlarKayitSadeKayitModelBody
    },
      );
    }
  const Notlar_NotSilDelete = (
    { id, notID }: NotlarNotSilDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/Notlar/${id}/NotSil/${notID}`, method: 'DELETE'
    },
      );
    }
  return {Notlar_GetGet,Notlar_PutPut,Notlar_DeleteDelete,Notlar_ListeGetGet,Notlar_PostPost,Notlar_OnaylaPost,Notlar_ReddetPost,Notlar_ListeEsnekGet,Notlar_ListePostPost,Notlar_GrupluListeGet,Notlar_OnayDurumuGet,Notlar_DegisiklikGecmisiGet,Notlar_BelgelerGet,Notlar_BelgeEklePost,Notlar_BelgeSilDelete,Notlar_NotlarGet,Notlar_NotEklePost,Notlar_NotSilDelete}};
export type NotlarGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotlar>['Notlar_GetGet']>>>
export type NotlarPutPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotlar>['Notlar_PutPut']>>>
export type NotlarDeleteDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotlar>['Notlar_DeleteDelete']>>>
export type NotlarListeGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotlar>['Notlar_ListeGetGet']>>>
export type NotlarPostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotlar>['Notlar_PostPost']>>>
export type NotlarOnaylaPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotlar>['Notlar_OnaylaPost']>>>
export type NotlarReddetPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotlar>['Notlar_ReddetPost']>>>
export type NotlarListeEsnekGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotlar>['Notlar_ListeEsnekGet']>>>
export type NotlarListePostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotlar>['Notlar_ListePostPost']>>>
export type NotlarGrupluListeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotlar>['Notlar_GrupluListeGet']>>>
export type NotlarOnayDurumuGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotlar>['Notlar_OnayDurumuGet']>>>
export type NotlarDegisiklikGecmisiGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotlar>['Notlar_DegisiklikGecmisiGet']>>>
export type NotlarBelgelerGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotlar>['Notlar_BelgelerGet']>>>
export type NotlarBelgeEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotlar>['Notlar_BelgeEklePost']>>>
export type NotlarBelgeSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotlar>['Notlar_BelgeSilDelete']>>>
export type NotlarNotlarGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotlar>['Notlar_NotlarGet']>>>
export type NotlarNotEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotlar>['Notlar_NotEklePost']>>>
export type NotlarNotSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotlar>['Notlar_NotSilDelete']>>>
