/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type {
  AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokHareketleriListeModel,
  StokHareketleriDetayliListeGetParams,
  StokHareketleriGrupluListeGetParams
} from '../../models';

import { customInstance } from '../../axios';



  export const getStokHareketleri = () => {
/**
 * @summary Stok hareketlerinin detaylı listesini getirir. 
Stok hareketlerinin detaylı analizleri ve takibi için kullanılır.
Filtreleme, sayfalama ve sıralama desteği sunar.
 */
const StokHareketleri_DetayliListeGet = (
    params?: StokHareketleriDetayliListeGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokHareketleriListeModel>(
      {url: `/api/StokHareketleri`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Stok hareket verilerini gruplama ve agregasyon işlemleri için kullanılır. 
Bu Web API endpoint'i stok hareketlerini pivot table benzeri şekilde gruplar ve 
matematiksel işlemler (toplam, ortalama, min, max, sayım) uygular.
Alternatif İsimler: StockMovementGrouping, InventoryMovementPivot, StockTransactionSummary, MaterialMovementAnalysis

Kullanım Senaryoları:
Stok Analizleri:
- Aylık/yıllık ürün bazlı hareket raporları oluşturma
- Ürün bazında giriş/çıkış miktarları analizi
- En çok hareket gören ürünlerin belirlenmesi (ABC analizi)
- Sezonsal stok hareket paternlerinin ürün bazında analizi
- Kritik stok seviyelerinin tespit edilmesi 
Depo Yönetimi:
- Depo bazında stok hareket performans değerlendirme
- Raf/lokasyon bazında hareket yoğunluğu analizi
- Depo verimliliği ve kapasite kullanım oranları
- Transfer hareketlerinin depo bazında takibi
- Envanter devir hızı analizleri 
Operasyonel Raporlama:
- Dönemsel stok giriş/çıkış özetleri
- Fire/zayi oranlarının ürün/kategori bazında analizi
- Üretim-tüketim dengesi raporları
- Seri/lot bazında izlenebilirlik raporları
- Stok yaşlandırma analizleri 
Maliyet Analizleri:
- Ürün bazında ortalama maliyet hesaplamaları
- Stok değer hareketlerinin takibi
- Karlılık analizleri için maliyet dağılımları
- Enflasyon etkilerinin stok maliyetlerine yansıması
- FIFO/LIFO maliyet metodları karşılaştırması 
Satın Alma ve Tedarik:
- Tedarikçi bazında alım performans analizleri
- Sipariş-teslimat süre analizleri
- Tedarikçi kalite performans değerlendirmeleri
- Minimum-maksimum stok seviyelerinin optimizasyonu
- Talep tahminleme için geçmiş hareket analizleri 
Üretim Planlama:
- Hammadde tüketim oranları ve planlaması
- Üretim kapasitesi ve kaynak kullanım analizleri
- Yarı mamul ve mamul hareket takibi
- Üretim verimliliği ölçümleri
- İş emri bazında malzeme tüketim analizleri 
Finansal Kontrol:
- Stok devir hızı ve cash flow etkisi analizleri
- Ölü stok tespiti ve değer kaybı hesaplamaları
- Sigorta değerlendirmeleri için stok değer raporları
- Mali müşavir raporları için stok hareket özetleri
- Vergi denetimi için stok hareket dökümleri 
Uyum ve İzlenebilirlik:
- İthalat/ihracat gümrük beyanları için stok raporları
- Çevre mevzuatı için atık/geri dönüşüm takibi
- Kalite kontrol süreçleri için hareket izleme

İş Kuralları:
- En az bir grup alanı belirtilmelidir
- En az bir değer alanı ve gruplama tipi belirtilmelidir
- Kullanıcının stok hareketleri pivot yetki kontrolü yapılır
- Boş/null değerler hesaplamalarda 0 olarak kabul edilir
- Giriş/çıkış durumuna göre miktarlar otomatik işaretlenir
- Maksimum 50.000 kayıt üzerinde gruplama yapılır

MCP/Chatbot Açıklama:
Bu API ile kullanıcı "Bu aya kadar ürün bazında toplam giriş miktarlarını göster", 
"Depo bazında en çok hareket gören ürünler hangileri" gibi sorguları cevaplayabilir. 
Stok yönetimi ve operasyonel raporlama için temel veri kaynağıdır.
 */
const StokHareketleri_GrupluListeGet = (
    params?: StokHareketleriGrupluListeGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokHareketleriListeModel>(
      {url: `/api/StokHareketleri/Pivot`, method: 'GET',
        params
    },
      );
    }
  return {StokHareketleri_DetayliListeGet,StokHareketleri_GrupluListeGet}};
export type StokHareketleriDetayliListeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStokHareketleri>['StokHareketleri_DetayliListeGet']>>>
export type StokHareketleriGrupluListeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStokHareketleri>['StokHareketleri_GrupluListeGet']>>>
