/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type {
  AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel,
  AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel,
  AaroKayitSonucAaroModullerUrMakineKayitSadeKayitModel,
  AaroKayitSonucAaroModullerUrMakineKayitSadeListeModel,
  AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrMakineKayitSadeListeModel,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi,
  AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi,
  AaroModullerNotlarKayitSadeKayitModelBody,
  AaroModullerUrMakineKayitSadeKayitModelBody,
  LinqFilteringAdvancedFilterRequestBody,
  UrMakineBelgeEklePostParams,
  UrMakineBelgeEklePostPathParameters,
  UrMakineBelgeSilDeleteParams,
  UrMakineBelgeSilDeletePathParameters,
  UrMakineBelgelerGetParams,
  UrMakineBelgelerGetPathParameters,
  UrMakineDegisiklikGecmisiGetParams,
  UrMakineDegisiklikGecmisiGetPathParameters,
  UrMakineDeleteDeletePathParameters,
  UrMakineGetGetPathParameters,
  UrMakineGrupluListeGet200Four,
  UrMakineGrupluListeGet200One,
  UrMakineGrupluListeGet200Three,
  UrMakineGrupluListeGet200Two,
  UrMakineGrupluListeGetParams,
  UrMakineListeEsnekGet200Four,
  UrMakineListeEsnekGet200One,
  UrMakineListeEsnekGet200Three,
  UrMakineListeEsnekGet200Two,
  UrMakineListeEsnekGetParams,
  UrMakineListeGetGetParams,
  UrMakineNotEklePostPathParameters,
  UrMakineNotSilDeletePathParameters,
  UrMakineNotlarGetParams,
  UrMakineNotlarGetPathParameters,
  UrMakineOnayDurumuGetPathParameters,
  UrMakineOnaylaPostParams,
  UrMakinePutPutPathParameters,
  UrMakineReddetPostParams
} from '../../models';

import { customInstance } from '../../axios';



  export const getUrMakine = () => {
/**
 * @summary Belirtilen ID'ye sahip kaydı getirir. Kart detay bilgilerini döndürür.
INTENT: kaydı getir, detayı göster, bilgileri al, ID ile sorgula, kartı görüntüle
KULLANIM: Kart görüntüleme, düzenleme öncesi mevcut bilgileri alma.
 */
const UrMakine_GetGet = (
    { id }: UrMakineGetGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerUrMakineKayitSadeListeModel>(
      {url: `/api/UrMakine/${id}`, method: 'GET'
    },
      );
    }
  const UrMakine_PutPut = (
    { id }: UrMakinePutPutPathParameters,
    aaroModullerUrMakineKayitSadeKayitModelBody: AaroModullerUrMakineKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerUrMakineKayitSadeListeModel>(
      {url: `/api/UrMakine/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerUrMakineKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı siler veya pasifleştirir.
INTENT: sil, kaldır, pasifleştir, devre dışı bırak, kapat
KULLANIM: Artık kullanılmayan kayıtları sistemden kaldırma veya pasifleştirme.
IS_KURALLARI: Hareketi veya bağlı kaydı bulunan kartlar tamamen silinemez; yalnızca pasifleştirilebilir.
 */
const UrMakine_DeleteDelete = (
    { id }: UrMakineDeleteDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerUrMakineKayitSadeListeModel>(
      {url: `/api/UrMakine/${id}`, method: 'DELETE'
    },
      );
    }
  const UrMakine_ListeGetGet = (
    params?: UrMakineListeGetGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrMakineKayitSadeListeModel>(
      {url: `/api/UrMakine`, method: 'GET',
        params
    },
      );
    }
  const UrMakine_PostPost = (
    aaroModullerUrMakineKayitSadeKayitModelBody: AaroModullerUrMakineKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerUrMakineKayitSadeListeModel>(
      {url: `/api/UrMakine`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerUrMakineKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı onaylar. Onay akışındaki kaydı bir sonraki aşamaya taşır.
INTENT: onayla, kabul et, akışı ilerlet, onay ver
IS_KURALLARI: Kayıt onay akışında olmalı ve onaylanabilir durumda olmalı.
 */
const UrMakine_OnaylaPost = (
    params?: UrMakineOnaylaPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerUrMakineKayitSadeKayitModel>(
      {url: `/api/UrMakine/Onayla`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydı reddeder. Onay akışındaki kaydı geri gönderir.
INTENT: reddet, geri gönder, onaylama, iade et
IS_KURALLARI: Kayıt onay akışında ve reddedilebilir durumda olmalı.
 */
const UrMakine_ReddetPost = (
    params?: UrMakineReddetPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerUrMakineKayitSadeKayitModel>(
      {url: `/api/UrMakine/Reddet`, method: 'POST',
        params
    },
      );
    }
  /**
 * FILTRE_FORMATI: {Alan}:{Operator}:{Deger}:{Mantik}
Operatörler:
  eq  — Eşit           örn: Durum:eq:True
  ct  — İçerir         örn: Ad:ct:Market
  sw  — İle başlar     örn: Kod:sw:A
  gt  — Büyüktür       örn: Bakiye:gt:5000
  in  — Listede        örn: GrupID:in:1|5|8   (değerler | ile ayrılır)
  lk  — Like (%)       örn: Adres:lk:İstanbul
Birden fazla filtre virgülle birleştirilir:
  örn: Sehir:eq:Istanbul:and,Bakiye:gt:5000:and,GrupID:in:1|5|8
            
SIRALAMA_FORMATI: {Alan}:{Yon}
  örn: Ad:asc,Bakiye:desc    (Varsayılan: Kod alanı artan)
            
SUTUN_SECIMI: Sadece ihtiyaç duyulan alanlar belirtilir; performansı artırır.
  örn: ID,Kod,Ad,Bakiye
 * @summary Dinamik ve esnek sorgulama altyapısı ile kayıt listesini getirir.
Kolon seçimi, karmaşık filtreler ve sıralama üzerinde tam kontrol sağlar.
INTENT: esnek sorgula, dinamik filtrele, özel alanları getir, karmaşık filtre uygula
KULLANIM: İnsan geliştirici ve harici entegrasyonlar için tasarlanmıştır.
          MCP ve AI çağrıları için POST /Liste tercih edilmelidir.
MCP_NOT: Bu endpoint MCP/AI çağrıları için önerilmez. 
         Tip güvensiz string filtreler hata üretme riski taşır.
         Karmaşık filtreler için POST /Liste kullanılır.
 */
const UrMakine_ListeEsnekGet = (
    params?: UrMakineListeEsnekGetParams,
 ) => {
      return customInstance<UrMakineListeEsnekGet200One | UrMakineListeEsnekGet200Two | UrMakineListeEsnekGet200Three | UrMakineListeEsnekGet200Four>(
      {url: `/api/UrMakine/Liste`, method: 'GET',
        params
    },
      );
    }
  const UrMakine_ListePostPost = (
    linqFilteringAdvancedFilterRequestBody: LinqFilteringAdvancedFilterRequestBody,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrMakineKayitSadeListeModel>(
      {url: `/api/UrMakine/Liste`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: linqFilteringAdvancedFilterRequestBody
    },
      );
    }
  /**
 * @summary Kayıtları belirtilen alanlara göre gruplayarak özet liste döndürür.
INTENT: grupla, özet al, gruplara göre say, gruplama raporu
KULLANIM: Gruplama bazlı raporlama ve istatistik sorgularında kullanılır.
YETKI: Hareket özeti admini gerektirir.
 */
const UrMakine_GrupluListeGet = (
    params?: UrMakineGrupluListeGetParams,
 ) => {
      return customInstance<UrMakineGrupluListeGet200One | UrMakineGrupluListeGet200Two | UrMakineGrupluListeGet200Three | UrMakineGrupluListeGet200Four>(
      {url: `/api/UrMakine/GrupluListe`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydın onay durumunu ve onay geçmişini getirir.
INTENT: onay durumu nedir, onaylandı mı, hangi aşamada, onay sorgula
KULLANIM: Onay akışı takibi, kaydın hangi adımda olduğunu öğrenme.
 */
const UrMakine_OnayDurumuGet = (
    { id }: UrMakineOnayDurumuGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi>(
      {url: `/api/UrMakine/${id}/OnayDurumu`, method: 'GET'
    },
      );
    }
  /**
 * @summary Belirtilen kaydın değişiklik geçmişini getirir. Kim, ne zaman, ne değiştirdi bilgisi.
INTENT: değişiklik geçmişi, kim değiştirdi, ne zaman değişti, log, audit, tarihçe
KULLANIM: Kayıt üzerinde yapılan tüm değişikliklerin izlenmesi ve denetimi.
 */
const UrMakine_DegisiklikGecmisiGet = (
    { id }: UrMakineDegisiklikGecmisiGetPathParameters,
    params?: UrMakineDegisiklikGecmisiGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi>(
      {url: `/api/UrMakine/${id}/DegisiklikGecmisi`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait belge listesini getirir.
INTENT: belgeleri getir, dosyaları listele, ekleri göster, dokümanlar
KULLANIM: Kayda eklenmiş sözleşme, fatura, resim gibi belgelerin listelenmesi.
 */
const UrMakine_BelgelerGet = (
    { id }: UrMakineBelgelerGetPathParameters,
    params?: UrMakineBelgelerGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi>(
      {url: `/api/UrMakine/${id}/Belgeler`, method: 'GET',
        params
    },
      );
    }
  const UrMakine_BelgeEklePost = (
    { id }: UrMakineBelgeEklePostPathParameters,
    params?: UrMakineBelgeEklePostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/UrMakine/${id}/BelgeEkle`, method: 'POST',
        params
    },
      );
    }
  const UrMakine_BelgeSilDelete = (
    { id, belgeID }: UrMakineBelgeSilDeletePathParameters,
    params?: UrMakineBelgeSilDeleteParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/UrMakine/${id}/BelgeSil/${belgeID}`, method: 'DELETE',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait notları getirir.
INTENT: notları getir, açıklamaları göster, yorumları listele, notlar neler
KULLANIM: Kayda eklenen serbest metin notların, hatırlatmaların veya açıklamaların listelenmesi.
 */
const UrMakine_NotlarGet = (
    { id }: UrMakineNotlarGetPathParameters,
    params?: UrMakineNotlarGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi>(
      {url: `/api/UrMakine/${id}/Notlar`, method: 'GET',
        params
    },
      );
    }
  const UrMakine_NotEklePost = (
    { id }: UrMakineNotEklePostPathParameters,
    aaroModullerNotlarKayitSadeKayitModelBody: AaroModullerNotlarKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/UrMakine/${id}/NotEkle`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerNotlarKayitSadeKayitModelBody
    },
      );
    }
  const UrMakine_NotSilDelete = (
    { id, notID }: UrMakineNotSilDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/UrMakine/${id}/NotSil/${notID}`, method: 'DELETE'
    },
      );
    }
  return {UrMakine_GetGet,UrMakine_PutPut,UrMakine_DeleteDelete,UrMakine_ListeGetGet,UrMakine_PostPost,UrMakine_OnaylaPost,UrMakine_ReddetPost,UrMakine_ListeEsnekGet,UrMakine_ListePostPost,UrMakine_GrupluListeGet,UrMakine_OnayDurumuGet,UrMakine_DegisiklikGecmisiGet,UrMakine_BelgelerGet,UrMakine_BelgeEklePost,UrMakine_BelgeSilDelete,UrMakine_NotlarGet,UrMakine_NotEklePost,UrMakine_NotSilDelete}};
export type UrMakineGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrMakine>['UrMakine_GetGet']>>>
export type UrMakinePutPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrMakine>['UrMakine_PutPut']>>>
export type UrMakineDeleteDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrMakine>['UrMakine_DeleteDelete']>>>
export type UrMakineListeGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrMakine>['UrMakine_ListeGetGet']>>>
export type UrMakinePostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrMakine>['UrMakine_PostPost']>>>
export type UrMakineOnaylaPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrMakine>['UrMakine_OnaylaPost']>>>
export type UrMakineReddetPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrMakine>['UrMakine_ReddetPost']>>>
export type UrMakineListeEsnekGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrMakine>['UrMakine_ListeEsnekGet']>>>
export type UrMakineListePostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrMakine>['UrMakine_ListePostPost']>>>
export type UrMakineGrupluListeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrMakine>['UrMakine_GrupluListeGet']>>>
export type UrMakineOnayDurumuGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrMakine>['UrMakine_OnayDurumuGet']>>>
export type UrMakineDegisiklikGecmisiGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrMakine>['UrMakine_DegisiklikGecmisiGet']>>>
export type UrMakineBelgelerGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrMakine>['UrMakine_BelgelerGet']>>>
export type UrMakineBelgeEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrMakine>['UrMakine_BelgeEklePost']>>>
export type UrMakineBelgeSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrMakine>['UrMakine_BelgeSilDelete']>>>
export type UrMakineNotlarGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrMakine>['UrMakine_NotlarGet']>>>
export type UrMakineNotEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrMakine>['UrMakine_NotEklePost']>>>
export type UrMakineNotSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUrMakine>['UrMakine_NotSilDelete']>>>
