/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type {
  AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerDepoTerminalHareketListeModel,
  AaroModullerSeriLotKayitSadeHizliGirisSatirBody,
  DepoTerminalDepolarArasiTransferGet200Four,
  DepoTerminalDepolarArasiTransferGet200One,
  DepoTerminalDepolarArasiTransferGet200Three,
  DepoTerminalDepolarArasiTransferGet200Two,
  DepoTerminalDepolarArasiTransferGetParams,
  DepoTerminalDepolarArasiTransferKalemDetayPost200Four,
  DepoTerminalDepolarArasiTransferKalemDetayPost200One,
  DepoTerminalDepolarArasiTransferKalemDetayPost200Three,
  DepoTerminalDepolarArasiTransferKalemDetayPost200Two,
  DepoTerminalDepolarArasiTransferKalemDetayPostParams,
  DepoTerminalDepolarArasiTransferKalemDetaylarGet200Four,
  DepoTerminalDepolarArasiTransferKalemDetaylarGet200One,
  DepoTerminalDepolarArasiTransferKalemDetaylarGet200Three,
  DepoTerminalDepolarArasiTransferKalemDetaylarGet200Two,
  DepoTerminalDepolarArasiTransferKalemGet200Four,
  DepoTerminalDepolarArasiTransferKalemGet200One,
  DepoTerminalDepolarArasiTransferKalemGet200Three,
  DepoTerminalDepolarArasiTransferKalemGet200Two,
  DepoTerminalDepolarArasiTransferKalemGetParams,
  DepoTerminalDepolarArasiTransferListesiGetirGet200Four,
  DepoTerminalDepolarArasiTransferListesiGetirGet200One,
  DepoTerminalDepolarArasiTransferListesiGetirGet200Three,
  DepoTerminalDepolarArasiTransferListesiGetirGet200Two,
  DepoTerminalFaturaIrsaliyeGet200Four,
  DepoTerminalFaturaIrsaliyeGet200One,
  DepoTerminalFaturaIrsaliyeGet200Three,
  DepoTerminalFaturaIrsaliyeGet200Two,
  DepoTerminalFaturaIrsaliyeGetParams,
  DepoTerminalFaturaIrsaliyeKalemDetayPost200Four,
  DepoTerminalFaturaIrsaliyeKalemDetayPost200One,
  DepoTerminalFaturaIrsaliyeKalemDetayPost200Three,
  DepoTerminalFaturaIrsaliyeKalemDetayPost200Two,
  DepoTerminalFaturaIrsaliyeKalemDetayPostParams,
  DepoTerminalFaturaIrsaliyeKalemDetaylarGet200Four,
  DepoTerminalFaturaIrsaliyeKalemDetaylarGet200One,
  DepoTerminalFaturaIrsaliyeKalemDetaylarGet200Three,
  DepoTerminalFaturaIrsaliyeKalemDetaylarGet200Two,
  DepoTerminalFaturaIrsaliyeKalemDetaylarGetParams,
  DepoTerminalFaturaIrsaliyeKalemGet200Four,
  DepoTerminalFaturaIrsaliyeKalemGet200One,
  DepoTerminalFaturaIrsaliyeKalemGet200Three,
  DepoTerminalFaturaIrsaliyeKalemGet200Two,
  DepoTerminalFaturaIrsaliyeKalemGetParams,
  DepoTerminalFaturaIrsaliyeKalemlerGet200Four,
  DepoTerminalFaturaIrsaliyeKalemlerGet200One,
  DepoTerminalFaturaIrsaliyeKalemlerGet200Three,
  DepoTerminalFaturaIrsaliyeKalemlerGet200Two,
  DepoTerminalFaturaIrsaliyeKalemlerGetParams,
  DepoTerminalHareketListesiGetParams,
  DepoTerminalListeKayitlarSayisiGet200Four,
  DepoTerminalListeKayitlarSayisiGet200One,
  DepoTerminalListeKayitlarSayisiGet200Three,
  DepoTerminalListeKayitlarSayisiGet200Two,
  DepoTerminalStokMiktarListesiGet200Four,
  DepoTerminalStokMiktarListesiGet200One,
  DepoTerminalStokMiktarListesiGet200Three,
  DepoTerminalStokMiktarListesiGet200Two,
  DepoTerminalStokMiktarListesiGetParams,
  DepoTerminalTransferPost200Four,
  DepoTerminalTransferPost200One,
  DepoTerminalTransferPost200Three,
  DepoTerminalTransferPost200Two,
  DepoTerminalTransferPostParams
} from '../../models';

import { customInstance } from '../../axios';



  export const getDepoTerminal = () => {
const DepoTerminal_HareketListesiGet = (
    params?: DepoTerminalHareketListesiGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerDepoTerminalHareketListeModel>(
      {url: `/api/DepoTerminal/HareketListesi`, method: 'GET',
        params
    },
      );
    }
  const DepoTerminal_ListeKayitlarSayisiGet = (
    
 ) => {
      return customInstance<DepoTerminalListeKayitlarSayisiGet200One | DepoTerminalListeKayitlarSayisiGet200Two | DepoTerminalListeKayitlarSayisiGet200Three | DepoTerminalListeKayitlarSayisiGet200Four>(
      {url: `/api/DepoTerminal/ListeKayitlarSayisi`, method: 'GET'
    },
      );
    }
  const DepoTerminal_FaturaIrsaliyeGet = (
    params?: DepoTerminalFaturaIrsaliyeGetParams,
 ) => {
      return customInstance<DepoTerminalFaturaIrsaliyeGet200One | DepoTerminalFaturaIrsaliyeGet200Two | DepoTerminalFaturaIrsaliyeGet200Three | DepoTerminalFaturaIrsaliyeGet200Four>(
      {url: `/api/DepoTerminal/FaturaIrsaliye`, method: 'GET',
        params
    },
      );
    }
  const DepoTerminal_FaturaIrsaliyeKalemlerGet = (
    params?: DepoTerminalFaturaIrsaliyeKalemlerGetParams,
 ) => {
      return customInstance<DepoTerminalFaturaIrsaliyeKalemlerGet200One | DepoTerminalFaturaIrsaliyeKalemlerGet200Two | DepoTerminalFaturaIrsaliyeKalemlerGet200Three | DepoTerminalFaturaIrsaliyeKalemlerGet200Four>(
      {url: `/api/DepoTerminal/FaturaIrsaliyeKalemler`, method: 'GET',
        params
    },
      );
    }
  const DepoTerminal_FaturaIrsaliyeKalemGet = (
    params?: DepoTerminalFaturaIrsaliyeKalemGetParams,
 ) => {
      return customInstance<DepoTerminalFaturaIrsaliyeKalemGet200One | DepoTerminalFaturaIrsaliyeKalemGet200Two | DepoTerminalFaturaIrsaliyeKalemGet200Three | DepoTerminalFaturaIrsaliyeKalemGet200Four>(
      {url: `/api/DepoTerminal/FaturaIrsaliyeKalem`, method: 'GET',
        params
    },
      );
    }
  const DepoTerminal_FaturaIrsaliyeKalemDetaylarGet = (
    params?: DepoTerminalFaturaIrsaliyeKalemDetaylarGetParams,
 ) => {
      return customInstance<DepoTerminalFaturaIrsaliyeKalemDetaylarGet200One | DepoTerminalFaturaIrsaliyeKalemDetaylarGet200Two | DepoTerminalFaturaIrsaliyeKalemDetaylarGet200Three | DepoTerminalFaturaIrsaliyeKalemDetaylarGet200Four>(
      {url: `/api/DepoTerminal/FaturaIrsaliyeKalemDetaylar`, method: 'GET',
        params
    },
      );
    }
  const DepoTerminal_FaturaIrsaliyeKalemDetayPost = (
    aaroModullerSeriLotKayitSadeHizliGirisSatirBody: AaroModullerSeriLotKayitSadeHizliGirisSatirBody,
    params?: DepoTerminalFaturaIrsaliyeKalemDetayPostParams,
 ) => {
      return customInstance<DepoTerminalFaturaIrsaliyeKalemDetayPost200One | DepoTerminalFaturaIrsaliyeKalemDetayPost200Two | DepoTerminalFaturaIrsaliyeKalemDetayPost200Three | DepoTerminalFaturaIrsaliyeKalemDetayPost200Four>(
      {url: `/api/DepoTerminal/FaturaIrsaliyeKalemDetay`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerSeriLotKayitSadeHizliGirisSatirBody,
        params
    },
      );
    }
  const DepoTerminal_StokMiktarListesiGet = (
    params?: DepoTerminalStokMiktarListesiGetParams,
 ) => {
      return customInstance<DepoTerminalStokMiktarListesiGet200One | DepoTerminalStokMiktarListesiGet200Two | DepoTerminalStokMiktarListesiGet200Three | DepoTerminalStokMiktarListesiGet200Four>(
      {url: `/api/DepoTerminal/StokMiktarListesi`, method: 'GET',
        params
    },
      );
    }
  const DepoTerminal_TransferPost = (
    params?: DepoTerminalTransferPostParams,
 ) => {
      return customInstance<DepoTerminalTransferPost200One | DepoTerminalTransferPost200Two | DepoTerminalTransferPost200Three | DepoTerminalTransferPost200Four>(
      {url: `/api/DepoTerminal/Transfer`, method: 'POST',
        params
    },
      );
    }
  const DepoTerminal_DepolarArasiTransferGet = (
    params?: DepoTerminalDepolarArasiTransferGetParams,
 ) => {
      return customInstance<DepoTerminalDepolarArasiTransferGet200One | DepoTerminalDepolarArasiTransferGet200Two | DepoTerminalDepolarArasiTransferGet200Three | DepoTerminalDepolarArasiTransferGet200Four>(
      {url: `/api/DepoTerminal/DepolarArasiTransfer`, method: 'GET',
        params
    },
      );
    }
  const DepoTerminal_DepolarArasiTransferListesiGetirGet = (
    
 ) => {
      return customInstance<DepoTerminalDepolarArasiTransferListesiGetirGet200One | DepoTerminalDepolarArasiTransferListesiGetirGet200Two | DepoTerminalDepolarArasiTransferListesiGetirGet200Three | DepoTerminalDepolarArasiTransferListesiGetirGet200Four>(
      {url: `/api/DepoTerminal/DepolarArasiTransferListesiGetir`, method: 'GET'
    },
      );
    }
  const DepoTerminal_DepolarArasiTransferKalemGet = (
    params?: DepoTerminalDepolarArasiTransferKalemGetParams,
 ) => {
      return customInstance<DepoTerminalDepolarArasiTransferKalemGet200One | DepoTerminalDepolarArasiTransferKalemGet200Two | DepoTerminalDepolarArasiTransferKalemGet200Three | DepoTerminalDepolarArasiTransferKalemGet200Four>(
      {url: `/api/DepoTerminal/DepolarArasiTransferKalem`, method: 'GET',
        params
    },
      );
    }
  const DepoTerminal_DepolarArasiTransferKalemDetaylarGet = (
    
 ) => {
      return customInstance<DepoTerminalDepolarArasiTransferKalemDetaylarGet200One | DepoTerminalDepolarArasiTransferKalemDetaylarGet200Two | DepoTerminalDepolarArasiTransferKalemDetaylarGet200Three | DepoTerminalDepolarArasiTransferKalemDetaylarGet200Four>(
      {url: `/api/DepoTerminal/DepolarArasiTransferKalemDetaylar`, method: 'GET'
    },
      );
    }
  const DepoTerminal_DepolarArasiTransferKalemDetayPost = (
    aaroModullerSeriLotKayitSadeHizliGirisSatirBody: AaroModullerSeriLotKayitSadeHizliGirisSatirBody,
    params?: DepoTerminalDepolarArasiTransferKalemDetayPostParams,
 ) => {
      return customInstance<DepoTerminalDepolarArasiTransferKalemDetayPost200One | DepoTerminalDepolarArasiTransferKalemDetayPost200Two | DepoTerminalDepolarArasiTransferKalemDetayPost200Three | DepoTerminalDepolarArasiTransferKalemDetayPost200Four>(
      {url: `/api/DepoTerminal/DepolarArasiTransferKalemDetay`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerSeriLotKayitSadeHizliGirisSatirBody,
        params
    },
      );
    }
  return {DepoTerminal_HareketListesiGet,DepoTerminal_ListeKayitlarSayisiGet,DepoTerminal_FaturaIrsaliyeGet,DepoTerminal_FaturaIrsaliyeKalemlerGet,DepoTerminal_FaturaIrsaliyeKalemGet,DepoTerminal_FaturaIrsaliyeKalemDetaylarGet,DepoTerminal_FaturaIrsaliyeKalemDetayPost,DepoTerminal_StokMiktarListesiGet,DepoTerminal_TransferPost,DepoTerminal_DepolarArasiTransferGet,DepoTerminal_DepolarArasiTransferListesiGetirGet,DepoTerminal_DepolarArasiTransferKalemGet,DepoTerminal_DepolarArasiTransferKalemDetaylarGet,DepoTerminal_DepolarArasiTransferKalemDetayPost}};
export type DepoTerminalHareketListesiGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDepoTerminal>['DepoTerminal_HareketListesiGet']>>>
export type DepoTerminalListeKayitlarSayisiGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDepoTerminal>['DepoTerminal_ListeKayitlarSayisiGet']>>>
export type DepoTerminalFaturaIrsaliyeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDepoTerminal>['DepoTerminal_FaturaIrsaliyeGet']>>>
export type DepoTerminalFaturaIrsaliyeKalemlerGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDepoTerminal>['DepoTerminal_FaturaIrsaliyeKalemlerGet']>>>
export type DepoTerminalFaturaIrsaliyeKalemGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDepoTerminal>['DepoTerminal_FaturaIrsaliyeKalemGet']>>>
export type DepoTerminalFaturaIrsaliyeKalemDetaylarGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDepoTerminal>['DepoTerminal_FaturaIrsaliyeKalemDetaylarGet']>>>
export type DepoTerminalFaturaIrsaliyeKalemDetayPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDepoTerminal>['DepoTerminal_FaturaIrsaliyeKalemDetayPost']>>>
export type DepoTerminalStokMiktarListesiGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDepoTerminal>['DepoTerminal_StokMiktarListesiGet']>>>
export type DepoTerminalTransferPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDepoTerminal>['DepoTerminal_TransferPost']>>>
export type DepoTerminalDepolarArasiTransferGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDepoTerminal>['DepoTerminal_DepolarArasiTransferGet']>>>
export type DepoTerminalDepolarArasiTransferListesiGetirGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDepoTerminal>['DepoTerminal_DepolarArasiTransferListesiGetirGet']>>>
export type DepoTerminalDepolarArasiTransferKalemGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDepoTerminal>['DepoTerminal_DepolarArasiTransferKalemGet']>>>
export type DepoTerminalDepolarArasiTransferKalemDetaylarGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDepoTerminal>['DepoTerminal_DepolarArasiTransferKalemDetaylarGet']>>>
export type DepoTerminalDepolarArasiTransferKalemDetayPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDepoTerminal>['DepoTerminal_DepolarArasiTransferKalemDetayPost']>>>
