/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type {
  AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel,
  AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel,
  AaroKayitSonucAaroModullerStokKayitSadeKayitModel,
  AaroKayitSonucAaroModullerStokKayitSadeListeModel,
  AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokKayitSadeListeModel,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi,
  AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi,
  AaroModullerNotlarKayitSadeKayitModelBody,
  AaroModullerStokKayitSadeKayitModelBody,
  DemirbasBelgeEklePostParams,
  DemirbasBelgeEklePostPathParameters,
  DemirbasBelgeSilDeleteParams,
  DemirbasBelgeSilDeletePathParameters,
  DemirbasBelgelerGetParams,
  DemirbasBelgelerGetPathParameters,
  DemirbasDegisiklikGecmisiGetParams,
  DemirbasDegisiklikGecmisiGetPathParameters,
  DemirbasDeleteDeletePathParameters,
  DemirbasGetGetPathParameters,
  DemirbasGrupluListeGet200Four,
  DemirbasGrupluListeGet200One,
  DemirbasGrupluListeGet200Three,
  DemirbasGrupluListeGet200Two,
  DemirbasGrupluListeGetParams,
  DemirbasListeEsnekGet200Four,
  DemirbasListeEsnekGet200One,
  DemirbasListeEsnekGet200Three,
  DemirbasListeEsnekGet200Two,
  DemirbasListeEsnekGetParams,
  DemirbasListeGetGetParams,
  DemirbasNotEklePostPathParameters,
  DemirbasNotSilDeletePathParameters,
  DemirbasNotlarGetParams,
  DemirbasNotlarGetPathParameters,
  DemirbasOnayDurumuGetPathParameters,
  DemirbasOnaylaPostParams,
  DemirbasPutPutPathParameters,
  DemirbasReddetPostParams,
  LinqFilteringAdvancedFilterRequestBody
} from '../../models';

import { customInstance } from '../../axios';



  export const getDemirbas = () => {
/**
 * @summary Belirtilen ID'ye sahip kaydı getirir. Kart detay bilgilerini döndürür.
INTENT: kaydı getir, detayı göster, bilgileri al, ID ile sorgula, kartı görüntüle
KULLANIM: Kart görüntüleme, düzenleme öncesi mevcut bilgileri alma.
 */
const Demirbas_GetGet = (
    { id }: DemirbasGetGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokKayitSadeListeModel>(
      {url: `/api/Demirbas/${id}`, method: 'GET'
    },
      );
    }
  const Demirbas_PutPut = (
    { id }: DemirbasPutPutPathParameters,
    aaroModullerStokKayitSadeKayitModelBody: AaroModullerStokKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokKayitSadeListeModel>(
      {url: `/api/Demirbas/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerStokKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı siler veya pasifleştirir.
INTENT: sil, kaldır, pasifleştir, devre dışı bırak, kapat
KULLANIM: Artık kullanılmayan kayıtları sistemden kaldırma veya pasifleştirme.
IS_KURALLARI: Hareketi veya bağlı kaydı bulunan kartlar tamamen silinemez; yalnızca pasifleştirilebilir.
 */
const Demirbas_DeleteDelete = (
    { id }: DemirbasDeleteDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokKayitSadeListeModel>(
      {url: `/api/Demirbas/${id}`, method: 'DELETE'
    },
      );
    }
  const Demirbas_ListeGetGet = (
    params?: DemirbasListeGetGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokKayitSadeListeModel>(
      {url: `/api/Demirbas`, method: 'GET',
        params
    },
      );
    }
  const Demirbas_PostPost = (
    aaroModullerStokKayitSadeKayitModelBody: AaroModullerStokKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokKayitSadeListeModel>(
      {url: `/api/Demirbas`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerStokKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı onaylar. Onay akışındaki kaydı bir sonraki aşamaya taşır.
INTENT: onayla, kabul et, akışı ilerlet, onay ver
IS_KURALLARI: Kayıt onay akışında olmalı ve onaylanabilir durumda olmalı.
 */
const Demirbas_OnaylaPost = (
    params?: DemirbasOnaylaPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokKayitSadeKayitModel>(
      {url: `/api/Demirbas/Onayla`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydı reddeder. Onay akışındaki kaydı geri gönderir.
INTENT: reddet, geri gönder, onaylama, iade et
IS_KURALLARI: Kayıt onay akışında ve reddedilebilir durumda olmalı.
 */
const Demirbas_ReddetPost = (
    params?: DemirbasReddetPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokKayitSadeKayitModel>(
      {url: `/api/Demirbas/Reddet`, method: 'POST',
        params
    },
      );
    }
  /**
 * FILTRE_FORMATI: {Alan}:{Operator}:{Deger}:{Mantik}
Operatörler:
  eq  — Eşit           örn: Durum:eq:True
  ct  — İçerir         örn: Ad:ct:Market
  sw  — İle başlar     örn: Kod:sw:A
  gt  — Büyüktür       örn: Bakiye:gt:5000
  in  — Listede        örn: GrupID:in:1|5|8   (değerler | ile ayrılır)
  lk  — Like (%)       örn: Adres:lk:İstanbul
Birden fazla filtre virgülle birleştirilir:
  örn: Sehir:eq:Istanbul:and,Bakiye:gt:5000:and,GrupID:in:1|5|8
            
SIRALAMA_FORMATI: {Alan}:{Yon}
  örn: Ad:asc,Bakiye:desc    (Varsayılan: Kod alanı artan)
            
SUTUN_SECIMI: Sadece ihtiyaç duyulan alanlar belirtilir; performansı artırır.
  örn: ID,Kod,Ad,Bakiye
 * @summary Dinamik ve esnek sorgulama altyapısı ile kayıt listesini getirir.
Kolon seçimi, karmaşık filtreler ve sıralama üzerinde tam kontrol sağlar.
INTENT: esnek sorgula, dinamik filtrele, özel alanları getir, karmaşık filtre uygula
KULLANIM: İnsan geliştirici ve harici entegrasyonlar için tasarlanmıştır.
          MCP ve AI çağrıları için POST /Liste tercih edilmelidir.
MCP_NOT: Bu endpoint MCP/AI çağrıları için önerilmez. 
         Tip güvensiz string filtreler hata üretme riski taşır.
         Karmaşık filtreler için POST /Liste kullanılır.
 */
const Demirbas_ListeEsnekGet = (
    params?: DemirbasListeEsnekGetParams,
 ) => {
      return customInstance<DemirbasListeEsnekGet200One | DemirbasListeEsnekGet200Two | DemirbasListeEsnekGet200Three | DemirbasListeEsnekGet200Four>(
      {url: `/api/Demirbas/Liste`, method: 'GET',
        params
    },
      );
    }
  const Demirbas_ListePostPost = (
    linqFilteringAdvancedFilterRequestBody: LinqFilteringAdvancedFilterRequestBody,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokKayitSadeListeModel>(
      {url: `/api/Demirbas/Liste`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: linqFilteringAdvancedFilterRequestBody
    },
      );
    }
  /**
 * @summary Kayıtları belirtilen alanlara göre gruplayarak özet liste döndürür.
INTENT: grupla, özet al, gruplara göre say, gruplama raporu
KULLANIM: Gruplama bazlı raporlama ve istatistik sorgularında kullanılır.
YETKI: Hareket özeti admini gerektirir.
 */
const Demirbas_GrupluListeGet = (
    params?: DemirbasGrupluListeGetParams,
 ) => {
      return customInstance<DemirbasGrupluListeGet200One | DemirbasGrupluListeGet200Two | DemirbasGrupluListeGet200Three | DemirbasGrupluListeGet200Four>(
      {url: `/api/Demirbas/GrupluListe`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydın onay durumunu ve onay geçmişini getirir.
INTENT: onay durumu nedir, onaylandı mı, hangi aşamada, onay sorgula
KULLANIM: Onay akışı takibi, kaydın hangi adımda olduğunu öğrenme.
 */
const Demirbas_OnayDurumuGet = (
    { id }: DemirbasOnayDurumuGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi>(
      {url: `/api/Demirbas/${id}/OnayDurumu`, method: 'GET'
    },
      );
    }
  /**
 * @summary Belirtilen kaydın değişiklik geçmişini getirir. Kim, ne zaman, ne değiştirdi bilgisi.
INTENT: değişiklik geçmişi, kim değiştirdi, ne zaman değişti, log, audit, tarihçe
KULLANIM: Kayıt üzerinde yapılan tüm değişikliklerin izlenmesi ve denetimi.
 */
const Demirbas_DegisiklikGecmisiGet = (
    { id }: DemirbasDegisiklikGecmisiGetPathParameters,
    params?: DemirbasDegisiklikGecmisiGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi>(
      {url: `/api/Demirbas/${id}/DegisiklikGecmisi`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait belge listesini getirir.
INTENT: belgeleri getir, dosyaları listele, ekleri göster, dokümanlar
KULLANIM: Kayda eklenmiş sözleşme, fatura, resim gibi belgelerin listelenmesi.
 */
const Demirbas_BelgelerGet = (
    { id }: DemirbasBelgelerGetPathParameters,
    params?: DemirbasBelgelerGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi>(
      {url: `/api/Demirbas/${id}/Belgeler`, method: 'GET',
        params
    },
      );
    }
  const Demirbas_BelgeEklePost = (
    { id }: DemirbasBelgeEklePostPathParameters,
    params?: DemirbasBelgeEklePostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/Demirbas/${id}/BelgeEkle`, method: 'POST',
        params
    },
      );
    }
  const Demirbas_BelgeSilDelete = (
    { id, belgeID }: DemirbasBelgeSilDeletePathParameters,
    params?: DemirbasBelgeSilDeleteParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/Demirbas/${id}/BelgeSil/${belgeID}`, method: 'DELETE',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait notları getirir.
INTENT: notları getir, açıklamaları göster, yorumları listele, notlar neler
KULLANIM: Kayda eklenen serbest metin notların, hatırlatmaların veya açıklamaların listelenmesi.
 */
const Demirbas_NotlarGet = (
    { id }: DemirbasNotlarGetPathParameters,
    params?: DemirbasNotlarGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi>(
      {url: `/api/Demirbas/${id}/Notlar`, method: 'GET',
        params
    },
      );
    }
  const Demirbas_NotEklePost = (
    { id }: DemirbasNotEklePostPathParameters,
    aaroModullerNotlarKayitSadeKayitModelBody: AaroModullerNotlarKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/Demirbas/${id}/NotEkle`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerNotlarKayitSadeKayitModelBody
    },
      );
    }
  const Demirbas_NotSilDelete = (
    { id, notID }: DemirbasNotSilDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/Demirbas/${id}/NotSil/${notID}`, method: 'DELETE'
    },
      );
    }
  return {Demirbas_GetGet,Demirbas_PutPut,Demirbas_DeleteDelete,Demirbas_ListeGetGet,Demirbas_PostPost,Demirbas_OnaylaPost,Demirbas_ReddetPost,Demirbas_ListeEsnekGet,Demirbas_ListePostPost,Demirbas_GrupluListeGet,Demirbas_OnayDurumuGet,Demirbas_DegisiklikGecmisiGet,Demirbas_BelgelerGet,Demirbas_BelgeEklePost,Demirbas_BelgeSilDelete,Demirbas_NotlarGet,Demirbas_NotEklePost,Demirbas_NotSilDelete}};
export type DemirbasGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDemirbas>['Demirbas_GetGet']>>>
export type DemirbasPutPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDemirbas>['Demirbas_PutPut']>>>
export type DemirbasDeleteDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDemirbas>['Demirbas_DeleteDelete']>>>
export type DemirbasListeGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDemirbas>['Demirbas_ListeGetGet']>>>
export type DemirbasPostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDemirbas>['Demirbas_PostPost']>>>
export type DemirbasOnaylaPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDemirbas>['Demirbas_OnaylaPost']>>>
export type DemirbasReddetPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDemirbas>['Demirbas_ReddetPost']>>>
export type DemirbasListeEsnekGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDemirbas>['Demirbas_ListeEsnekGet']>>>
export type DemirbasListePostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDemirbas>['Demirbas_ListePostPost']>>>
export type DemirbasGrupluListeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDemirbas>['Demirbas_GrupluListeGet']>>>
export type DemirbasOnayDurumuGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDemirbas>['Demirbas_OnayDurumuGet']>>>
export type DemirbasDegisiklikGecmisiGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDemirbas>['Demirbas_DegisiklikGecmisiGet']>>>
export type DemirbasBelgelerGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDemirbas>['Demirbas_BelgelerGet']>>>
export type DemirbasBelgeEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDemirbas>['Demirbas_BelgeEklePost']>>>
export type DemirbasBelgeSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDemirbas>['Demirbas_BelgeSilDelete']>>>
export type DemirbasNotlarGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDemirbas>['Demirbas_NotlarGet']>>>
export type DemirbasNotEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDemirbas>['Demirbas_NotEklePost']>>>
export type DemirbasNotSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDemirbas>['Demirbas_NotSilDelete']>>>
