/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type {
  AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariHareketleriListeListeModel,
  CariHareketleriDetayliListeGetParams,
  CariHareketleriGrupluListeGet200Four,
  CariHareketleriGrupluListeGet200One,
  CariHareketleriGrupluListeGet200Three,
  CariHareketleriGrupluListeGet200Two,
  CariHareketleriGrupluListeGetParams,
  CariHareketleriListeEsnekGet200Four,
  CariHareketleriListeEsnekGet200One,
  CariHareketleriListeEsnekGet200Three,
  CariHareketleriListeEsnekGet200Two,
  CariHareketleriListeEsnekGetParams
} from '../../models';

import { customInstance } from '../../axios';



  export const getCariHareketleri = () => {
/**
 * @summary Cari hesap hareketlerinin detaylı listesini getirir. Müşteri/tedarikçi hesap ekstreleri, 
borç/alacak durumları ve finansal raporlama için kullanılır.
Filtreleme, sayfalama ve sıralama desteği sunar.
 */
const CariHareketleri_DetayliListeGet = (
    params?: CariHareketleriDetayliListeGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariHareketleriListeListeModel>(
      {url: `/api/CariHareketleri`, method: 'GET',
        params
    },
      );
    }
  const CariHareketleri_ListeEsnekGet = (
    params?: CariHareketleriListeEsnekGetParams,
 ) => {
      return customInstance<CariHareketleriListeEsnekGet200One | CariHareketleriListeEsnekGet200Two | CariHareketleriListeEsnekGet200Three | CariHareketleriListeEsnekGet200Four>(
      {url: `/api/CariHareketleri/Liste`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary ERP'de Cari hareket verilerini gruplama ve agregasyon işlemleri için kullanılır. 
Bu fonksiyon pivot table benzeri çalışarak, belirtilen alanlara göre verileri gruplar ve 
matematiksel işlemler (toplam, ortalama, min, max, sayım) uygular.

Kullanım Senaryoları:
Satış Analizleri:
- Aylık/yıllık müşteri bazlı satış raporları oluşturma
- Müşteri bazında ciro analizi ve trend takibi
- En çok satış yapılan müşterilerin belirlenmesi (ABC analizi)
- Sezonsal satış paternlerinin müşteri bazında analizi
- Yeni müşteri kazanım oranları ve performans ölçümü        
Performans Değerlendirme:
- Plasiyer bazında performans değerlendirme ve hedef takibi
- Satış temsilcisi bazında müşteri portföy analizi
- Bölge/şehir bazında satış performans karşılaştırması
- Müşteri sadakat analizleri (tekrar alım oranları)        
Finansal Analizler:
- Müşteri bazında alacak/borç durumu özeti
- Vadeli satışların müşteri bazında takibi
- Müşteri risk analizleri (ödeme gecikmesi, limit aşımı)
- Nakit akış tahminleri için müşteri bazlı projeksiyonlar     
Operasyonel Raporlama:
- Dönemsel müşteri hareketlilik raporları
- İade oranlarının müşteri bazında analizi
- Ödeme yöntemlerinin müşteri bazında dağılımı
- Müşteri segmentasyonu için davranış analizleri
- Fatura bazlı tahsilat performans takibi        
Stratejik Kararlar:
- Müşteri portföy optimizasyonu için veri analizi
- Fiyatlandırma stratejileri için müşteri bazlı elastisite analizi
- Yeni pazar fırsatlarının belirlenmesi
- Müşteri yaşam boyu değeri (CLV) hesaplamaları
- Çapraz satış fırsatlarının tespiti         
Uyum ve Kontrol:
- Mali müşavir raporları için müşteri bazlı özetler
- Vergi denetimi için cari hareket özetleri
- İç denetim süreçleri için müşteri bazlı anomali tespiti
- Muhasebe dönem kapama raporları

İş Kuralları:
- En az bir grup alanı belirtilmelidir
- En az bir değer alanı ve gruplama tipi belirtilmelidir
- Kullanıcının pivot yetki kontrolü yapılır
- Boş/null değerler hesaplamalarda 0 olarak kabul edilir
- Borç/Alacak durumuna göre tutarlar otomatik işaretlenir
- Maksimum 50000 kayıt üzerinden gruplama yapılır, üzeri için filtre daraltılmalı

MCP/Chatbot Açıklama:
Bu API ile kullanıcı "Bu aya kadar müşteri bazında toplam satışları göster" 
gibi sorguları cevaplayabilir. Finansal raporlama ve analiz için temel veri kaynağıdır.
 */
const CariHareketleri_GrupluListeGet = (
    params?: CariHareketleriGrupluListeGetParams,
 ) => {
      return customInstance<CariHareketleriGrupluListeGet200One | CariHareketleriGrupluListeGet200Two | CariHareketleriGrupluListeGet200Three | CariHareketleriGrupluListeGet200Four>(
      {url: `/api/CariHareketleri/Pivot`, method: 'GET',
        params
    },
      );
    }
  return {CariHareketleri_DetayliListeGet,CariHareketleri_ListeEsnekGet,CariHareketleri_GrupluListeGet}};
export type CariHareketleriDetayliListeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariHareketleri>['CariHareketleri_DetayliListeGet']>>>
export type CariHareketleriListeEsnekGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariHareketleri>['CariHareketleri_ListeEsnekGet']>>>
export type CariHareketleriGrupluListeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCariHareketleri>['CariHareketleri_GrupluListeGet']>>>
