/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type {
  AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel,
  AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel,
  AaroKayitSonucAaroModullerStokKayitSadeDetayliKayitModelAPI,
  AaroKayitSonucAaroModullerStokKayitSadeKayitModel,
  AaroKayitSonucAaroModullerStokKayitSadeListeModel,
  AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokKayitSadeListeModel,
  AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokKayitSadeMinModel,
  AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokKayitSadeStokMiktarListeModel,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi,
  AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi,
  AaroModullerNotlarKayitSadeKayitModelBody,
  AaroModullerStokKayitSadeDetayliKayitModelAPI,
  AaroModullerStokKayitSadeKayitModelBody,
  LinqFilteringAdvancedFilterRequestBody,
  StokBelgeEklePostParams,
  StokBelgeEklePostPathParameters,
  StokBelgeSilDeleteParams,
  StokBelgeSilDeletePathParameters,
  StokBelgelerGetParams,
  StokBelgelerGetPathParameters,
  StokDegisiklikGecmisiGetParams,
  StokDegisiklikGecmisiGetPathParameters,
  StokDeleteDeletePathParameters,
  StokDetayliGetGetPathParameters,
  StokGetGetPathParameters,
  StokGrupluListeGet200Four,
  StokGrupluListeGet200One,
  StokGrupluListeGet200Three,
  StokGrupluListeGet200Two,
  StokGrupluListeGetParams,
  StokListeEsnekGet200Four,
  StokListeEsnekGet200One,
  StokListeEsnekGet200Three,
  StokListeEsnekGet200Two,
  StokListeEsnekGetParams,
  StokListeGetGetParams,
  StokMinListeGetParams,
  StokNotEklePostPathParameters,
  StokNotSilDeletePathParameters,
  StokNotlarGetParams,
  StokNotlarGetPathParameters,
  StokOnayDurumuGetPathParameters,
  StokOnaylaPostParams,
  StokPutPutPathParameters,
  StokReddetPostParams,
  StokStokMiktarListeGetParams
} from '../../models';

import { customInstance } from '../../axios';



  export const getStok = () => {
/**
 * @summary Stok kartlarının sadece temel bilgilerini içeren hafif liste getirir.
 */
const Stok_MinListeGet = (
    params?: StokMinListeGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokKayitSadeMinModel>(
      {url: `/api/Stok/MinListe`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Depo bazında stok miktarlarının detaylı listesini getirir.
Stok hareketlerinden hesaplanmış güncel miktarları, birim bilgileriyle birlikte sunar.
 */
const Stok_StokMiktarListeGet = (
    params?: StokStokMiktarListeGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokKayitSadeStokMiktarListeModel>(
      {url: `/api/Stok/StokMiktarListe`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Stok ana kaydını entegrasyon tanımı ve muhasebe hesaplarıyla birlikte tek seferde günceller.
INTENT: detaylı stok güncelle, muhasebe hesabıyla birlikte düzenle, komple güncelle
KULLANIM: Entegrasyon tanımı veya muhasebe hesapları da aynı anda güncellenecekse standart Put yerine bu endpoint kullanılır.
IS_KURALLARI: StokID zorunlu. Gönderilmeyen entegrasyon bilgileri değiştirilmez.
MCP_NOT: Sadece temel stok bilgileri güncellenecekse standart PUT /api/Stok/{id} tercih edilir.
         Entegrasyon bilgileri de güncellenecekse bu endpoint tek çağrıyla işlemi tamamlar.
 */
const Stok_DetayliPutPut = (
    aaroModullerStokKayitSadeDetayliKayitModelAPI: AaroModullerStokKayitSadeDetayliKayitModelAPI,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokKayitSadeKayitModel>(
      {url: `/api/Stok/Detayli`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerStokKayitSadeDetayliKayitModelAPI
    },
      );
    }
  /**
 * @summary Stok ana kaydını entegrasyon tanımı ve muhasebe hesaplarıyla birlikte tek seferde oluşturur.
INTENT: detaylı stok oluştur, tam kayıt aç, muhasebe hesabıyla birlikte ekle, komple kayıt
KULLANIM: Entegrasyon tanımı ve muhasebe hesapları da aynı anda kaydedilecekse standart Post yerine bu endpoint kullanılır.
IS_KURALLARI: StokKodu benzersiz olmalı. EntegrasyonTanimi isteğe bağlıdır; gönderilmezse otomatik oluşturulur.
MCP_NOT: Sadece temel stok bilgileri kaydedilecekse standart POST /api/Stok tercih edilir.
         Muhasebe entegrasyonu da kurulacaksa bu endpoint tek çağrıyla işlemi tamamlar.
 */
const Stok_DetayliPostPost = (
    aaroModullerStokKayitSadeDetayliKayitModelAPI: AaroModullerStokKayitSadeDetayliKayitModelAPI,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokKayitSadeKayitModel>(
      {url: `/api/Stok/Detayli`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerStokKayitSadeDetayliKayitModelAPI
    },
      );
    }
  /**
 * @summary Belirtilen Stok ID'si ile stok kartının tüm detaylı bilgilerini getirir.
INTENT: detaylı stok verisi getir, barkod ve fiyatla beraber stok oku, tam stok bilgisi
KULLANIM: Stok kartı ile birlikte ilişkili barkodlar, alış/satış fiyatları ve muhasebe entegrasyon kodları da lazımsa bu endpoint kullanılır.
IS_KURALLARI: StokID (id) parametresi zorunludur ve sistemde kayıtlı olmalıdır.
MCP_NOT: Sadece temel alanlar (adı, kodu vb.) istenecekse standart GET /api/Stok/{id} kullanılabilir. 
         Tüm ilişkili detaylar (barkod, fiyat, entegrasyon) tek seferde çekilmek isteniyorsa bu endpoint tercih edilmelidir.
 */
const Stok_DetayliGetGet = (
    { id }: StokDetayliGetGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokKayitSadeDetayliKayitModelAPI>(
      {url: `/api/Stok/Detayli/${id}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Belirtilen ID'ye sahip kaydı getirir. Kart detay bilgilerini döndürür.
INTENT: kaydı getir, detayı göster, bilgileri al, ID ile sorgula, kartı görüntüle
KULLANIM: Kart görüntüleme, düzenleme öncesi mevcut bilgileri alma.
 */
const Stok_GetGet = (
    { id }: StokGetGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokKayitSadeListeModel>(
      {url: `/api/Stok/${id}`, method: 'GET'
    },
      );
    }
  const Stok_PutPut = (
    { id }: StokPutPutPathParameters,
    aaroModullerStokKayitSadeKayitModelBody: AaroModullerStokKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokKayitSadeListeModel>(
      {url: `/api/Stok/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerStokKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı siler veya pasifleştirir.
INTENT: sil, kaldır, pasifleştir, devre dışı bırak, kapat
KULLANIM: Artık kullanılmayan kayıtları sistemden kaldırma veya pasifleştirme.
IS_KURALLARI: Hareketi veya bağlı kaydı bulunan kartlar tamamen silinemez; yalnızca pasifleştirilebilir.
 */
const Stok_DeleteDelete = (
    { id }: StokDeleteDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokKayitSadeListeModel>(
      {url: `/api/Stok/${id}`, method: 'DELETE'
    },
      );
    }
  const Stok_ListeGetGet = (
    params?: StokListeGetGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokKayitSadeListeModel>(
      {url: `/api/Stok`, method: 'GET',
        params
    },
      );
    }
  const Stok_PostPost = (
    aaroModullerStokKayitSadeKayitModelBody: AaroModullerStokKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokKayitSadeListeModel>(
      {url: `/api/Stok`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerStokKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı onaylar. Onay akışındaki kaydı bir sonraki aşamaya taşır.
INTENT: onayla, kabul et, akışı ilerlet, onay ver
IS_KURALLARI: Kayıt onay akışında olmalı ve onaylanabilir durumda olmalı.
 */
const Stok_OnaylaPost = (
    params?: StokOnaylaPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokKayitSadeKayitModel>(
      {url: `/api/Stok/Onayla`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydı reddeder. Onay akışındaki kaydı geri gönderir.
INTENT: reddet, geri gönder, onaylama, iade et
IS_KURALLARI: Kayıt onay akışında ve reddedilebilir durumda olmalı.
 */
const Stok_ReddetPost = (
    params?: StokReddetPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerStokKayitSadeKayitModel>(
      {url: `/api/Stok/Reddet`, method: 'POST',
        params
    },
      );
    }
  /**
 * FILTRE_FORMATI: {Alan}:{Operator}:{Deger}:{Mantik}
Operatörler:
  eq  — Eşit           örn: Durum:eq:True
  ct  — İçerir         örn: Ad:ct:Market
  sw  — İle başlar     örn: Kod:sw:A
  gt  — Büyüktür       örn: Bakiye:gt:5000
  in  — Listede        örn: GrupID:in:1|5|8   (değerler | ile ayrılır)
  lk  — Like (%)       örn: Adres:lk:İstanbul
Birden fazla filtre virgülle birleştirilir:
  örn: Sehir:eq:Istanbul:and,Bakiye:gt:5000:and,GrupID:in:1|5|8
            
SIRALAMA_FORMATI: {Alan}:{Yon}
  örn: Ad:asc,Bakiye:desc    (Varsayılan: Kod alanı artan)
            
SUTUN_SECIMI: Sadece ihtiyaç duyulan alanlar belirtilir; performansı artırır.
  örn: ID,Kod,Ad,Bakiye
 * @summary Dinamik ve esnek sorgulama altyapısı ile kayıt listesini getirir.
Kolon seçimi, karmaşık filtreler ve sıralama üzerinde tam kontrol sağlar.
INTENT: esnek sorgula, dinamik filtrele, özel alanları getir, karmaşık filtre uygula
KULLANIM: İnsan geliştirici ve harici entegrasyonlar için tasarlanmıştır.
          MCP ve AI çağrıları için POST /Liste tercih edilmelidir.
MCP_NOT: Bu endpoint MCP/AI çağrıları için önerilmez. 
         Tip güvensiz string filtreler hata üretme riski taşır.
         Karmaşık filtreler için POST /Liste kullanılır.
 */
const Stok_ListeEsnekGet = (
    params?: StokListeEsnekGetParams,
 ) => {
      return customInstance<StokListeEsnekGet200One | StokListeEsnekGet200Two | StokListeEsnekGet200Three | StokListeEsnekGet200Four>(
      {url: `/api/Stok/Liste`, method: 'GET',
        params
    },
      );
    }
  const Stok_ListePostPost = (
    linqFilteringAdvancedFilterRequestBody: LinqFilteringAdvancedFilterRequestBody,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerStokKayitSadeListeModel>(
      {url: `/api/Stok/Liste`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: linqFilteringAdvancedFilterRequestBody
    },
      );
    }
  /**
 * @summary Kayıtları belirtilen alanlara göre gruplayarak özet liste döndürür.
INTENT: grupla, özet al, gruplara göre say, gruplama raporu
KULLANIM: Gruplama bazlı raporlama ve istatistik sorgularında kullanılır.
YETKI: Hareket özeti admini gerektirir.
 */
const Stok_GrupluListeGet = (
    params?: StokGrupluListeGetParams,
 ) => {
      return customInstance<StokGrupluListeGet200One | StokGrupluListeGet200Two | StokGrupluListeGet200Three | StokGrupluListeGet200Four>(
      {url: `/api/Stok/GrupluListe`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydın onay durumunu ve onay geçmişini getirir.
INTENT: onay durumu nedir, onaylandı mı, hangi aşamada, onay sorgula
KULLANIM: Onay akışı takibi, kaydın hangi adımda olduğunu öğrenme.
 */
const Stok_OnayDurumuGet = (
    { id }: StokOnayDurumuGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi>(
      {url: `/api/Stok/${id}/OnayDurumu`, method: 'GET'
    },
      );
    }
  /**
 * @summary Belirtilen kaydın değişiklik geçmişini getirir. Kim, ne zaman, ne değiştirdi bilgisi.
INTENT: değişiklik geçmişi, kim değiştirdi, ne zaman değişti, log, audit, tarihçe
KULLANIM: Kayıt üzerinde yapılan tüm değişikliklerin izlenmesi ve denetimi.
 */
const Stok_DegisiklikGecmisiGet = (
    { id }: StokDegisiklikGecmisiGetPathParameters,
    params?: StokDegisiklikGecmisiGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi>(
      {url: `/api/Stok/${id}/DegisiklikGecmisi`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait belge listesini getirir.
INTENT: belgeleri getir, dosyaları listele, ekleri göster, dokümanlar
KULLANIM: Kayda eklenmiş sözleşme, fatura, resim gibi belgelerin listelenmesi.
 */
const Stok_BelgelerGet = (
    { id }: StokBelgelerGetPathParameters,
    params?: StokBelgelerGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi>(
      {url: `/api/Stok/${id}/Belgeler`, method: 'GET',
        params
    },
      );
    }
  const Stok_BelgeEklePost = (
    { id }: StokBelgeEklePostPathParameters,
    params?: StokBelgeEklePostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/Stok/${id}/BelgeEkle`, method: 'POST',
        params
    },
      );
    }
  const Stok_BelgeSilDelete = (
    { id, belgeID }: StokBelgeSilDeletePathParameters,
    params?: StokBelgeSilDeleteParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/Stok/${id}/BelgeSil/${belgeID}`, method: 'DELETE',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait notları getirir.
INTENT: notları getir, açıklamaları göster, yorumları listele, notlar neler
KULLANIM: Kayda eklenen serbest metin notların, hatırlatmaların veya açıklamaların listelenmesi.
 */
const Stok_NotlarGet = (
    { id }: StokNotlarGetPathParameters,
    params?: StokNotlarGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi>(
      {url: `/api/Stok/${id}/Notlar`, method: 'GET',
        params
    },
      );
    }
  const Stok_NotEklePost = (
    { id }: StokNotEklePostPathParameters,
    aaroModullerNotlarKayitSadeKayitModelBody: AaroModullerNotlarKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/Stok/${id}/NotEkle`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerNotlarKayitSadeKayitModelBody
    },
      );
    }
  const Stok_NotSilDelete = (
    { id, notID }: StokNotSilDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/Stok/${id}/NotSil/${notID}`, method: 'DELETE'
    },
      );
    }
  return {Stok_MinListeGet,Stok_StokMiktarListeGet,Stok_DetayliPutPut,Stok_DetayliPostPost,Stok_DetayliGetGet,Stok_GetGet,Stok_PutPut,Stok_DeleteDelete,Stok_ListeGetGet,Stok_PostPost,Stok_OnaylaPost,Stok_ReddetPost,Stok_ListeEsnekGet,Stok_ListePostPost,Stok_GrupluListeGet,Stok_OnayDurumuGet,Stok_DegisiklikGecmisiGet,Stok_BelgelerGet,Stok_BelgeEklePost,Stok_BelgeSilDelete,Stok_NotlarGet,Stok_NotEklePost,Stok_NotSilDelete}};
export type StokMinListeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_MinListeGet']>>>
export type StokStokMiktarListeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_StokMiktarListeGet']>>>
export type StokDetayliPutPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_DetayliPutPut']>>>
export type StokDetayliPostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_DetayliPostPost']>>>
export type StokDetayliGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_DetayliGetGet']>>>
export type StokGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_GetGet']>>>
export type StokPutPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_PutPut']>>>
export type StokDeleteDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_DeleteDelete']>>>
export type StokListeGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_ListeGetGet']>>>
export type StokPostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_PostPost']>>>
export type StokOnaylaPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_OnaylaPost']>>>
export type StokReddetPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_ReddetPost']>>>
export type StokListeEsnekGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_ListeEsnekGet']>>>
export type StokListePostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_ListePostPost']>>>
export type StokGrupluListeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_GrupluListeGet']>>>
export type StokOnayDurumuGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_OnayDurumuGet']>>>
export type StokDegisiklikGecmisiGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_DegisiklikGecmisiGet']>>>
export type StokBelgelerGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_BelgelerGet']>>>
export type StokBelgeEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_BelgeEklePost']>>>
export type StokBelgeSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_BelgeSilDelete']>>>
export type StokNotlarGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_NotlarGet']>>>
export type StokNotEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_NotEklePost']>>>
export type StokNotSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStok>['Stok_NotSilDelete']>>>
