/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export interface AaroModullerPerMesaiHareketDetayCihazKayitSadeKayitModel {
  StrID?: number;
  CihazID?: number;
  CihazLogID?: number;
  CihazPersonelID?: number;
  Tarih?: Date;
  PerMesaiHareketDetayID?: number;
}
