/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerOlcuBirimleriKayitSadeListeModelTipID } from './aaroModullerOlcuBirimleriKayitSadeListeModelTipID';

export interface AaroModullerOlcuBirimleriKayitSadeListeModel {
  OlcuBirimleriUBLKodu?: string;
  OlcuBirimleriUBLAdi?: string;
  SubeKodu?: string;
  SubeAdi?: string;
  SirketKodu?: string;
  SirketAdi?: string;
  TipKodu?: string;
  TipAdi?: string;
  EsnekAramaKisiti?: string;
  BirimID?: number;
  BirimKodu?: string;
  BirimAdi?: string;
  OlcuBirimleriUBLID?: number;
  BirimOran?: number;
  TipID?: AaroModullerOlcuBirimleriKayitSadeListeModelTipID;
  SubeID?: number;
  SirketID?: number;
}
