/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerSeriLotKayitSadeListeModel } from './aaroModullerSeriLotKayitSadeListeModel';
import type { AaroKayitSonucAaroModullerSeriLotKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerSeriLotKayitSadeListeModelMesajlar';

export interface AaroKayitSonucAaroModullerSeriLotKayitSadeListeModel {
  Model?: AaroModullerSeriLotKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerSeriLotKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
