/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type AaroModullerSirketlerKayitSadeKayitModelEPostaSSL = typeof AaroModullerSirketlerKayitSadeKayitModelEPostaSSL[keyof typeof AaroModullerSirketlerKayitSadeKayitModelEPostaSSL];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AaroModullerSirketlerKayitSadeKayitModelEPostaSSL = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
} as const;
