/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerStokSayimHareketleriListeKayitModel } from './aaroModullerStokSayimHareketleriListeKayitModel';
import type { AaroKayitSonucAaroModullerStokSayimHareketleriListeKayitModelMesajlar } from './aaroKayitSonucAaroModullerStokSayimHareketleriListeKayitModelMesajlar';

export interface AaroKayitSonucAaroModullerStokSayimHareketleriListeKayitModel {
  Model?: AaroModullerStokSayimHareketleriListeKayitModel;
  Mesajlar?: AaroKayitSonucAaroModullerStokSayimHareketleriListeKayitModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
