/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';
import type { AaroModullerDepoKayitSadeListeModel } from './aaroModullerDepoKayitSadeListeModel';
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerDepoKayitSadeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerDepoKayitSadeListeModelMesajlar';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerDepoKayitSadeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerDepoKayitSadeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerDepoKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
