/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export interface AaroModullerUrAkisOperasyonKayitSadeUrAkisOperasyonHammaddeleri {
  ReceteOperasyonHammaddeID?: number;
  AkisOperasyonHammaddeID?: number;
  Miktar?: number;
  MiktarRecete?: number;
  HammaddeID?: number;
  HemMamulHemHammadde?: boolean;
  StokHareketID?: number;
  KullanilacakSeriLotlar?: string;
}
