/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export interface AaroModullerSeriLotKayitSadeHizliGirisSatir {
  HareketID?: number;
  StokRafID?: number;
  StokRafKodu?: string;
  PaketID?: number;
  PaketKodu?: string;
  YeniKodOlustur?: boolean;
  SeriLotID?: number;
  EskiSeriLotID?: number;
  SeriLotKodu?: string;
  EskiSeriLotKodu?: string;
  Miktar?: number;
  BA?: string;
  UrAkisOperasyonAnaMamulSeriLotID?: number;
  UrAkisOperasyonAnaMamulSeriLotKodu?: string;
  TransferStokRafID?: number;
  TransferStokRafKodu?: string;
  TransferPaketID?: number;
  TransferPaketKodu?: string;
  TransferHareketID?: number;
  SonKullanmaTarihi?: Date;
}
