/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export interface AaroModullerKaliteKontrolDetayKayitSadeListeModel {
  KaliteKontrolTurDetayAdi?: string;
  KaliteKontrolTurKodu?: string;
  KaliteKontrolTurAdi?: string;
  OlcumAletiKodu?: string;
  OlcumAletiAdi?: string;
  OlsTar?: Date;
  DgsTar?: Date;
  OlsID?: number;
  OlsKodu?: string;
  OlsAdi?: string;
  DgsID?: number;
  DgsKodu?: string;
  DgsAdi?: string;
  KaliteKontrolDetayID?: number;
  KaliteKontrolTurDetayID?: number;
  KaliteKontrolTurID?: number;
  KaliteKontrolID?: number;
  SayisalSonuc?: number;
  TarihSonuc?: Date;
  DogruYanlisSonuc?: boolean;
  MetinSonuc?: string;
  OlcumAletiID?: number;
}
