/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerStokSayimHareketleriListeListeModel } from './aaroModullerStokSayimHareketleriListeListeModel';
import type { AaroKayitSonucAaroModullerStokSayimHareketleriListeListeModelMesajlar } from './aaroKayitSonucAaroModullerStokSayimHareketleriListeListeModelMesajlar';

export interface AaroKayitSonucAaroModullerStokSayimHareketleriListeListeModel {
  Model?: AaroModullerStokSayimHareketleriListeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerStokSayimHareketleriListeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
