/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerStokBarkodKayitSadeListeModel } from './aaroModullerStokBarkodKayitSadeListeModel';
import type { AaroKayitSonucAaroModullerStokBarkodKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerStokBarkodKayitSadeListeModelMesajlar';

export interface AaroKayitSonucAaroModullerStokBarkodKayitSadeListeModel {
  Model?: AaroModullerStokBarkodKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerStokBarkodKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
