/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerAdrsIllerKayitSadeListeModel } from './aaroModullerAdrsIllerKayitSadeListeModel';
import type { AaroKayitSonucAaroModullerAdrsIllerKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerAdrsIllerKayitSadeListeModelMesajlar';

export interface AaroKayitSonucAaroModullerAdrsIllerKayitSadeListeModel {
  Model?: AaroModullerAdrsIllerKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerAdrsIllerKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
