/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerOnayKosulTanimKayitSadeOnaylanacaklarViewModelTabloID } from './aaroModullerOnayKosulTanimKayitSadeOnaylanacaklarViewModelTabloID';
import type { AaroModullerOnayKosulTanimKayitSadeOnaylanacaklarViewModelOnayDurum } from './aaroModullerOnayKosulTanimKayitSadeOnaylanacaklarViewModelOnayDurum';

export interface AaroModullerOnayKosulTanimKayitSadeOnaylanacaklarViewModel {
  Sube?: string;
  Sirket?: string;
  TipID?: number;
  Tarih?: Date;
  BelgeNo?: string;
  Tutar?: number;
  OnayKosulTanim?: string;
  IlkKullanici?: string;
  OnayindakiKullanici?: string;
  Tip?: string;
  HareketID?: number;
  TabloID?: AaroModullerOnayKosulTanimKayitSadeOnaylanacaklarViewModelTabloID;
  OnayID?: number;
  AdresCont?: string;
  AdresAct?: string;
  AdresData?: string;
  OnayDurum?: AaroModullerOnayKosulTanimKayitSadeOnaylanacaklarViewModelOnayDurum;
  Renk?: string;
  BagID?: number;
}
