/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';
import type { AaroModellerBelgeAdres } from './aaroModellerBelgeAdres';
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModellerBelgeAdresMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModellerBelgeAdresMesajlar';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModellerBelgeAdres {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModellerBelgeAdres[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModellerBelgeAdresMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
