/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';
import type { AaroModullerIthalatIhracatKayitSadeListeModel } from './aaroModullerIthalatIhracatKayitSadeListeModel';
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerIthalatIhracatKayitSadeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerIthalatIhracatKayitSadeListeModelMesajlar';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerIthalatIhracatKayitSadeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerIthalatIhracatKayitSadeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerIthalatIhracatKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
