/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';
import type { AaroModullerTakvimKayitSadeListeModel } from './aaroModullerTakvimKayitSadeListeModel';
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerTakvimKayitSadeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerTakvimKayitSadeListeModelMesajlar';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerTakvimKayitSadeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerTakvimKayitSadeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerTakvimKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
