/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerHareketTurleriAltKayitSadeKayitModelHareketTurDtyID } from './aaroModullerHareketTurleriAltKayitSadeKayitModelHareketTurDtyID';

export interface AaroModullerHareketTurleriAltKayitSadeKayitModel {
  HareketTurAltID?: number;
  HareketKodu?: string;
  HareketAdi?: string;
  SubeID?: number;
  SirketID?: number;
  HareketTurDtyID?: AaroModullerHareketTurleriAltKayitSadeKayitModelHareketTurDtyID;
  Durum?: boolean;
  IskontoOran?: number;
  Renk?: string;
}
