/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerIthalatIhracatKayitSadeKayitModelTipID } from './aaroModullerIthalatIhracatKayitSadeKayitModelTipID';

export interface AaroModullerIthalatIhracatKayitSadeKayitModel {
  IthalatIhracatID?: number;
  BeyannameNo?: string;
  Aciklama?: string;
  Durum?: boolean;
  TipID?: AaroModullerIthalatIhracatKayitSadeKayitModelTipID;
  CariID?: number;
  TeslimSekilleriVeSartlariID?: number;
  TasimaGonderimSekilID?: number;
  SirketID?: number;
  SubeID?: number;
  SablonID?: number;
}
