/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroKayitSonucSystemStringMesajlar } from './aaroKayitSonucSystemStringMesajlar';

export interface AaroKayitSonucSystemString {
  Model?: string;
  Mesajlar?: AaroKayitSonucSystemStringMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
