/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerHareketTurleriAltKayitSadeKayitModel } from './aaroModullerHareketTurleriAltKayitSadeKayitModel';
import type { AaroKayitSonucAaroModullerHareketTurleriAltKayitSadeKayitModelMesajlar } from './aaroKayitSonucAaroModullerHareketTurleriAltKayitSadeKayitModelMesajlar';

export interface AaroKayitSonucAaroModullerHareketTurleriAltKayitSadeKayitModel {
  Model?: AaroModullerHareketTurleriAltKayitSadeKayitModel;
  Mesajlar?: AaroKayitSonucAaroModullerHareketTurleriAltKayitSadeKayitModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
