/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerStokSayimKayitSadeListeModel } from './aaroModullerStokSayimKayitSadeListeModel';
import type { AaroKayitSonucAaroModullerStokSayimKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerStokSayimKayitSadeListeModelMesajlar';

export interface AaroKayitSonucAaroModullerStokSayimKayitSadeListeModel {
  Model?: AaroModullerStokSayimKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerStokSayimKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
