/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export interface AaroModullerMuhasebeKayitSadeKayitModel {
  MuhasebeID?: number;
  HesapKodu?: string;
  HesapAdi?: string;
  HesapAdiY?: string;
  BA?: string;
  AGM?: string;
  KartPuan?: number;
  Durum?: boolean;
  SubeID?: number;
  SirketID?: number;
  Kod1ID?: number;
  Kod2ID?: number;
  Kod3ID?: number;
  Kod4ID?: number;
  Kod5ID?: number;
  Kod6ID?: number;
  Etiket1ID?: number;
  Etiket2ID?: number;
  Etiket3ID?: number;
  Etiket4ID?: number;
  Etiket5ID?: number;
  SablonID?: number;
}
