/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerProjeKayitSadeKayitModelTipID } from './aaroModullerProjeKayitSadeKayitModelTipID';

export interface AaroModullerProjeKayitSadeKayitModel {
  ProjeID?: number;
  ProjeKodu?: string;
  ProjeAdi?: string;
  Aciklama?: string;
  AciklamalarID?: number;
  Vade?: number;
  SubeID?: number;
  SirketID?: number;
  Durum?: boolean;
  TipID?: AaroModullerProjeKayitSadeKayitModelTipID;
  Kod1ID?: number;
  Kod2ID?: number;
  Kod3ID?: number;
  Kod4ID?: number;
  Kod5ID?: number;
  Kod6ID?: number;
  Etiket1ID?: number;
  Etiket2ID?: number;
  Etiket3ID?: number;
  Etiket4ID?: number;
  Etiket5ID?: number;
  Seviye?: number;
  SablonID?: number;
}
