/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';
import type { AaroModullerUrIsEmriKayitSadeTamamlanmisUretimMaliyetleriModel } from './aaroModullerUrIsEmriKayitSadeTamamlanmisUretimMaliyetleriModel';
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrIsEmriKayitSadeTamamlanmisUretimMaliyetleriModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrIsEmriKayitSadeTamamlanmisUretimMaliyetleriModelMesajlar';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrIsEmriKayitSadeTamamlanmisUretimMaliyetleriModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerUrIsEmriKayitSadeTamamlanmisUretimMaliyetleriModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerUrIsEmriKayitSadeTamamlanmisUretimMaliyetleriModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
