/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerPersonelKayitSadeKayitModel } from './aaroModullerPersonelKayitSadeKayitModel';
import type { AaroKayitSonucAaroModullerPersonelKayitSadeKayitModelMesajlar } from './aaroKayitSonucAaroModullerPersonelKayitSadeKayitModelMesajlar';

export interface AaroKayitSonucAaroModullerPersonelKayitSadeKayitModel {
  Model?: AaroModullerPersonelKayitSadeKayitModel;
  Mesajlar?: AaroKayitSonucAaroModullerPersonelKayitSadeKayitModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
