/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerKaliteKontrolBaslikKayitSadeKayitModel } from './aaroModullerKaliteKontrolBaslikKayitSadeKayitModel';

export type AaroModullerKaliteKontrolBaslikKayitSadeKayitModelBody = AaroModullerKaliteKontrolBaslikKayitSadeKayitModel;
