/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

/**
 * e-Belgenin entegratör üzerindeki güncel statüsü.
 */
export type AaroMVCControllersWebApiBaslikModelEFaturaDurumID = typeof AaroMVCControllersWebApiBaslikModelEFaturaDurumID[keyof typeof AaroMVCControllersWebApiBaslikModelEFaturaDurumID];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AaroMVCControllersWebApiBaslikModelEFaturaDurumID = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
  NUMBER_7: 7,
  NUMBER_8: 8,
} as const;
