/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';
import type { AaroModullerSatisIadeFaturasiHareketleriListeModel } from './aaroModullerSatisIadeFaturasiHareketleriListeModel';
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisIadeFaturasiHareketleriListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisIadeFaturasiHareketleriListeModelMesajlar';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisIadeFaturasiHareketleriListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerSatisIadeFaturasiHareketleriListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisIadeFaturasiHareketleriListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
