/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerHareketTurleriAltKayitSadeListeModelHareketTurDtyID } from './aaroModullerHareketTurleriAltKayitSadeListeModelHareketTurDtyID';

export interface AaroModullerHareketTurleriAltKayitSadeListeModel {
  SubeKodu?: string;
  SubeAdi?: string;
  SirketKodu?: string;
  SirketAdi?: string;
  HareketTurleriDtyKodu?: string;
  HareketTurleriDtyAdi?: string;
  HareketTurAltID?: number;
  HareketKodu?: string;
  HareketAdi?: string;
  SubeID?: number;
  SirketID?: number;
  HareketTurDtyID?: AaroModullerHareketTurleriAltKayitSadeListeModelHareketTurDtyID;
  Durum?: boolean;
  IskontoOran?: number;
  Renk?: string;
}
