/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerUrOperasyonKayitSadeKayitModel } from './aaroModullerUrOperasyonKayitSadeKayitModel';
import type { AaroKayitSonucAaroModullerUrOperasyonKayitSadeKayitModelMesajlar } from './aaroKayitSonucAaroModullerUrOperasyonKayitSadeKayitModelMesajlar';

export interface AaroKayitSonucAaroModullerUrOperasyonKayitSadeKayitModel {
  Model?: AaroModullerUrOperasyonKayitSadeKayitModel;
  Mesajlar?: AaroKayitSonucAaroModullerUrOperasyonKayitSadeKayitModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
