/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerUrAkisOperasyonKayitSadeKayitModel } from './aaroModullerUrAkisOperasyonKayitSadeKayitModel';
import type { AaroKayitSonucAaroModullerUrAkisOperasyonKayitSadeKayitModelMesajlar } from './aaroKayitSonucAaroModullerUrAkisOperasyonKayitSadeKayitModelMesajlar';

export interface AaroKayitSonucAaroModullerUrAkisOperasyonKayitSadeKayitModel {
  Model?: AaroModullerUrAkisOperasyonKayitSadeKayitModel;
  Mesajlar?: AaroKayitSonucAaroModullerUrAkisOperasyonKayitSadeKayitModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
