/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export interface AaroMVCControllersWebApiSiparisCariKalem {
  /** Siparişin teslim edileceği fiziksel sevk adresi ID'si. */
  CariAdresID?: number;
  /** Ana cari altındaki alt departman veya şube referans ID'si. */
  CariDetayID?: number;
  /** Sipariş üzerindeki perakende müşterinin adı. */
  MuhtelifCariAdi?: string;
  /** Muhtelif müşteri için vergi veya kimlik numarası. */
  MuhtelifVergiNo?: string;
  /** Muhtelif müşterinin vergi dairesi bilgisi. */
  MuhtelifVergiDairesi?: string;
  /** Muhtelif müşterinin açık adresi. */
  MuhtelifAdres?: string;
  /** Muhtelif müşterinin telefon numarası. */
  MuhtelifTel?: string;
  /** Havale veya EFT gibi banka işlemleri için cari hesaba bağlı Cari'nin banka ID'si. */
  CariBankaID?: number;
  /** Sektörel raporlama (BA/BS) için baz alınacak brüt tutar. */
  BABSTutar?: number;
  /** Finansal nakit akış planlamasında eşleşen beklenen ödeme/tahsilat ID'si. */
  BeklenenTahsilatOdemeID?: number;
}
