/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerPerMesaiHareketDetayKayitSadeKayitModelTipID } from './aaroModullerPerMesaiHareketDetayKayitSadeKayitModelTipID';

export interface AaroModullerPerMesaiHareketDetayKayitSadeKayitModel {
  StrID?: number;
  PersonelID?: number;
  Baslangic?: Date;
  Bitis?: Date;
  ToplamSure?: number;
  HesaplananSure?: number;
  MolaSure?: number;
  MesaiOncesiSayilmayanSure?: number;
  MesaiSonrasiSayilmayanSure?: number;
  TipID?: AaroModullerPerMesaiHareketDetayKayitSadeKayitModelTipID;
}
