/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type AaroKayitSonucAaroModullerSeriLotHareketleriKayitSadeKayitModelMesajlar = {[key: string]: string};
