/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type AaroModullerAlisIadeIrsaliyesiListeListeModelEFaturaTurID = typeof AaroModullerAlisIadeIrsaliyesiListeListeModelEFaturaTurID[keyof typeof AaroModullerAlisIadeIrsaliyesiListeListeModelEFaturaTurID];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AaroModullerAlisIadeIrsaliyesiListeListeModelEFaturaTurID = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;
