/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export interface AaroModullerCariKayitSadeCariEntegrasyonTanimKayitModel {
  EntegrasyonTanimID?: number;
  EntegrasyonKodu?: string;
  EntegrasyonAdi?: string;
  AlisMuhasebeID?: number;
  AlisHesapKodu?: string;
  AlisHesapAdi?: string;
  SatisMuhasebeID?: number;
  SatisHesapKodu?: string;
  SatisHesapAdi?: string;
}
