/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerKartlarUrBenzerlikKayitSadeListeModelOnayDurum } from './aaroModullerKartlarUrBenzerlikKayitSadeListeModelOnayDurum';

export interface AaroModullerKartlarUrBenzerlikKayitSadeListeModel {
  SubeKodu?: string;
  SubeAdi?: string;
  SirketKodu?: string;
  SirketAdi?: string;
  OnayDurum?: AaroModullerKartlarUrBenzerlikKayitSadeListeModelOnayDurum;
  OlsTar?: Date;
  DgsTar?: Date;
  OlsID?: number;
  OlsKodu?: string;
  OlsAdi?: string;
  DgsID?: number;
  DgsKodu?: string;
  DgsAdi?: string;
  SablonKodu?: string;
  SablonAdi?: string;
  ResimAdresi?: string;
  EsnekAramaKisiti?: string;
  SirketSube?: string;
  BenzerlikID?: number;
  BenzerlikAdi?: string;
  BenzerlikKodu?: string;
  Aciklama?: string;
  Renk?: string;
  Sekil?: number;
  SirketID?: number;
  SubeID?: number;
  Durum?: boolean;
  SablonID?: number;
}
