/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModellerFiyatBulSonuc } from './aaroModellerFiyatBulSonuc';
import type { AaroKayitSonucAaroModellerFiyatBulSonucMesajlar } from './aaroKayitSonucAaroModellerFiyatBulSonucMesajlar';

export interface AaroKayitSonucAaroModellerFiyatBulSonuc {
  Model?: AaroModellerFiyatBulSonuc;
  Mesajlar?: AaroKayitSonucAaroModellerFiyatBulSonucMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
