/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';
import type { AaroModullerCariKayitSadeMinModel } from './aaroModullerCariKayitSadeMinModel';
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariKayitSadeMinModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariKayitSadeMinModelMesajlar';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariKayitSadeMinModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerCariKayitSadeMinModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerCariKayitSadeMinModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
