/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';
import type { AaroModullerSatisIadeIrsaliyesiListeListeModel } from './aaroModullerSatisIadeIrsaliyesiListeListeModel';
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisIadeIrsaliyesiListeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisIadeIrsaliyesiListeListeModelMesajlar';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisIadeIrsaliyesiListeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerSatisIadeIrsaliyesiListeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSatisIadeIrsaliyesiListeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
