/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerPerGirisCikisKayitSadeListeModelOnayDurum } from './aaroModullerPerGirisCikisKayitSadeListeModelOnayDurum';

export interface AaroModullerPerGirisCikisKayitSadeListeModel {
  OnayDurum?: AaroModullerPerGirisCikisKayitSadeListeModelOnayDurum;
  OlsTar?: Date;
  DgsTar?: Date;
  OlsID?: number;
  OlsKodu?: string;
  OlsAdi?: string;
  DgsID?: number;
  DgsKodu?: string;
  DgsAdi?: string;
  PersonelAdiSoyadi?: string;
  SicilAciklama?: string;
  CikisNedenSSKAciklama?: string;
  CikisNedenSSKKodu?: number;
  CikisNedenKodu?: number;
  PersonelKodu?: string;
  StrID?: number;
  PerSirketSicilID?: number;
  PersonelID?: number;
  GirisTarihi?: Date;
  CikisTarihi?: Date;
  CikisNedenSSKID?: number;
  CikisNedenID?: number;
  Aciklama?: string;
  Ihbar?: boolean;
  Kidem?: boolean;
  IzinParasi?: boolean;
  KidemBasTarihi?: Date;
  OzlukBasTarihi?: Date;
}
