/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export interface AaroModullerUrReceteKayitSadeReceteDetayViewModel {
  ReceteKodu?: string;
  ReceteAdi?: string;
  OperasyonKodu?: string;
  OperasyonAdi?: string;
  StokKodu?: string;
  StokAdi?: string;
  Miktar?: number;
  BirimKodu?: string;
  BirimMaliyetFiyati?: number;
  Tutar?: number;
  MakineKodu?: string;
  MakineAdi?: string;
  IsciAdedi?: number;
  HazirlikSure?: number;
  UretimSure?: number;
  IscilikMaliyetiSaat?: number;
  CalismaMaliyetiSaat?: number;
  OperasyonAciklama?: string;
  IsEmriID?: number;
  ReceteID?: number;
  ReceteOperasyonID?: number;
  Tip?: string;
  HemMamulHemHammadde?: boolean;
  Derinlik?: number;
  Derinlik2?: number;
  SonrakiReceteOperasyonID?: number;
  ReceteOperasyonMamulID?: number;
  ReceteOperasyonHammaddeID?: number;
  StokID?: number;
  OperasyonID?: number;
  MakineID?: number;
  SiraKodu?: string;
}
