/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerKartlarUrBenzerlikKayitSadeKayitModel } from './aaroModullerKartlarUrBenzerlikKayitSadeKayitModel';
import type { AaroKayitSonucAaroModullerKartlarUrBenzerlikKayitSadeKayitModelMesajlar } from './aaroKayitSonucAaroModullerKartlarUrBenzerlikKayitSadeKayitModelMesajlar';

export interface AaroKayitSonucAaroModullerKartlarUrBenzerlikKayitSadeKayitModel {
  Model?: AaroModullerKartlarUrBenzerlikKayitSadeKayitModel;
  Mesajlar?: AaroKayitSonucAaroModullerKartlarUrBenzerlikKayitSadeKayitModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
