/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerUrIsEmriKayitSadeListeModelOnayDurum } from './aaroModullerUrIsEmriKayitSadeListeModelOnayDurum';
import type { AaroModullerUrIsEmriKayitSadeListeModelUretimDurumu } from './aaroModullerUrIsEmriKayitSadeListeModelUretimDurumu';
import type { AaroModullerUrIsEmriKayitSadeListeModelTipID } from './aaroModullerUrIsEmriKayitSadeListeModelTipID';

export interface AaroModullerUrIsEmriKayitSadeListeModel {
  SubeKodu?: string;
  SubeAdi?: string;
  SirketKodu?: string;
  SirketAdi?: string;
  OnayDurum?: AaroModullerUrIsEmriKayitSadeListeModelOnayDurum;
  OlsTar?: Date;
  DgsTar?: Date;
  OlsID?: number;
  OlsKodu?: string;
  OlsAdi?: string;
  DgsID?: number;
  DgsKodu?: string;
  DgsAdi?: string;
  PlanlanmisMi?: boolean;
  StokID?: number;
  StokAdi?: string;
  BirimKodu?: string;
  MiktarUretilen?: number;
  Kod1ID?: number;
  Kod2ID?: number;
  Kod3ID?: number;
  Kod4ID?: number;
  Kod5ID?: number;
  Kod6ID?: number;
  UretimDurumu?: AaroModullerUrIsEmriKayitSadeListeModelUretimDurumu;
  UretimOrani?: number;
  SiparisNo?: string;
  Tutar?: number;
  CariID?: number;
  TamamlanmaOrani?: number;
  BirimAdi?: string;
  BirimID?: number;
  DovizID?: number;
  DovizAdi?: string;
  CariAdi?: string;
  DekontID?: number;
  EsnekAramaKisiti?: string;
  IsEmriID?: number;
  SubeID?: number;
  SirketID?: number;
  IsEmriNo?: string;
  Tarih?: Date;
  TeslimTarihi?: Date;
  TipID?: AaroModullerUrIsEmriKayitSadeListeModelTipID;
  Oncelik?: number;
  ProjeID?: number;
  Kapali?: boolean;
  AciklamalarID?: number;
  Renk?: string;
  ReceteID?: number;
  ReceteAdi?: string;
  ReceteKodu?: string;
  Miktar?: number;
  YedekD1?: number;
  YedekD2?: number;
  YedekD3?: number;
  YedekS1?: string;
  YedekS2?: string;
  YedekS3?: string;
  Aciklama?: string;
  HareketID?: number;
  PlanKilit?: boolean;
  AltReceteSeviye?: number;
  AltRecetelereIsEmriVerilsinMi?: boolean;
}
