/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export interface AaroModullerGorevHareketleriKayitSadeKayitModel {
  GorevHareketleriSatirID?: number;
  GorevID?: number;
  KullaniciID?: number;
  GorulduTarihBas?: Date;
  BaslandiTarihBas?: Date;
  TamamlandiTarihBas?: Date;
  IadeEdildiTarihBas?: Date;
  IadeAciklama?: string;
}
