/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerPerGirisCikisKayitSadeListeModel } from './aaroModullerPerGirisCikisKayitSadeListeModel';
import type { AaroKayitSonucAaroModullerPerGirisCikisKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerPerGirisCikisKayitSadeListeModelMesajlar';

export interface AaroKayitSonucAaroModullerPerGirisCikisKayitSadeListeModel {
  Model?: AaroModullerPerGirisCikisKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerPerGirisCikisKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
