/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerPerOnayBaslikKayitSadeListeModel } from './aaroModullerPerOnayBaslikKayitSadeListeModel';
import type { AaroKayitSonucAaroModullerPerOnayBaslikKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerPerOnayBaslikKayitSadeListeModelMesajlar';

export interface AaroKayitSonucAaroModullerPerOnayBaslikKayitSadeListeModel {
  Model?: AaroModullerPerOnayBaslikKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerPerOnayBaslikKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
