/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export interface AaroModullerStokSayimKayitSadeKayitModel {
  SayimID?: number;
  DepoID?: number;
  ProjeID?: number;
  PlasiyerID?: number;
  SirketID?: number;
  SubeID?: number;
  Tarih?: Date;
  Durum?: boolean;
  Aciklama?: string;
}
