/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerSozlesmeKayitSadeKayitModel } from './aaroModullerSozlesmeKayitSadeKayitModel';
import type { AaroKayitSonucAaroModullerSozlesmeKayitSadeKayitModelMesajlar } from './aaroKayitSonucAaroModullerSozlesmeKayitSadeKayitModelMesajlar';

export interface AaroKayitSonucAaroModullerSozlesmeKayitSadeKayitModel {
  Model?: AaroModullerSozlesmeKayitSadeKayitModel;
  Mesajlar?: AaroKayitSonucAaroModullerSozlesmeKayitSadeKayitModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
