/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';
import type { AaroModullerGorevKullanicilariKayitSadeListeModel } from './aaroModullerGorevKullanicilariKayitSadeListeModel';
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerGorevKullanicilariKayitSadeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerGorevKullanicilariKayitSadeListeModelMesajlar';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerGorevKullanicilariKayitSadeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerGorevKullanicilariKayitSadeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerGorevKullanicilariKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
