/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export interface AaroModullerPerGirisCikisKayitSadeKayitModel {
  StrID?: number;
  PerSirketSicilID?: number;
  PersonelID?: number;
  GirisTarihi?: Date;
  CikisTarihi?: Date;
  CikisNedenSSKID?: number;
  CikisNedenID?: number;
  Aciklama?: string;
  Ihbar?: boolean;
  Kidem?: boolean;
  IzinParasi?: boolean;
  KidemBasTarihi?: Date;
  OzlukBasTarihi?: Date;
}
