/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export interface AaroModullerSubelerKayitSadeListeModel {
  SirketKodu?: string;
  SirketAdi?: string;
  IlceKodu?: string;
  IlceAdi?: string;
  EsnekAramaKisiti?: string;
  SubeID?: number;
  SubeKodu?: string;
  SubeAdi?: string;
  SubeUzunAdi?: string;
  SirketID?: number;
  Adres?: string;
  IlceID?: number;
}
