/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';
import type { AaroMVCControllersWebApiBaslikModel } from './aaroMVCControllersWebApiBaslikModel';
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroMVCControllersWebApiBaslikModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroMVCControllersWebApiBaslikModelMesajlar';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroMVCControllersWebApiBaslikModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroMVCControllersWebApiBaslikModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroMVCControllersWebApiBaslikModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
