/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerBankaHesapKayitSadeDetayliKayitModelAPI } from './aaroModullerBankaHesapKayitSadeDetayliKayitModelAPI';
import type { AaroKayitSonucAaroModullerBankaHesapKayitSadeDetayliKayitModelAPIMesajlar } from './aaroKayitSonucAaroModullerBankaHesapKayitSadeDetayliKayitModelAPIMesajlar';

export interface AaroKayitSonucAaroModullerBankaHesapKayitSadeDetayliKayitModelAPI {
  Model?: AaroModullerBankaHesapKayitSadeDetayliKayitModelAPI;
  Mesajlar?: AaroKayitSonucAaroModullerBankaHesapKayitSadeDetayliKayitModelAPIMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
