/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerDepoKayitSadeKayitModel } from './aaroModullerDepoKayitSadeKayitModel';
import type { AaroKayitSonucAaroModullerDepoKayitSadeKayitModelMesajlar } from './aaroKayitSonucAaroModullerDepoKayitSadeKayitModelMesajlar';

export interface AaroKayitSonucAaroModullerDepoKayitSadeKayitModel {
  Model?: AaroModullerDepoKayitSadeKayitModel;
  Mesajlar?: AaroKayitSonucAaroModullerDepoKayitSadeKayitModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
