/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';
import type { AaroModullerPerOnayBaslikKayitSadeListeModel } from './aaroModullerPerOnayBaslikKayitSadeListeModel';
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerPerOnayBaslikKayitSadeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerPerOnayBaslikKayitSadeListeModelMesajlar';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerPerOnayBaslikKayitSadeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerPerOnayBaslikKayitSadeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerPerOnayBaslikKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
