/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';
import type { AaroModullerAlisIrsaliyesiListeListeModel } from './aaroModullerAlisIrsaliyesiListeListeModel';
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerAlisIrsaliyesiListeListeModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerAlisIrsaliyesiListeListeModelMesajlar';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerAlisIrsaliyesiListeListeModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroModullerAlisIrsaliyesiListeListeModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerAlisIrsaliyesiListeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
