/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerUrReceteKayitSadeListeModel } from './aaroModullerUrReceteKayitSadeListeModel';
import type { AaroKayitSonucAaroModullerUrReceteKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerUrReceteKayitSadeListeModelMesajlar';

export interface AaroKayitSonucAaroModullerUrReceteKayitSadeListeModel {
  Model?: AaroModullerUrReceteKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerUrReceteKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
