/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerKullanicilarKayitSadeKayitModel } from './aaroModullerKullanicilarKayitSadeKayitModel';
import type { AaroKayitSonucAaroModullerKullanicilarKayitSadeKayitModelMesajlar } from './aaroKayitSonucAaroModullerKullanicilarKayitSadeKayitModelMesajlar';

export interface AaroKayitSonucAaroModullerKullanicilarKayitSadeKayitModel {
  Model?: AaroModullerKullanicilarKayitSadeKayitModel;
  Mesajlar?: AaroKayitSonucAaroModullerKullanicilarKayitSadeKayitModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
