/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerUrAkisOperasyonPersonelKayitSadeKayitModel } from './aaroModullerUrAkisOperasyonPersonelKayitSadeKayitModel';
import type { AaroKayitSonucAaroModullerUrAkisOperasyonPersonelKayitSadeKayitModelMesajlar } from './aaroKayitSonucAaroModullerUrAkisOperasyonPersonelKayitSadeKayitModelMesajlar';

export interface AaroKayitSonucAaroModullerUrAkisOperasyonPersonelKayitSadeKayitModel {
  Model?: AaroModullerUrAkisOperasyonPersonelKayitSadeKayitModel;
  Mesajlar?: AaroKayitSonucAaroModullerUrAkisOperasyonPersonelKayitSadeKayitModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
