/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroMVCControllersWebApiStokKalemBrmFiyatTipi } from './aaroMVCControllersWebApiStokKalemBrmFiyatTipi';
import type { AaroModellerStokHareketleriVergiDetaylari } from './aaroModellerStokHareketleriVergiDetaylari';

export interface AaroMVCControllersWebApiStokKalem {
  /** Ürünün iskontolar düşüldükten sonraki net birim alış/satış fiyatı. */
  BrmFiyatN?: number;
  /** Ürünün iskontolar öncesi brüt birim alış/satış fiyatı. */
  BrmFiyatB?: number;
  /** Fiyatın birim tipini (Net mi, Brüt mü?) belirleyen parametre. */
  BrmFiyatTipi?: AaroMVCControllersWebApiStokKalemBrmFiyatTipi;
  /** True ise sistemin otomatik hesapladığı fiyat yerine kullanıcının girdiği manuel brüt fiyat baz alınır. */
  BrutBirimFiyatManuelAtansin?: boolean;
  /** Vergi kalemi hareketlerinde (KDV, ÖTV) kullanılan vergi alt tanımlama ID'si. */
  VergiAltID?: number;
  /** Kaleme uygulanan dinamik vergi oranı (Örn: %20). */
  VergiOran?: number;
  /** Ürünün varyant (renk, beden, seri no, parti no) bazlı alt kimlik ID'si. */
  StokDetayID?: number;
  /** Ürünün çıktığı veya girdiği fiziksel stok lokasyon ID'si. */
  DepoID?: number;
  /** Stok hareketinin özel olarak ilişkilendirildiği CariID. */
  CariID?: number;
  /** Masraf veya gider kaleminin hangi personelin/carinin hesabına kaydedileceği. */
  GelirGiderCariID?: number;
  /** İşlemin ilişkilendirildiği Sabit Kıymet (Demirbaş) kart ID'si. */
  DemirbasID?: number;
  /** İşlemin bağlı olduğu finansal belge (Dekont) referansı. */
  GelirGiderDekontID?: number;
  /** Maliyetin yüklendiği operasyonel departman veya proje masraf merkezi ID'si. */
  MasrafMerkeziID?: number;
  /** True ise bu satır sistem tarafından otomatik üretilmiştir (Örn: Otomatik nakliye veya kampanya bedeli). */
  OtomatikKalem?: boolean;
  /** Kaleme uygulanan promosyon veya kampanya kural ID'si. */
  PromosyonID?: number;
  /** Satırın bir ürün paketinden (set) geldiği durumdaki PaketID referansı. */
  PaketID?: number;
  /** Kalemin sevk edildiği veya kaynaklandığı İrsaliye ID'si. */
  IrsaliyeID?: number;
  /** Lojistik planlamadaki sevkiyat/yükleme organizasyon ID'si. */
  YuklemeID?: number;
  /** Sevkiyatı gerçekleştiren lojistik firması (Nakliye) ID'si. */
  NakliyeID?: number;
  /** Faturanın kaynaklandığı orijinal sipariş satırı (hareket) ID'si. */
  SiparisHareketID?: number;
  /** Giriş kalite kontrol (Depo Kabul) süreci referans ID'si. */
  DepoKabulID?: number;
  /** İskontonun tutar bazlı mı yoksa yüzde bazlı mı hesaplanacağı kuralı. */
  IskontoTipi?: boolean;
  /** Kaleme uygulanan genel kampanya/liste iskonto oranı. */
  IskontoOrani?: number;
  /** Ödeme vadesine bağlı olarak uygulanan vade indirimi oranı. */
  VadeIskontoOrani?: number;
  /** Satış temsilcisi tarafından yerinde uygulanan ekstra (extra) iskonto oranı. */
  KullaniciIskontoOrani?: number;
  /** Depolar arası transfer işleminin karşı bacak (giriş/çıkış) hareket ID'si. */
  TransferHareketID?: number;
  /** Dış ticaret proje dosya ID'si (Import/Export). */
  IthalatIhracatID?: number;
  /** Hiyerarşik (takım/set) stok hareketlerinde ana parça/kalem ID'si. */
  UstHareketID?: number;
  /** Gelen e-Faturadaki orijinal stok açıklama metinleri. */
  GelenEFaturaStokBilgileri?: string;
  /** Ürün satırına uygulanan tüm vergilerin (KDV, ÖTV vb.) detaylandırılmış listesi. */
  VergiDetaylari?: AaroModellerStokHareketleriVergiDetaylari[];
}
