/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerGorevKullanicilariKayitSadeListeModel } from './aaroModullerGorevKullanicilariKayitSadeListeModel';
import type { AaroKayitSonucAaroModullerGorevKullanicilariKayitSadeListeModelMesajlar } from './aaroKayitSonucAaroModullerGorevKullanicilariKayitSadeListeModelMesajlar';

export interface AaroKayitSonucAaroModullerGorevKullanicilariKayitSadeListeModel {
  Model?: AaroModullerGorevKullanicilariKayitSadeListeModel;
  Mesajlar?: AaroKayitSonucAaroModullerGorevKullanicilariKayitSadeListeModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
