/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroSayfalandirmaBilgisi } from './aaroSayfalandirmaBilgisi';
import type { AaroMVCControllersWebApiKodlarBayiModel } from './aaroMVCControllersWebApiKodlarBayiModel';
import type { AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroMVCControllersWebApiKodlarBayiModelMesajlar } from './aaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroMVCControllersWebApiKodlarBayiModelMesajlar';

export interface AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroMVCControllersWebApiKodlarBayiModel {
  SayfalandirmaBilgisi?: AaroSayfalandirmaBilgisi;
  Model?: AaroMVCControllersWebApiKodlarBayiModel[];
  Mesajlar?: AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroMVCControllersWebApiKodlarBayiModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
