/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerNotlarKayitSadeListeModelTipID } from './aaroModullerNotlarKayitSadeListeModelTipID';
import type { AaroModullerNotlarKayitSadeListeModelTabloID } from './aaroModullerNotlarKayitSadeListeModelTabloID';

export interface AaroModullerNotlarKayitSadeListeModel {
  SubeKodu?: string;
  SubeAdi?: string;
  SirketKodu?: string;
  SirketAdi?: string;
  TipAdi?: string;
  TipKodu?: string;
  TabloAdi?: string;
  OlsKodu?: string;
  OlsAdi?: string;
  EsnekAramaKisiti?: string;
  NotID?: number;
  TabloSatirID?: number;
  Notu?: string;
  SubeID?: number;
  SirketID?: number;
  TipID?: AaroModullerNotlarKayitSadeListeModelTipID;
  TabloID?: AaroModullerNotlarKayitSadeListeModelTabloID;
  OlsTar?: Date;
  OlsID?: number;
}
