/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerYetkilerKayitSadeKayitModel } from './aaroModullerYetkilerKayitSadeKayitModel';
import type { AaroKayitSonucAaroModullerYetkilerKayitSadeKayitModelMesajlar } from './aaroKayitSonucAaroModullerYetkilerKayitSadeKayitModelMesajlar';

export interface AaroKayitSonucAaroModullerYetkilerKayitSadeKayitModel {
  Model?: AaroModullerYetkilerKayitSadeKayitModel;
  Mesajlar?: AaroKayitSonucAaroModullerYetkilerKayitSadeKayitModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
