/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerParametrelerSirketSubeKayitSadeListeModelParametreID } from './aaroModullerParametrelerSirketSubeKayitSadeListeModelParametreID';

export interface AaroModullerParametrelerSirketSubeKayitSadeListeModel {
  ParametreAdi?: string;
  StrID?: number;
  ParametreID?: AaroModullerParametrelerSirketSubeKayitSadeListeModelParametreID;
  SirketID?: number;
  SubeID?: number;
  Deger?: string;
}
