/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { AaroModullerDisardanAktarimEkKodlarExcelModel } from './aaroModullerDisardanAktarimEkKodlarExcelModel';
import type { AaroKayitSonucAaroModullerDisardanAktarimEkKodlarExcelModelMesajlar } from './aaroKayitSonucAaroModullerDisardanAktarimEkKodlarExcelModelMesajlar';

export interface AaroKayitSonucAaroModullerDisardanAktarimEkKodlarExcelModel {
  Model?: AaroModullerDisardanAktarimEkKodlarExcelModel;
  Mesajlar?: AaroKayitSonucAaroModullerDisardanAktarimEkKodlarExcelModelMesajlar;
  Sonuc?: boolean;
  Detay?: string;
}
