/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type DekontZorunluDemirbasCariPostParams = {
/**
 * Kısıt ve zorunluluk kuralları kontrol edilecek stok/hizmet kartının sistem ID'si.
 */
StokID: number;
};
