/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { DepoDegisiklikGecmisiGetKisitKayitTipi } from './depoDegisiklikGecmisiGetKisitKayitTipi';
import type { DepoDegisiklikGecmisiGetKisitTabloID } from './depoDegisiklikGecmisiGetKisitTabloID';

export type DepoDegisiklikGecmisiGetParams = {
'Kisit.kulAdi'?: string;
'Kisit.kulKodu'?: string;
'Kisit.degisiklikLogID'?: number;
'Kisit.tarih'?: Date;
'Kisit.kayitTipi'?: DepoDegisiklikGecmisiGetKisitKayitTipi;
'Kisit.kullaniciID'?: number;
'Kisit.tabloID'?: DepoDegisiklikGecmisiGetKisitTabloID;
'Kisit.tabloSatirID'?: number;
'Kisit.sutunAdi'?: string;
'Kisit.eskiVeri'?: string;
'Kisit.yeniVeri'?: string;
'Kisit.dekontID'?: number;
/**
 * Listeleme işlemlerinde sıralama için kullanılacak kısıtı belirtir.
Örneğin, "Tarih", "Tarih:desc", "Tarih,Adi", "Tarih:desc,Adi" gibi bir değer alabilir.
 */
'SayfalandirmaBilgisi.siralamaKisiti'?: string;
/**
 * Geçerli sayfa numarasını (1'den başlar) alır veya ayarlar.
 */
'SayfalandirmaBilgisi.sayfa'?: number;
/**
 * Sayfa başına satır sayısını alır veya ayarlar. maxSayfaSatirSayisi değerini aşamaz.
 */
'SayfalandirmaBilgisi.sayfaSatirSayisi'?: number;
};
