/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { FiyatListesiListeGetGetKisitOnayDurum } from './fiyatListesiListeGetGetKisitOnayDurum';
import type { FiyatListesiListeGetGetKisitTipID } from './fiyatListesiListeGetGetKisitTipID';

export type FiyatListesiListeGetGetParams = {
'Kisit.subeKodu'?: string;
'Kisit.subeAdi'?: string;
'Kisit.sirketKodu'?: string;
'Kisit.sirketAdi'?: string;
'Kisit.tipAdi'?: string;
'Kisit.tipKodu'?: string;
'Kisit.onayDurum'?: FiyatListesiListeGetGetKisitOnayDurum;
'Kisit.olsTar'?: Date;
'Kisit.dgsTar'?: Date;
'Kisit.olsID'?: number;
'Kisit.olsKodu'?: string;
'Kisit.olsAdi'?: string;
'Kisit.dgsID'?: number;
'Kisit.dgsKodu'?: string;
'Kisit.dgsAdi'?: string;
'Kisit.etiket1Adi'?: string;
'Kisit.etiket2Adi'?: string;
'Kisit.etiket3Adi'?: string;
'Kisit.etiket4Adi'?: string;
'Kisit.etiket5Adi'?: string;
'Kisit.sablonKodu'?: string;
'Kisit.sablonAdi'?: string;
'Kisit.esnekAramaKisiti'?: string;
'Kisit.fiyatListesiID'?: number;
'Kisit.kodu'?: string;
'Kisit.adi'?: string;
'Kisit.vade'?: number;
'Kisit.tarihBas'?: Date;
'Kisit.tarihBit'?: Date;
'Kisit.subeID'?: number;
'Kisit.sirketID'?: number;
'Kisit.durum'?: boolean;
'Kisit.tipID'?: FiyatListesiListeGetGetKisitTipID;
'Kisit.etiket1ID'?: number;
'Kisit.etiket2ID'?: number;
'Kisit.etiket3ID'?: number;
'Kisit.etiket4ID'?: number;
'Kisit.etiket5ID'?: number;
/**
 * Listeleme işlemlerinde sıralama için kullanılacak kısıtı belirtir.
Örneğin, "Tarih", "Tarih:desc", "Tarih,Adi", "Tarih:desc,Adi" gibi bir değer alabilir.
 */
'SayfalandirmaBilgisi.siralamaKisiti'?: string;
/**
 * Geçerli sayfa numarasını (1'den başlar) alır veya ayarlar.
 */
'SayfalandirmaBilgisi.sayfa'?: number;
/**
 * Sayfa başına satır sayısını alır veya ayarlar. maxSayfaSatirSayisi değerini aşamaz.
 */
'SayfalandirmaBilgisi.sayfaSatirSayisi'?: number;
};
