/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type KaliteKontrolBaslikDetayliListeGetKisitTipIDTuru = typeof KaliteKontrolBaslikDetayliListeGetKisitTipIDTuru[keyof typeof KaliteKontrolBaslikDetayliListeGetKisitTipIDTuru];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KaliteKontrolBaslikDetayliListeGetKisitTipIDTuru = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
