/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { KullanicilarListeGetGetKisitOnayDurum } from './kullanicilarListeGetGetKisitOnayDurum';

export type KullanicilarListeGetGetParams = {
'Kisit.grupAdi'?: string;
'Kisit.grupKodu'?: string;
'Kisit.personelAdi'?: string;
'Kisit.personelKodu'?: string;
'Kisit.onayDurum'?: KullanicilarListeGetGetKisitOnayDurum;
'Kisit.olsTar'?: Date;
'Kisit.dgsTar'?: Date;
'Kisit.olsID'?: number;
'Kisit.olsKodu'?: string;
'Kisit.olsAdi'?: string;
'Kisit.dgsID'?: number;
'Kisit.dgsKodu'?: string;
'Kisit.dgsAdi'?: string;
'Kisit.etiket1Adi'?: string;
'Kisit.etiket2Adi'?: string;
'Kisit.etiket3Adi'?: string;
'Kisit.etiket4Adi'?: string;
'Kisit.etiket5Adi'?: string;
'Kisit.depoAdi'?: string;
'Kisit.depoKodu'?: string;
'Kisit.makineAdi'?: string;
'Kisit.makineKodu'?: string;
'Kisit.bayiCariAdi'?: string;
'Kisit.bayiCariKodu'?: string;
'Kisit.esnekAramaKisiti'?: string;
'Kisit.kulID'?: number;
'Kisit.kulKodu'?: string;
'Kisit.kulAdiSoyadi'?: string;
'Kisit.grupID'?: number;
'Kisit.personelID'?: number;
'Kisit.ePosta'?: string;
'Kisit.telefon'?: string;
'Kisit.durum'?: boolean;
'Kisit.etiket1ID'?: number;
'Kisit.etiket2ID'?: number;
'Kisit.etiket3ID'?: number;
'Kisit.etiket4ID'?: number;
'Kisit.etiket5ID'?: number;
'Kisit.gecmisTarihliCariKayitGunSayisi'?: number;
'Kisit.gelecekTarihliCariKayitGunSayisi'?: number;
'Kisit.gecmisTarihliMuhasebeKayitGunSayisi'?: number;
'Kisit.gelecekTarihliMuhasebeKayitGunSayisi'?: number;
'Kisit.siparisOlusturabilir'?: boolean;
'Kisit.bakiyeGorebilir'?: boolean;
'Kisit.hareketGorebilir'?: boolean;
'Kisit.anaSayfaIntroGorebilir'?: boolean;
'Kisit.cariKayitIntroGorebilir'?: boolean;
'Kisit.faturaKayitIntroGorebilir'?: boolean;
'Kisit.stokKayitIntroGorebilir'?: boolean;
'Kisit.gorulenSonGuncellemeTarihi'?: Date;
'Kisit.oturumBaslangicSaatiPazartesi'?: Date;
'Kisit.oturumBitisSaatiPazartesi'?: Date;
'Kisit.oturumBaslangicSaatiSali'?: Date;
'Kisit.oturumBitisSaatiSali'?: Date;
'Kisit.oturumBaslangicSaatiCarsamba'?: Date;
'Kisit.oturumBitisSaatiCarsamba'?: Date;
'Kisit.oturumBaslangicSaatiPersembe'?: Date;
'Kisit.oturumBitisSaatiPersembe'?: Date;
'Kisit.oturumBaslangicSaatiCuma'?: Date;
'Kisit.oturumBitisSaatiCuma'?: Date;
'Kisit.oturumBaslangicSaatiCumartesi'?: Date;
'Kisit.oturumBitisSaatiCumartesi'?: Date;
'Kisit.oturumBaslangicSaatiPazar'?: Date;
'Kisit.oturumBitisSaatiPazar'?: Date;
'Kisit.depoID'?: number;
'Kisit.urMakineID'?: number;
'Kisit.bayiCariID'?: number;
/**
 * Listeleme işlemlerinde sıralama için kullanılacak kısıtı belirtir.
Örneğin, "Tarih", "Tarih:desc", "Tarih,Adi", "Tarih:desc,Adi" gibi bir değer alabilir.
 */
'SayfalandirmaBilgisi.siralamaKisiti'?: string;
/**
 * Geçerli sayfa numarasını (1'den başlar) alır veya ayarlar.
 */
'SayfalandirmaBilgisi.sayfa'?: number;
/**
 * Sayfa başına satır sayısını alır veya ayarlar. maxSayfaSatirSayisi değerini aşamaz.
 */
'SayfalandirmaBilgisi.sayfaSatirSayisi'?: number;
};
