/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type LinqFilteringSortingInfoDirection = typeof LinqFilteringSortingInfoDirection[keyof typeof LinqFilteringSortingInfoDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LinqFilteringSortingInfoDirection = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
