/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { LinqFilteringFilterCriteria } from './linqFilteringFilterCriteria';
import type { LinqFilteringSortingInfo } from './linqFilteringSortingInfo';

export interface LinqFilteringAdvancedFilterRequest {
  Filters?: LinqFilteringFilterCriteria[];
  Sorting?: LinqFilteringSortingInfo[];
  Page?: number;
  PageSize?: number;
}
