/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type MuhasebeListeGetGetKisitOnayDurum = typeof MuhasebeListeGetGetKisitOnayDurum[keyof typeof MuhasebeListeGetGetKisitOnayDurum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MuhasebeListeGetGetKisitOnayDurum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_MINUS_1: -1,
} as const;
