/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */

export type PlasiyerGrupluListeGetParams = {
/**
 * Gruplanacak alan adları, virgülle ayrılmış. Örnek: "Sehir,GrupAdi"
 */
Gruplar: string;
/**
 * Hesaplanacak değer alanları, virgülle ayrılmış. Örnek: "Bakiye,KayitSayisi"
 */
Degerler: string;
/**
 * Gruplama öncesi uygulanacak filtre. ListeEsnek filtre formatıyla aynıdır.
 */
Kisit: string;
};
