/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { SeriLotHareketleriListeGetGetKisitTipID } from './seriLotHareketleriListeGetGetKisitTipID';
import type { SeriLotHareketleriListeGetGetKisitOnayDurum } from './seriLotHareketleriListeGetGetKisitOnayDurum';

export type SeriLotHareketleriListeGetGetParams = {
'Kisit.seriLotKodu'?: string;
'Kisit.seriLotAdi'?: string;
'Kisit.stokRafKodu'?: string;
'Kisit.stokRafAdi'?: string;
'Kisit.paketKodu'?: string;
'Kisit.paketAdi'?: string;
'Kisit.isEmriNo'?: string;
'Kisit.subeID'?: number;
'Kisit.subeKodu'?: string;
'Kisit.subeAdi'?: string;
'Kisit.sirketID'?: number;
'Kisit.sirketKodu'?: string;
'Kisit.sirketAdi'?: string;
'Kisit.stokID'?: number;
'Kisit.stokKodu'?: string;
'Kisit.stokAdi'?: string;
'Kisit.tipID'?: SeriLotHareketleriListeGetGetKisitTipID;
'Kisit.tipKodu'?: string;
'Kisit.tipAdi'?: string;
'Kisit.brm1Kodu'?: string;
'Kisit.bakiyeMiktar'?: number;
'Kisit.onayDurum'?: SeriLotHareketleriListeGetGetKisitOnayDurum;
'Kisit.olsTar'?: Date;
'Kisit.dgsTar'?: Date;
'Kisit.olsID'?: number;
'Kisit.olsKodu'?: string;
'Kisit.olsAdi'?: string;
'Kisit.dgsID'?: number;
'Kisit.dgsKodu'?: string;
'Kisit.dgsAdi'?: string;
'Kisit.uretimTarihi'?: Date;
'Kisit.sonKullanmaTarihi'?: Date;
'Kisit.urunKalanOmru'?: number;
'Kisit.depoKodu'?: string;
'Kisit.depoID'?: number;
'Kisit.tarih'?: Date;
'Kisit.hareketID'?: number;
'Kisit.stokHareketID'?: number;
'Kisit.seriLotID'?: number;
'Kisit.stokRafID'?: number;
'Kisit.paketID'?: number;
'Kisit.bA'?: string;
'Kisit.miktar'?: number;
'Kisit.isEmriID'?: number;
'Kisit.urAkisOperasyonAnaMamulSeriLotID'?: number;
'Kisit.urAkisOperasyonHammaddeID'?: number;
'Kisit.urAkisOperasyonMamulID'?: number;
'Kisit.durum'?: boolean;
'Kisit.aciklama'?: string;
/**
 * Listeleme işlemlerinde sıralama için kullanılacak kısıtı belirtir.
Örneğin, "Tarih", "Tarih:desc", "Tarih,Adi", "Tarih:desc,Adi" gibi bir değer alabilir.
 */
'SayfalandirmaBilgisi.siralamaKisiti'?: string;
/**
 * Geçerli sayfa numarasını (1'den başlar) alır veya ayarlar.
 */
'SayfalandirmaBilgisi.sayfa'?: number;
/**
 * Sayfa başına satır sayısını alır veya ayarlar. maxSayfaSatirSayisi değerini aşamaz.
 */
'SayfalandirmaBilgisi.sayfaSatirSayisi'?: number;
};
