/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { UrAkisOperasyonListeGetGetKisitTipID } from './urAkisOperasyonListeGetGetKisitTipID';

export type UrAkisOperasyonListeGetGetParams = {
'Kisit.hamListStokBirimAd'?: unknown[];
'Kisit.mamListStokBirimAd'?: unknown[];
'Kisit.isEmriNo'?: string;
'Kisit.receteKodu'?: string;
'Kisit.receteAdi'?: string;
'Kisit.operasyonKodu'?: string;
'Kisit.operasyonAdi'?: string;
'Kisit.duraklamaNedenKodu'?: string;
'Kisit.duraklamaNedenAdi'?: string;
'Kisit.makineKodu'?: string;
'Kisit.makineAdi'?: string;
'Kisit.sira'?: number;
'Kisit.olsTar'?: Date;
'Kisit.dgsTar'?: Date;
'Kisit.olsID'?: number;
'Kisit.olsKodu'?: string;
'Kisit.olsAdi'?: string;
'Kisit.dgsID'?: number;
'Kisit.dgsKodu'?: string;
'Kisit.dgsAdi'?: string;
'Kisit.subeID'?: number;
'Kisit.subeKodu'?: string;
'Kisit.subeAdi'?: string;
'Kisit.sirketID'?: number;
'Kisit.sirketKodu'?: string;
'Kisit.sirketAdi'?: string;
'Kisit.tarih'?: Date;
'Kisit.anaMamulAdi'?: string;
'Kisit.anaMamulMiktar'?: number;
'Kisit.receteAnaMamulMiktar'?: number;
'Kisit.receteIsciAdedi'?: number;
'Kisit.receteHazirlikSure'?: number;
'Kisit.receteUretimSureToplam'?: number;
'Kisit.receteUretimSure'?: number;
'Kisit.akisOperasyonMamulID'?: number;
'Kisit.receteOperasyonMamulID'?: number;
'Kisit.siparisDekontID'?: number;
'Kisit.siparisHareketID'?: number;
'Kisit.cariID'?: number;
'Kisit.sonOperasyonMu'?: boolean;
'Kisit.siparisNo'?: string;
'Kisit.mamulAdi'?: string;
'Kisit.miktar'?: number;
'Kisit.receteMiktar'?: number;
'Kisit.fiyat'?: number;
'Kisit.receteFiyat'?: number;
'Kisit.gerceklesenMiktarBoluRecete'?: number;
'Kisit.gerceklesenFiyatBoluRecete'?: number;
'Kisit.siparisFiyatBoluRecete'?: number;
'Kisit.siparisFiyatBoluGerceklesen'?: number;
'Kisit.hazirlikSureBoluRecete'?: number;
'Kisit.uretimSureBoluRecete'?: number;
'Kisit.netHizBoluRecete'?: number;
'Kisit.brutHizBoluRecete'?: number;
'Kisit.isciAdediBoluRecete'?: number;
'Kisit.kod1ID'?: number;
'Kisit.kod2ID'?: number;
'Kisit.kod3ID'?: number;
'Kisit.kod4ID'?: number;
'Kisit.kod5ID'?: number;
'Kisit.kod6ID'?: number;
'Kisit.etiket1ID'?: number;
'Kisit.etiket2ID'?: number;
'Kisit.etiket3ID'?: number;
'Kisit.etiket4ID'?: number;
'Kisit.etiket5ID'?: number;
'Kisit.kaliteKontrolID'?: number;
'Kisit.kaliteKontrolKapaliMi'?: boolean;
'Kisit.stokID'?: number;
'Kisit.personelID'?: number;
'Kisit.kaliteKontrolBaslikKapali'?: boolean;
'Kisit.kaliteKontrolTurID'?: number;
'Kisit.yil'?: number;
'Kisit.ay'?: number;
'Kisit.ceyrek'?: number;
'Kisit.brm2Miktar'?: number;
'Kisit.brm3Miktar'?: number;
'Kisit.brm2Kodu'?: string;
'Kisit.brm3Kodu'?: string;
'Kisit.fireMiktar'?: number;
'Kisit.ilkNumuneKontrol'?: boolean;
'Kisit.yedekD1'?: number;
'Kisit.yedekD2'?: number;
'Kisit.yedekD3'?: number;
'Kisit.yedekS1'?: string;
'Kisit.yedekS2'?: string;
'Kisit.yedekS3'?: string;
'Kisit.akisOperasyonID'?: number;
'Kisit.isEmriID'?: number;
'Kisit.receteOperasyonID'?: number;
'Kisit.receteID'?: number;
'Kisit.operasyonID'?: number;
'Kisit.makineID'?: number;
'Kisit.duraklamaNedenID'?: number;
'Kisit.hazirlikSure'?: number;
'Kisit.uretimSure'?: number;
'Kisit.isciAdedi'?: number;
'Kisit.aciklama'?: string;
'Kisit.duraklamaNedeni'?: string;
'Kisit.tipID'?: UrAkisOperasyonListeGetGetKisitTipID;
'Kisit.atlandi'?: boolean;
'Kisit.duraklamaSure'?: number;
'Kisit.molaSure'?: number;
'Kisit.baslangic'?: Date;
'Kisit.bitis'?: Date;
'Kisit.baslangicSaat'?: string;
'Kisit.bitisSaat'?: string;
'Kisit.durum'?: boolean;
'Kisit.operasyonDetayID'?: number;
'Kisit.sorumluPersonelID'?: number;
'Kisit.kaliteKontrolBaslikID'?: number;
'Kisit.hammaddeListe'?: unknown[];
'Kisit.mamulListe'?: unknown[];
'Kisit.personelListe'?: unknown[];
'Kisit.hamIstifNo'?: string;
'Kisit.mamIstifNo'?: string;
'Kisit.molaSaatleri'?: unknown[];
/**
 * Listeleme işlemlerinde sıralama için kullanılacak kısıtı belirtir.
Örneğin, "Tarih", "Tarih:desc", "Tarih,Adi", "Tarih:desc,Adi" gibi bir değer alabilir.
 */
'SayfalandirmaBilgisi.siralamaKisiti'?: string;
/**
 * Geçerli sayfa numarasını (1'den başlar) alır veya ayarlar.
 */
'SayfalandirmaBilgisi.sayfa'?: number;
/**
 * Sayfa başına satır sayısını alır veya ayarlar. maxSayfaSatirSayisi değerini aşamaz.
 */
'SayfalandirmaBilgisi.sayfaSatirSayisi'?: number;
};
