/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { UrMakineListeGetGetKisitOnayDurum } from './urMakineListeGetGetKisitOnayDurum';
import type { UrMakineListeGetGetKisitTipID } from './urMakineListeGetGetKisitTipID';

export type UrMakineListeGetGetParams = {
'Kisit.olsTar'?: Date;
'Kisit.dgsTar'?: Date;
'Kisit.olsID'?: number;
'Kisit.olsKodu'?: string;
'Kisit.olsAdi'?: string;
'Kisit.dgsID'?: number;
'Kisit.dgsKodu'?: string;
'Kisit.dgsAdi'?: string;
'Kisit.onayDurum'?: UrMakineListeGetGetKisitOnayDurum;
'Kisit.subeKodu'?: string;
'Kisit.subeAdi'?: string;
'Kisit.sirketKodu'?: string;
'Kisit.sirketAdi'?: string;
'Kisit.tipKodu'?: string;
'Kisit.tipAdi'?: string;
'Kisit.bolumKodu'?: string;
'Kisit.bolumAdi'?: string;
'Kisit.makineID'?: number;
'Kisit.subeID'?: number;
'Kisit.sirketID'?: number;
'Kisit.makineKodu'?: string;
'Kisit.makineAdi'?: string;
'Kisit.demirbasID'?: number;
'Kisit.durum'?: boolean;
'Kisit.tipID'?: UrMakineListeGetGetKisitTipID;
'Kisit.kod1ID'?: number;
'Kisit.kod2ID'?: number;
'Kisit.kod3ID'?: number;
'Kisit.kod4ID'?: number;
'Kisit.kod5ID'?: number;
'Kisit.kod6ID'?: number;
'Kisit.etiket1ID'?: number;
'Kisit.etiket2ID'?: number;
'Kisit.etiket3ID'?: number;
'Kisit.etiket4ID'?: number;
'Kisit.etiket5ID'?: number;
'Kisit.cariID'?: number;
'Kisit.aciklama'?: string;
'Kisit.bolumID'?: number;
'Kisit.konumX'?: number;
'Kisit.konumY'?: number;
'Kisit.konumZ'?: number;
'Kisit.en'?: number;
'Kisit.boy'?: number;
'Kisit.yukseklik'?: number;
'Kisit.genelID'?: string;
'Kisit.planGosterimSira'?: number;
/**
 * Listeleme işlemlerinde sıralama için kullanılacak kısıtı belirtir.
Örneğin, "Tarih", "Tarih:desc", "Tarih,Adi", "Tarih:desc,Adi" gibi bir değer alabilir.
 */
'SayfalandirmaBilgisi.siralamaKisiti'?: string;
/**
 * Geçerli sayfa numarasını (1'den başlar) alır veya ayarlar.
 */
'SayfalandirmaBilgisi.sayfa'?: number;
/**
 * Sayfa başına satır sayısını alır veya ayarlar. maxSayfaSatirSayisi değerini aşamaz.
 */
'SayfalandirmaBilgisi.sayfaSatirSayisi'?: number;
};
