/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { UrOperasyonMakineBelgeEklePostBilgiTipID } from './urOperasyonMakineBelgeEklePostBilgiTipID';
import type { UrOperasyonMakineBelgeEklePostBilgiTabloID } from './urOperasyonMakineBelgeEklePostBilgiTabloID';

export type UrOperasyonMakineBelgeEklePostParams = {
'Bilgi.kartID'?: number;
'Bilgi.kartKodu'?: string;
'Bilgi.kartAdi'?: string;
'Bilgi.belgeAdresID'?: number;
'Bilgi.belgeAdresKodu'?: string;
'Bilgi.belgeAdresAdi'?: string;
'Bilgi.adres'?: string;
'Bilgi.depoID'?: number;
'Bilgi.stokRafID'?: number;
'Bilgi.depoNo'?: string;
'Bilgi.sayfaNo'?: string;
'Bilgi.dosyaNo'?: string;
'Bilgi.seviye'?: number;
'Bilgi.tabloSatirID'?: number;
'Bilgi.subeID'?: number;
'Bilgi.sirketID'?: number;
'Bilgi.tipID'?: UrOperasyonMakineBelgeEklePostBilgiTipID;
'Bilgi.tabloID'?: UrOperasyonMakineBelgeEklePostBilgiTabloID;
'Bilgi.kod1ID'?: number;
'Bilgi.kod2ID'?: number;
'Bilgi.kod3ID'?: number;
'Bilgi.kod4ID'?: number;
'Bilgi.kod5ID'?: number;
'Bilgi.kod6ID'?: number;
'Bilgi.etiket1ID'?: number;
'Bilgi.etiket2ID'?: number;
'Bilgi.etiket3ID'?: number;
'Bilgi.etiket4ID'?: number;
'Bilgi.etiket5ID'?: number;
};
