/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type { UrReceteOperasyonNotlarGetKisitTipID } from './urReceteOperasyonNotlarGetKisitTipID';
import type { UrReceteOperasyonNotlarGetKisitTabloID } from './urReceteOperasyonNotlarGetKisitTabloID';

export type UrReceteOperasyonNotlarGetParams = {
'Kisit.subeKodu'?: string;
'Kisit.subeAdi'?: string;
'Kisit.sirketKodu'?: string;
'Kisit.sirketAdi'?: string;
'Kisit.tipAdi'?: string;
'Kisit.tipKodu'?: string;
'Kisit.tabloAdi'?: string;
'Kisit.olsKodu'?: string;
'Kisit.olsAdi'?: string;
'Kisit.esnekAramaKisiti'?: string;
'Kisit.notID'?: number;
'Kisit.tabloSatirID'?: number;
'Kisit.notu'?: string;
'Kisit.subeID'?: number;
'Kisit.sirketID'?: number;
'Kisit.tipID'?: UrReceteOperasyonNotlarGetKisitTipID;
'Kisit.tabloID'?: UrReceteOperasyonNotlarGetKisitTabloID;
'Kisit.olsTar'?: Date;
'Kisit.olsID'?: number;
/**
 * Listeleme işlemlerinde sıralama için kullanılacak kısıtı belirtir.
Örneğin, "Tarih", "Tarih:desc", "Tarih,Adi", "Tarih:desc,Adi" gibi bir değer alabilir.
 */
'SayfalandirmaBilgisi.siralamaKisiti'?: string;
/**
 * Geçerli sayfa numarasını (1'den başlar) alır veya ayarlar.
 */
'SayfalandirmaBilgisi.sayfa'?: number;
/**
 * Sayfa başına satır sayısını alır veya ayarlar. maxSayfaSatirSayisi değerini aşamaz.
 */
'SayfalandirmaBilgisi.sayfaSatirSayisi'?: number;
};
