/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type {
  AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel,
  AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel,
  AaroKayitSonucAaroModullerSablonKayitSadeKayitModel,
  AaroKayitSonucAaroModullerSablonKayitSadeListeModel,
  AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSablonKayitSadeListeModel,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi,
  AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi,
  AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi,
  AaroModullerNotlarKayitSadeKayitModelBody,
  AaroModullerSablonKayitSadeKayitModelBody,
  LinqFilteringAdvancedFilterRequestBody,
  SablonBelgeEklePostParams,
  SablonBelgeEklePostPathParameters,
  SablonBelgeSilDeleteParams,
  SablonBelgeSilDeletePathParameters,
  SablonBelgelerGetParams,
  SablonBelgelerGetPathParameters,
  SablonDegisiklikGecmisiGetParams,
  SablonDegisiklikGecmisiGetPathParameters,
  SablonDeleteDeletePathParameters,
  SablonGetGetPathParameters,
  SablonGrupluListeGet200Four,
  SablonGrupluListeGet200One,
  SablonGrupluListeGet200Three,
  SablonGrupluListeGet200Two,
  SablonGrupluListeGetParams,
  SablonListeEsnekGet200Four,
  SablonListeEsnekGet200One,
  SablonListeEsnekGet200Three,
  SablonListeEsnekGet200Two,
  SablonListeEsnekGetParams,
  SablonListeGetGetParams,
  SablonNotEklePostPathParameters,
  SablonNotSilDeletePathParameters,
  SablonNotlarGetParams,
  SablonNotlarGetPathParameters,
  SablonOnayDurumuGetPathParameters,
  SablonOnaylaPostParams,
  SablonPutPutPathParameters,
  SablonReddetPostParams
} from '../../models';

import { customInstance } from '../../axios';



  export const getSablon = () => {
/**
 * @summary Belirtilen ID'ye sahip kaydı getirir. Kart detay bilgilerini döndürür.
INTENT: kaydı getir, detayı göster, bilgileri al, ID ile sorgula, kartı görüntüle
KULLANIM: Kart görüntüleme, düzenleme öncesi mevcut bilgileri alma.
 */
const Sablon_GetGet = (
    { id }: SablonGetGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerSablonKayitSadeListeModel>(
      {url: `/api/Sablon/${id}`, method: 'GET'
    },
      );
    }
  const Sablon_PutPut = (
    { id }: SablonPutPutPathParameters,
    aaroModullerSablonKayitSadeKayitModelBody: AaroModullerSablonKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerSablonKayitSadeListeModel>(
      {url: `/api/Sablon/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerSablonKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı siler veya pasifleştirir.
INTENT: sil, kaldır, pasifleştir, devre dışı bırak, kapat
KULLANIM: Artık kullanılmayan kayıtları sistemden kaldırma veya pasifleştirme.
IS_KURALLARI: Hareketi veya bağlı kaydı bulunan kartlar tamamen silinemez; yalnızca pasifleştirilebilir.
 */
const Sablon_DeleteDelete = (
    { id }: SablonDeleteDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerSablonKayitSadeListeModel>(
      {url: `/api/Sablon/${id}`, method: 'DELETE'
    },
      );
    }
  const Sablon_ListeGetGet = (
    params?: SablonListeGetGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSablonKayitSadeListeModel>(
      {url: `/api/Sablon`, method: 'GET',
        params
    },
      );
    }
  const Sablon_PostPost = (
    aaroModullerSablonKayitSadeKayitModelBody: AaroModullerSablonKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerSablonKayitSadeListeModel>(
      {url: `/api/Sablon`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerSablonKayitSadeKayitModelBody
    },
      );
    }
  /**
 * @summary Belirtilen kaydı onaylar. Onay akışındaki kaydı bir sonraki aşamaya taşır.
INTENT: onayla, kabul et, akışı ilerlet, onay ver
IS_KURALLARI: Kayıt onay akışında olmalı ve onaylanabilir durumda olmalı.
 */
const Sablon_OnaylaPost = (
    params?: SablonOnaylaPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerSablonKayitSadeKayitModel>(
      {url: `/api/Sablon/Onayla`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydı reddeder. Onay akışındaki kaydı geri gönderir.
INTENT: reddet, geri gönder, onaylama, iade et
IS_KURALLARI: Kayıt onay akışında ve reddedilebilir durumda olmalı.
 */
const Sablon_ReddetPost = (
    params?: SablonReddetPostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerSablonKayitSadeKayitModel>(
      {url: `/api/Sablon/Reddet`, method: 'POST',
        params
    },
      );
    }
  /**
 * FILTRE_FORMATI: {Alan}:{Operator}:{Deger}:{Mantik}
Operatörler:
  eq  — Eşit           örn: Durum:eq:True
  ct  — İçerir         örn: Ad:ct:Market
  sw  — İle başlar     örn: Kod:sw:A
  gt  — Büyüktür       örn: Bakiye:gt:5000
  in  — Listede        örn: GrupID:in:1|5|8   (değerler | ile ayrılır)
  lk  — Like (%)       örn: Adres:lk:İstanbul
Birden fazla filtre virgülle birleştirilir:
  örn: Sehir:eq:Istanbul:and,Bakiye:gt:5000:and,GrupID:in:1|5|8
            
SIRALAMA_FORMATI: {Alan}:{Yon}
  örn: Ad:asc,Bakiye:desc    (Varsayılan: Kod alanı artan)
            
SUTUN_SECIMI: Sadece ihtiyaç duyulan alanlar belirtilir; performansı artırır.
  örn: ID,Kod,Ad,Bakiye
 * @summary Dinamik ve esnek sorgulama altyapısı ile kayıt listesini getirir.
Kolon seçimi, karmaşık filtreler ve sıralama üzerinde tam kontrol sağlar.
INTENT: esnek sorgula, dinamik filtrele, özel alanları getir, karmaşık filtre uygula
KULLANIM: İnsan geliştirici ve harici entegrasyonlar için tasarlanmıştır.
          MCP ve AI çağrıları için POST /Liste tercih edilmelidir.
MCP_NOT: Bu endpoint MCP/AI çağrıları için önerilmez. 
         Tip güvensiz string filtreler hata üretme riski taşır.
         Karmaşık filtreler için POST /Liste kullanılır.
 */
const Sablon_ListeEsnekGet = (
    params?: SablonListeEsnekGetParams,
 ) => {
      return customInstance<SablonListeEsnekGet200One | SablonListeEsnekGet200Two | SablonListeEsnekGet200Three | SablonListeEsnekGet200Four>(
      {url: `/api/Sablon/Liste`, method: 'GET',
        params
    },
      );
    }
  const Sablon_ListePostPost = (
    linqFilteringAdvancedFilterRequestBody: LinqFilteringAdvancedFilterRequestBody,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerSablonKayitSadeListeModel>(
      {url: `/api/Sablon/Liste`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: linqFilteringAdvancedFilterRequestBody
    },
      );
    }
  /**
 * @summary Kayıtları belirtilen alanlara göre gruplayarak özet liste döndürür.
INTENT: grupla, özet al, gruplara göre say, gruplama raporu
KULLANIM: Gruplama bazlı raporlama ve istatistik sorgularında kullanılır.
YETKI: Hareket özeti admini gerektirir.
 */
const Sablon_GrupluListeGet = (
    params?: SablonGrupluListeGetParams,
 ) => {
      return customInstance<SablonGrupluListeGet200One | SablonGrupluListeGet200Two | SablonGrupluListeGet200Three | SablonGrupluListeGet200Four>(
      {url: `/api/Sablon/GrupluListe`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kaydın onay durumunu ve onay geçmişini getirir.
INTENT: onay durumu nedir, onaylandı mı, hangi aşamada, onay sorgula
KULLANIM: Onay akışı takibi, kaydın hangi adımda olduğunu öğrenme.
 */
const Sablon_OnayDurumuGet = (
    { id }: SablonOnayDurumuGetPathParameters,
 ) => {
      return customInstance<AaroKayitSonucSystemCollectionsGenericListAaroModullerOnayDurumBilgisiODBilgi>(
      {url: `/api/Sablon/${id}/OnayDurumu`, method: 'GET'
    },
      );
    }
  /**
 * @summary Belirtilen kaydın değişiklik geçmişini getirir. Kim, ne zaman, ne değiştirdi bilgisi.
INTENT: değişiklik geçmişi, kim değiştirdi, ne zaman değişti, log, audit, tarihçe
KULLANIM: Kayıt üzerinde yapılan tüm değişikliklerin izlenmesi ve denetimi.
 */
const Sablon_DegisiklikGecmisiGet = (
    { id }: SablonDegisiklikGecmisiGetPathParameters,
    params?: SablonDegisiklikGecmisiGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerDegisiklikLoglariKayitSadeLogBilgisi>(
      {url: `/api/Sablon/${id}/DegisiklikGecmisi`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait belge listesini getirir.
INTENT: belgeleri getir, dosyaları listele, ekleri göster, dokümanlar
KULLANIM: Kayda eklenmiş sözleşme, fatura, resim gibi belgelerin listelenmesi.
 */
const Sablon_BelgelerGet = (
    { id }: SablonBelgelerGetPathParameters,
    params?: SablonBelgelerGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerBelgeAdresKayitSadeBelgeBilgisi>(
      {url: `/api/Sablon/${id}/Belgeler`, method: 'GET',
        params
    },
      );
    }
  const Sablon_BelgeEklePost = (
    { id }: SablonBelgeEklePostPathParameters,
    params?: SablonBelgeEklePostParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/Sablon/${id}/BelgeEkle`, method: 'POST',
        params
    },
      );
    }
  const Sablon_BelgeSilDelete = (
    { id, belgeID }: SablonBelgeSilDeletePathParameters,
    params?: SablonBelgeSilDeleteParams,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerBelgeAdresKayitSadeKayitModel>(
      {url: `/api/Sablon/${id}/BelgeSil/${belgeID}`, method: 'DELETE',
        params
    },
      );
    }
  /**
 * @summary Belirtilen kayda ait notları getirir.
INTENT: notları getir, açıklamaları göster, yorumları listele, notlar neler
KULLANIM: Kayda eklenen serbest metin notların, hatırlatmaların veya açıklamaların listelenmesi.
 */
const Sablon_NotlarGet = (
    { id }: SablonNotlarGetPathParameters,
    params?: SablonNotlarGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericListAaroModullerNotlarKayitSadeNotBilgisi>(
      {url: `/api/Sablon/${id}/Notlar`, method: 'GET',
        params
    },
      );
    }
  const Sablon_NotEklePost = (
    { id }: SablonNotEklePostPathParameters,
    aaroModullerNotlarKayitSadeKayitModelBody: AaroModullerNotlarKayitSadeKayitModelBody,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/Sablon/${id}/NotEkle`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aaroModullerNotlarKayitSadeKayitModelBody
    },
      );
    }
  const Sablon_NotSilDelete = (
    { id, notID }: SablonNotSilDeletePathParameters,
 ) => {
      return customInstance<AaroKayitSonucAaroModullerNotlarKayitSadeKayitModel>(
      {url: `/api/Sablon/${id}/NotSil/${notID}`, method: 'DELETE'
    },
      );
    }
  return {Sablon_GetGet,Sablon_PutPut,Sablon_DeleteDelete,Sablon_ListeGetGet,Sablon_PostPost,Sablon_OnaylaPost,Sablon_ReddetPost,Sablon_ListeEsnekGet,Sablon_ListePostPost,Sablon_GrupluListeGet,Sablon_OnayDurumuGet,Sablon_DegisiklikGecmisiGet,Sablon_BelgelerGet,Sablon_BelgeEklePost,Sablon_BelgeSilDelete,Sablon_NotlarGet,Sablon_NotEklePost,Sablon_NotSilDelete}};
export type SablonGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSablon>['Sablon_GetGet']>>>
export type SablonPutPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSablon>['Sablon_PutPut']>>>
export type SablonDeleteDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSablon>['Sablon_DeleteDelete']>>>
export type SablonListeGetGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSablon>['Sablon_ListeGetGet']>>>
export type SablonPostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSablon>['Sablon_PostPost']>>>
export type SablonOnaylaPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSablon>['Sablon_OnaylaPost']>>>
export type SablonReddetPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSablon>['Sablon_ReddetPost']>>>
export type SablonListeEsnekGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSablon>['Sablon_ListeEsnekGet']>>>
export type SablonListePostPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSablon>['Sablon_ListePostPost']>>>
export type SablonGrupluListeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSablon>['Sablon_GrupluListeGet']>>>
export type SablonOnayDurumuGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSablon>['Sablon_OnayDurumuGet']>>>
export type SablonDegisiklikGecmisiGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSablon>['Sablon_DegisiklikGecmisiGet']>>>
export type SablonBelgelerGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSablon>['Sablon_BelgelerGet']>>>
export type SablonBelgeEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSablon>['Sablon_BelgeEklePost']>>>
export type SablonBelgeSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSablon>['Sablon_BelgeSilDelete']>>>
export type SablonNotlarGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSablon>['Sablon_NotlarGet']>>>
export type SablonNotEklePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSablon>['Sablon_NotEklePost']>>>
export type SablonNotSilDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSablon>['Sablon_NotSilDelete']>>>
