/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Aaro API
 * OpenAPI spec version: v1
 */
import type {
  AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerAlisIrsaliyesiHareketleriListeModel,
  AlisIrsaliyesiHareketleriDetayliListeGetParams
} from '../../models';

import { customInstance } from '../../axios';



  export const getAlisIrsaliyesiHareketleri = () => {
/**
 * @summary Filtrelenmiş alış irsaliyesi hareket listesini getirir. Ürün bazlı fiziksel giriş analizi sunar.
Alternatif İsimler: DeliveryLineList, ReceivingDetailQuery, IrsaliyeDetaySorgulama, GetReceivedItems
Kullanım: Depoya giren ürünlerin takibi, mal kabul listeleri, henüz faturalanmamış irsaliye kalemlerinin kontrolü.
MCP Kullanımı: Kullanıcının "Depoya giren ürünler hangileri?", "X tarihinde hangi malları teslim aldık?", "Henüz faturası gelmemiş irsaliye satırları neler?" gibi soruları için temel kaynaktır.
 */
const AlisIrsaliyesiHareketleri_DetayliListeGet = (
    params?: AlisIrsaliyesiHareketleriDetayliListeGetParams,
 ) => {
      return customInstance<AaroKayitSonucListeSystemCollectionsGenericIEnumerableAaroModullerAlisIrsaliyesiHareketleriListeModel>(
      {url: `/api/AlisIrsaliyesiHareketleri`, method: 'GET',
        params
    },
      );
    }
  return {AlisIrsaliyesiHareketleri_DetayliListeGet}};
export type AlisIrsaliyesiHareketleriDetayliListeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAlisIrsaliyesiHareketleri>['AlisIrsaliyesiHareketleri_DetayliListeGet']>>>
